### ISSUE TITLE
packets not forwarded to newly added endpoint 

### ISSUE THREAD

**Issue by dachulin** [projectcalico/calico#1085]
We are using calico with kubernetes. We create a service that expose a node port to outside in order to receive incoming packets. We then ran into a problem that sometimes our container not receiving incoming packets, whereas the host shows packets are coming into it's eth interface.

Further digging and found that if outside device started sending packets to our host before our service/pod is created, then that device's packets won't get switch to our containers. It seems like in this case, conntrack entries already created for packets from that particular device. Newly added iptable entries doesn't affects existing connections, until that connection times out. 

Wondering if there any existing configuration in calico that clears existing conntrack entry for newly added endpoints? 

If not, can this be added?

**Comment by lxpollitt** [comment]
This is a very interesting issue.  Thanks for raising it @dachulin.  It's intriguing because if it were a mainline issue with container bring up then I would have expected us to have hit it during our stress and scale testing.  So I'm wondering if it is particular to the node port scenario, and if so what the interaction is between the rules that k8s programs vs the rules that Calico programs.

cc @fasaxc @caseydavenport

**Comment by dachulin** [comment]
It doesn't seem to be specific to node port, kubernetes, nor calico. Instead, it seems like is the behavior of linux iptable rules.

We have done some experiments with Linux VM and iptable command only:
1. Have some endpoint stream UDP packets to our Linux VM.
2. Add an iptable nat rule to forward the incoming udp packets to different location.

With the above sequence, since udp packets present BEFORE we add the rule, the packets were not forwarded. 

We then stop the UDP stream, wait for some time for the conntrack to timeout, then resume the udp stream. Then our packets get forwarded.

If we explicitly clear the conntrack tables it also make the packets forwarded.

Such iptable rule behavior probably has less impact in legacy world, as rules are more or less static and not likely to changed frequent.

But it will have bigger impact in kubernetes or containers, since rules will be more likely to add/remove. So I am looking for a good way of handling it.

**Comment by fasaxc** [comment]
@dachulin This sounds like a kube-proxy issue (since kube-proxy handles service load balancing).  I recommend you raise it on the kubernetes issue tracker.

Are the packets being forwarded to another pod in the service?  From your description, that's what I'd expect, but that won't hep if the other pod has since been removed since the packets will get black-holed.

In general, flow stickiness is desirable in load balancing.  For TCP, it's essential because the connection will be reset if it moves to a different destination.  For UDP, it's generally desirable too but apparently not in your use case.  Can you adjust your application so that it cycles its source port more often; that would allow its stream to be rebalanced to a different destination pod?

I'm going to close this because I believe it's a k8s issue and it Calico doesn't have the required information about service IPs to clean up kube-proxy's conntrack entries.  Please re-open if you disagree!

**Comment by dachulin** [comment]
Are the packets being forwarded to another pod in the service? 
No, packets were being dropped. The service only have one pod.

We can't adjust the application to cycle its source port, since they are not under our control.

Wondering if calico creates IP table rules for kubernete services or only pods? If calico only creates ip table rules for pods, then I agree it should be fixed in kube proxy. If calico also handles the ip table rule creation for kube services, then I would think is better for calico to handle it.
