### ISSUE TITLE
Incorrect latest documentation warning

### ISSUE THREAD

**Issue by unixwitch** [projectcalico/calico#1087]
https://docs.projectcalico.org/v2.5/introduction/ says "Warning: You are viewing the v2.5 docs. Click here to view the docs for the latest release".  However, this is the documentation for 2.5, which is the latest release.  Clicking the link redirects back to the same page with the warning still in place.

**Comment by fasaxc** [comment]
Git bisected it down to this change: fdc6657a62447096fccafb345745b8868f1e63b6

**Comment by fasaxc** [comment]
@bcreane Looks like your commit above caused this issue.  Please can you take a look?  Some sort of difference depending on whether the YAML command is used via the container or not?

**Comment by fasaxc** [comment]
Note: I had to do a `make clean serve` to see the issue locally.  I guess the relevant file is cached by jekyll.

**Comment by bcreane** [comment]
looking now.

**Comment by bcreane** [comment]
Turns out `Makefile` is sensitive to anything that comes ahead of the current release stream declaration. Moving the new keys - `currentReleaseStream` and `htmlProoferLocalDirIgnore` to the end of _data/versions.yml fixes the issue.

I'll look into making versions.yml less brittle, but for now, I'll just push a fix for this one issue after I've done a bit more testing.

**Comment by bcreane** [comment]
@unixwitch - nicely spotted and thanks for raising this issue.
