### ISSUE TITLE
Usage Report version does not match actual version

### ISSUE THREAD

**Issue by mikev** [projectcalico/calico#1098]
Currently Usage Report is reporting a version of "1.4.0".  This matches the most recent GA release, but it does not match the actual software version which is "1.4.1b2".

We need to figure out why we are not retrieving the actual software version.  Specifically this is important to help us segregate UT usage reports from customer usage reports.

Also, ideally the version of the master branch is something such as "1.4.1b2-dev"

**Comment by fasaxc** [comment]
The problem is that no-one updated the version number when creating the release branch/tag.  Felix is getting the version number from setup.py, which wasn't updated when cutting the 1.4.1b2 branch.

The process is supposed to be: 

- cut a release branch from master
- update version numbers
- commit
- test a needed
- tag the release
- merge back to master so master now picks up the new 
- (remove release branch)

**Comment by mikev** [comment]
Verified fix.
