### ISSUE TITLE
Process about upgrade calico daemonset from 2.2.1 to 2.4.1 in k8s cluster

### ISSUE THREAD

**Issue by lcnsir** [projectcalico/calico#1112]
Hi I have try to upgrade calico from 2.2.1 to 2.4.1 in my k8s cluster, my cluster is kubernetes v1.7.3

When I read the process in here https://docs.projectcalico.org/v2.4/getting-started/kubernetes/upgrade#upgrading-to-v1-networkpolicy-semantics

It says that after using 
`kubectl apply -f calico-node.yaml.`

we need also manually delete pod on each node, since k8s do not support upgrade daemonset

but I found that https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment

k8s have support this feature, and I have tried to using
`kubectl apply -f calico-node.yaml.`
wait for a while, all calico node have been update on each nodes.

Do we need the steps about delete pod on each node ?

**Comment by tmjd** [comment]
If you are confident that calico-node has been restarted with the new version then it would not be necessary to delete the pods.  You can verify calico-node has been updated by doing `kubectl describe -n kube-system pod <calico-node-name> | grep Image`, and you should see the 2.4.1 calico/node version.

**Comment by caseydavenport** [comment]
> we need also manually delete pod on each node, since k8s do not support upgrade daemonset

Kubernetes supports DaemonSet upgrades now, so it sounds like that doc is out of date.

We should update (and update our manifests to enable rolling update by default)

**Comment by tmjd** [comment]
@lcnsir Did you enable rolling upgrade in your `calico-node.yaml`, I just tried applying the v2.4 manifest and while the policy-controller is updated the calico-node pods have not been (after more than 30 minutes)?

I do think the docs are currently correct because without enabling/specifying the rolling update, it is necessary to delete each of the calico-node pods to have them redeployed.

There is issue #777 that already exists for adding the rolling upgrade to the manifest.
I'm going to close this issue for now because I suspect @lcnsir has the rolling-upgrade option set so I don't think there is anything left to do on this issue since one exists for updating the docs already.
