### ISSUE TITLE
Automatic cleanup of stale WorkloadEndpoints

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/calico#1115]
We are seeing occasional "failed to add route file exists" errors that keep a pod forever in "ContainerCreating" state.  It looks like kubernetes is trying to create a pod that existed previously but wasn't cleaned up in calico properly. In my case, I got this error creating a pod where the pod didn't exist, but there was an existing workload endpoint in etcd that specified the pod name, namespace, and also the worker node that kubernetes was trying to create the pod on. I was able to work around it by manually deleting the orphan workload endpoint and then trying to create the pod again.  I delete the workload endpoint using: ```calicoctl delete --workload=<NS>.<POD_NAME> --orchestrator=k8s --node=<NODE_NAME> wep <NAME>```

Originally we thought this might be due to https://github.com/projectcalico/cni-plugin/issues/352  but since the workaround is to delete the unneeded WEP, I think this is different.  At the least, since our environments have these orphan WEPs, we need a way to handle this until we can move to a release where this is fixed.  I've started writing a script to programmatically delete orphan WEPs, but want to make sure that there is no use for a WEP that doesn't have a currently running pod.  I don't want to delete a WEP if it could cause a problem.  Note also that I reported this issue months ago in: https://github.com/projectcalico/calico/issues/681  but after investigation closed it because it wasn't causing any problems (we weren't seeing the "failed to add route file exists" error).  There was a doc issue opened from that issue (https://github.com/projectcalico/calico/issues/657), but from what I can tell it hasn't been worked since it was opened, and the latest comment is from 21 days ago

## Expected Behavior
I would expect that these workload endpoints would get deleted when the pod goes away, and if something prevents that, then periodically (daily maybe?) calico would run something to clean up orphans.

## Current Behavior
These WEPs do not get cleaned up, causing the "failed to add route file exists" errors that keep a pod forever in "ContainerCreating" state.

## Steps to Reproduce (for bugs)
I'll work on getting a definitive set of steps to create these orphan WEPs, but until then, just running a kubernetes environment for a few days, maybe killing kubelet or taking network interfaces up and down while deleting pods might do the trick.  You could even look at any existing environments you have, I used the following to see how many orphan WEPs I have compared to kube pods for them (172.30.0.0/16 is the subnet for our ippool):

Number of pods that are not using host networking: ```kubectl get pods -o wide --all-namespaces | grep "172\.30\." | wc -l```
Number of WEPs: ```/opt/bin/calicoctl get wep -o wide | grep "172\.30\." | wc -l```

## Context
This issue is affecting us because it prevents pods from starting successfully, and the only workaround we have is a manual one, listed above

## Your Environment
* Calico version: 2.1.5 (calico-node running as a systemd service)
* Orchestrator version: Kubernetes 1.5.6
* Operating System and version: Ubuntu 16.04.2

**Comment by caseydavenport** [comment]
@bradbehle thanks for raising.

Dumping some thoughts - I think there are two related issues here:

### 1) The kubelet isn't always able to notify Calico about all pod deletion events.

Since kubernetes 1.6 the kubelet should now call the Calico plugin in most scenarios in order to tear down old workloads - a number of windows have been closed, but not all of them.  The big one that remains is "I've decommissioned a node for good but didn't drain it first".

Like you say, a controller would be a good way to handle the remaining case - we could detect when Pods no longer exist in the k8s API and remove them after a time.  We need to make sure we don't delete a WEP that should be there, so we'll need to be careful, but it should be possible.

> "but want to make sure that there is no use for a WEP that doesn't have a currently running pod

There isn't a use for a WEP that doesn't have a currently running Pod.  However, you want to make sure not to delete a WEP for a pod that is in e.g. ContainerCreating state, since the script might race with the CNI plugin and end up in a bad state.

### 2) The CNI plugin isn't resilient to a route already existing when it attempts to do its route programming.

> closed it because it wasn't causing any problems (we weren't seeing the "failed to add route file exists" error)

It's only somewhat recent versions of the CNI plugin which attempt to write the route.  Older versions wouldn't have hit the problem even though the stale WEPs were present.  https://github.com/projectcalico/cni-plugin/pull/358 should fix the route programming failure and will be included in the next CNI plugin release.

**Comment by bradbehle** [comment]
@caseydavenport Thanks, that explanation helps a lot.  So just so I know I understand, you're saying that the https://github.com/projectcalico/cni-plugin/pull/358 fix should allow the a route to be written and allow these pods to come up and function properly, even if an existing route is there and a stale WEP is present?

**Comment by caseydavenport** [comment]
@bradbehle yep that's correct.

The old WEP will be updated by the CNI plugin (ensuring only one WEP exists for a given Pod) and the CNI plugin will be resilient to that route already existing.

**Comment by caseydavenport** [comment]
Update:
 
- 1) above is still an issue that we'll be looking to fix in the near future probably through a long-lived controller of some sort. 
- 2) above has a fix which has been merged to master and is included in v2.6.0.

**Comment by fasaxc** [comment]
I think the work in progress on the "node (cleanup) controller" is here: https://github.com/projectcalico/kube-controllers/pull/176

**Comment by fasaxc** [comment]
I believe the node cleanup controller and CNI fixes are all in v2.6.4+.
