### ISSUE TITLE
StrictAffinity in IPAMConfig struct couldn't be set with calicoctl

### ISSUE THREAD

**Issue by mdianjun** [projectcalico/calico#1577]
When a node uses up a block it will assign another block (and free it when it’s not longer needed).  Only if the whole pool is exhausted will it start using /32s.

In Calico v3.0, it is controlled by the IPAMConfig struct, but that doesn’t seem to be exposed in the v3.0 calicoctl.

* Calico version 3.0.1
* Orchestrator version kubernetes 1.8.4
* Operating System and version: Centos 7.2

**Comment by caseydavenport** [comment]
@mdianjun could you share a bit more about the behavior you'd like to see? Do you need to enable strict affinity for some reason and if so, what is that reason?

**Comment by mdianjun** [comment]
Blocks need to be fixed on PODs(data center POD, not k8s pod), and spine switches only allowed nodes to announce /26 routes, don’t allowed /32 routes. If nodes announce /32, spine switches will have too many routes.

**Comment by caseydavenport** [comment]
Gotcha.

Right now, looks like it needs to be done programmatically: https://github.com/projectcalico/libcalico-go/blob/master/lib/ipam/interface.go#L78-L80 

Note that /32s should not be announced unless the /26s are all exhausted, so in normal operation you shouldn't end up with many routes.

You can also [configure the CNI plugin on a given node](https://docs.projectcalico.org/v3.0/reference/cni-plugin/configuration#ipam) to assign from a specific IP pool in order to enable say, per-rack IP aggregation.

That might be enough to meet your requirements. That said, agreed it would be nice to make this configurable through calicoctl.

**Comment by caseydavenport** [comment]
We actually already have a v3 API object for this: https://github.com/projectcalico/libcalico-go/blob/master/lib/apis/v3/ipam_config.go

However, it's not plumbed through the main go client, or accessible through calicoctl. I think to do this we'd need to:

- Review if that struct is appropriate to expose to users.
- Adjust the clientv3 package to allow modification of that object.
- Update calicoctl with the updated client.

We also need to think about how CRUD works for this. the current struct doesn't behave the same way that other resources do in some subtle ways. For example, if there is no IPAMConfig, then a Get() currently returns one with default fields. This is probably not a desirable inconsistency, so we'll want to fix that up so CRUD works the right way.

Also, to be consistent with BGPConfiguration and FelixConfiguration, it should probably be called IPAMConfiguration :)

**Comment by libesz** [comment]
Could you confirm whether in case of KDD, writing directly the IPAMConfig CR into the K8S API (before any allocation took place) is also a valid solution for this?

**Comment by caseydavenport** [comment]
> Could you confirm whether in case of KDD, writing directly the IPAMConfig CR into the K8S API (before any allocation took place) is also a valid solution for this?

I would not endorse this. However, Calico v3.14. finally introduces the ability to do this in a supported way using calicoctl. Check it out!
