### ISSUE TITLE
IP assignment error: No configured Calico pools.

### ISSUE THREAD

**Issue by lluxury** [projectcalico/calico#1607]
docker: Error response from daemon: IpamDriver.RequestAddress: IP assignment error: No configured Calico pools.

## Steps to Reproduce (for bugs)

1.docker container run --net cal_net1 --name bbox1 -tid busybox
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
Could you provide a bit more information:
- What version of calico and docker you are using?
- Did you configure the cluster-store as specified at https://docs.projectcalico.org/v2.6/getting-started/docker/installation/requirements?
- How did you install Calico?

**Comment by ozdanborne** [comment]
Hi @lluxury , any update on this issue? Can you provide answers to @tmjd 's questions?

**Comment by caseydavenport** [comment]
@lluxury that error means you haven't configured any Calico IP pools. You can use `calicoctl` to query the existing pools and create a new one if needed.

See here: https://docs.projectcalico.org/v2.6/reference/calicoctl/resources/ippool

I'm going to close this for now since I think the error is pretty clear. Let us know if you hit any other troubles.
