### ISSUE TITLE
Pods can't communicate with each other after setting a networkpolicy

### ISSUE THREAD

**Issue by JacieChao** [projectcalico/calico#1619]
I'm a newer of kubernetes and calico. I had installed a kubernetes cluster by kubeadm. I was trying networkpolicy by kubernetes docs [[Declare Network Policy](https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/)] 

I found that when my nginx deployment scheduled to different nodes, it can't be accessed by busybox pod which in the same namespace with nginx.
```
/ # wget --spider --timeout=3 nginx.test01
Connecting to nginx.test01 (x.x.x.x:80)
wget: download timed out
```
Then I checked my calico policies and profile by calicoctl.
```
apiVersion: projectcalico.org/v3
kind: Profile
metadata:
  creationTimestamp: 2018-03-06T02:55:35Z
  name: kns.test01
  resourceVersion: "673493"
  uid: d7e98a83-20e9-11e8-aa4c-fa163edf28bb
spec:
  egress:
  - action: Allow
    destination: {}
    source: {}
  ingress:
  - action: Allow
    destination: {}
    source: {}
```
```
{
  "kind": "policyList",
  "apiVersion": "v1",
  "metadata": {},
  "items": [
    {
      "kind": "policy",
      "apiVersion": "v1",
      "metadata": {
        "name": "knp.default.test01.deny-other"
      },
      "spec": {
        "order": 1000,
        "ingress": [
          {
            "action": "allow",
            "source": {
              "selector": "calico/k8s_ns == 'test01'"
            },
            "destination": {}
          }
        ],
        "egress": [
          {
            "action": "allow",
            "source": {},
            "destination": {}
          }
        ],
        "selector": "calico/k8s_ns == 'test01'",
        "types": [
          "ingress"
        ]
      }
    }
  ]
}
```
I check my iptables of calico, it seemed that my request has been dropped.
```
Chain cali-tw-cali1a5b9d3e9c8 (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
1       26  1667 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:YO1o2QAYz_iO21I9 */ ctstate RELATED,ESTABLISHED
2        3   120 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:YUvMTLVGLWI4fQDF */ ctstate INVALID
3       14   840 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:hW_aCuICBcQdNTn- */ MARK and 0xfeffffff
4       13   780 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:gEW_qZnuvGXHAN_U */ /* Start of policies */ MARK and 0xfdffffff
5       13   780 cali-pi-_O1Fbml_l7jiYebYgyJW  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:nhSLNvI0_HJqWgXD */ mark match 0x0/0x2000000
6        3   180 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:j5_oFEkaL96O920y */ /* Return if policy accepted */ mark match 0x1000000/0x1000000
7        2   120 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:mvEgcrYhfDxXvSSR */ /* Drop if no policies passed packet */ mark match 0x0/0x2000000
8        0     0 cali-pri-k8s_ns.test01  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:SHTsWVbMKWU0mIgW */
9        0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:Vx_fZaEUWon-i5Z7 */ /* Return if profile accepted */ mark match 0x1000000/0x1000000
10       0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:22R96zPTwHOhDxVD */ /* Drop if no profiles matched */
```

## Your Environment
* Calico v3.0.3
* kubernetes v1.9.3
* docker 1.13.1

**Comment by tmjd** [comment]
Sorry for not responding here sooner.
Did you ensure the requirements listed [here](https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/#requirements) were satisfied in your setup?  Specifically did you set `--pod-network-cidr`?  Since you are using a dns address that I'm guessing maps to a service IP, IIRC if you do not have that flag set then all traffic would be NAT'ed and would appear to come from the host's IP address instead of the pod's IP address and cause it to be dropped.

**Comment by JacieChao** [comment]
Thank you for your help. I still confuse about this question. Yes, I set --pod-networ-cidr parameter when I executed kubeadm command. If I delete the network policy, two pods in different nodes could communicate with each other well.

**Comment by tmjd** [comment]
I want to double check what you are doing and the behavior your are observing:
- Both your nginx and busybox pods are being deployed into at test01 namespace.  I'm assuming this since I believe your policy is selecting for that namespace.
- When the busybox and nginx pod are on the same node then the traffic works as expected.
- When your pods are on different nodes the traffic does not work.

Could you setup your pods so they are on different hosts and then run tcpdump on the node with nginx? Assuming you are using the default port 80 you could do `sudo tcpdump -i any port 80` and see if the traffic destined for the pod has the source address of the busy box pod.  That does assume that the traffic is reaching the destination node, you didn't mention in the iptables output if that was on the destination or source host.

**Comment by JacieChao** [comment]
Sorry for bothering you. I create a new cluster in VMWare. It works well. The cluster with problem have been running on Open Stack, maybe there's something wrong with my calico configuration. I will verify it clearly later. If I still have problem, I will reopen this issue. 

Once again, Thank you for your help.
