### ISSUE TITLE
Calico v3.0.1 unit test failures for s390x

### ISSUE THREAD

**Issue by samding01** [projectcalico/calico#1677]
Running `Calico v3.0,1 - calico/node` unit test by `make st` got 6 failures on s390x compared to on m86_64.  The problems are all no `ping` access from `workload` to `host`. 
 
## Current Behavior

Here are the 6 failures of total 86 test cases

     [fail] 5.64% tests.st.bgp.test_ipip.TestIPIP.test_gce_rr_0: 126.6380s
     [fail] 4.98% tests.st.bgp.test_single_route_reflector.TestSingleRouteReflector.test_bird_single_route_reflector_default_as: 111.7421s
     [fail] 4.98% tests.st.bgp.test_single_route_reflector.TestSingleRouteReflector.test_bird_single_route_reflector: 111.7111s
     [fail] 4.57% tests.st.bgp.test_ipip.TestIPIP.test_gce_rr_1: 102.5084s
     [fail] 3.60% tests.st.bgp.test_ipip.TestIPIP.test_gce_0: 80.8738s
     [fail] 2.62% tests.st.bgp.test_ipip.TestIPIP.test_gce_1: 58.7348s

Here are logs of `TestSingleRouteReflector.test_bird_single_route_reflector` on both x86 and s390x
[s390x.log](https://github.com/projectcalico/calico/files/1708862/s390x.log)
[x86.log](https://github.com/projectcalico/calico/files/1708863/x86.log)

Compare the both logs, they are almost similar until line :343, but after `create -f testfile.json`,

         docker exec -it host1 sh -c 'docker exec workload1 ping -c 1 -W 1 192.168.232.128'

gets access on x86 , but not on x390x. 
The log of `felix` does not show any `ERROR`, but  there is a `WARNING` (line :1705)

      # 2018-02-08 17:00:30.789 [WARNING][84] active_rules_calculator.go 288: Profile not known or invalid, generating dummy profile that drops all traffic. profileID="subnet1"^M

What does this mean?
The previous Calico versions do not have such an issue for the similar usages, what is the special changes of   v3.0.1? 

What is the reason of the problems, any hint?

## Steps to Reproduce (for bugs)

1. under `calico/calico_node`, run command `ST_TO_RUN=tests/st/bgp/test_single_route_reflector.py:TestSingleRouteReflector.test_bird_single_route_reflector make st`
2.
3.
4.

## Your Environment

* Calico version: v3.0.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version: RHEL 7.x and Ubuntu 
* Link to your project (optional):

**Comment by fasaxc** [comment]
Unfortunately, the system tests can be a little tricky to diagnose because they test lots of components together.

That warning means that your workload endpoint uses a profile called "subnet1", i.e. it has `wep.Spec.ProfileIDs=[]string{...,"subnet1",...}` but, at the point the active rules calculator sees the workload endpoint, it doesn't have that profile.  That could be because

- the profile is missing
- the profile is missing now, but is about to be created
- the profile failed validation so it was dropped; I'd expect more warnings or errors if that was the case.

Since you're seeing workload to host failures, it could be a difference in system-wide iptables policy between your systems.  Do you have a different iptables INPUT policy set on your s390x system?

**Comment by samding01** [comment]
@fasaxc 
Both `host1` and `host2` has the profile `subnet1`

       docker exec -it host1 sh -c 'export ETCD_ENDPOINTS=http://9.23.30.55:2379; export ETCD_CA_CERT_FILE=; export ETCD_CERT_FILE=; export ETCD_KEY_FILE=; /code/dist/calicoctl get profile'
      NAME
      subnet1

Which is the same on x86_64. 
As for the `iptables` INPUT policy, how can I verify if there is any?

**Comment by samding01** [comment]
Checking the `iptables` INPUT policy, did not find any difference between x86_64 and s390x.
It is suggested that the next step is to reproduce the problem and investigate

**Comment by caseydavenport** [comment]
Going to close this, since v3.0 is several releases back.

Please reopen if hitting this on modern releases.
