### ISSUE TITLE
Should calico support ip assignment based on timestamp?

### ISSUE THREAD

**Issue by mdianjun** [projectcalico/calico#1732]
This is a scene which we are facing with:

A statefulset has some pods, and the client accesses the pods via headless service. If pod-1(with ip-1) is rescheduled and assigned a new pod ip (ip-2), in the mean time pod-2 is created with ip-1. The client which connected with pod-1 previously still connects to ip-1,  because of the dns cache ttl in the client. However, ip-1 is used by pod-2 which might provide different data.

Now, the ip assignment in calico is based on FIFO, which will ease the problem, but not guaranteed.

The workaround we could figure out is, terminationGracePeriodSeconds is set in pods to assure the dns cache ttl is expired.

If calico could assign ip which has been released for a certain time to assure that the dns cache ttl is expired, is it a better solution?

**Comment by caseydavenport** [comment]
I think this is an interesting idea, and I'd be happy to explore more. As you noted, Calico IPAM is designed such that it won't re-use a recently released IP address within a block if there are any others because it appends the released IP to the end of the "queue". This is meant to alleviate this issue, but obviously if there's only one or two IPs left on a node then it won't work as well.

How often are you seeing this happen and what is the service impact? Would it be possible to simply use a k8s ClusterIP in front of your services to get a stable address? 

It's likely a substantial amount of work to implement time-based IP re-allocations, and potentially could introduce other unwanted side-effects (like a more fragmented use of the IP space).

**Comment by mdianjun** [comment]
@caseydavenport  We have some stateful applications to be deployed, such as kafka, hbase. K8s StatefulSet will be used to implement this requirement. K8s ClusterIP couldn't be used for the issue, because it couldn't  be accessed from outside of the cluster. The client needs to connect to each Pod IP directly, so Headless Service is appropriate.

About kafka, clients get broker IPs from zookeeper, this way is better. But there are a few problems about authentication. We switch to use hostNetwork temporarily.
