### ISSUE TITLE
Standardize sample dummy IP ranges

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#179]
As per the heading.

**Comment by djosborne** [comment]
Wikipedia says the test-net documentation ranges include:

- 192.0.2.0/24
- 198.51.100.0/24
- 203.0.113.0/24

I'd argue that since our default pool is `192.168.0.0/16`, we should use that for all container examples.

And since most of our Vagrant demos use `172.16.0.0/12`, we should use that to represent hosts.

That way, our documentation and demos can stay more aligned.

What prompted this issue? Were users reporting conflicts with local IP ranges?
