### ISSUE TITLE
Add PriorityClass to Calico manifests

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1844]
From the Kubernetes API:

```
        // If specified, indicates the pod's priority. "system-node-critical" and
        // "system-cluster-critical" are two special keywords which indicate the
        // highest priorities with the former being the highest priority. Any other
        // name must be defined by creating a PriorityClass object with that name.
        // If not specified, the pod priority will be default or zero if there is no
        // default.
        // +optional
        PriorityClassName string
```

This was introduced as alpha in v1.9, and is scheduled for beta in v1.11.

Once it goes beta we should probably add it to our manifests.

https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass

## Expected Behavior

`priorityClassName: system-node-critical`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by jbehrends** [comment]
This appears to have already been done in the latest 3.8.x versions of the manifests:
https://docs.projectcalico.org/v3.8/manifests/calico.yaml
https://docs.projectcalico.org/v3.8/manifests/calico-typha.yaml
https://docs.projectcalico.org/v3.8/manifests/calico-etcd.yaml

As a cleanup task though the annotation "**scheduler.alpha.kubernetes.io/critical-pod**" should be removed from the above manifests since it was replaced by "**priorityClassName**" and no longer does anything since K8s v1.14, as per: https://v1-12.docs.kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Comment by fasaxc** [comment]
Looks like those cleanups have been done too, now.
