### ISSUE TITLE
Port requirements for Calico

### ISSUE THREAD

**Issue by cyrilbkr** [projectcalico/calico#1860]
Hi, 
I m currently installing k8s onprem with k8s worker nodes split on different vlan with firewalls. 
What is the ports needed for calico ? found nothing in the doc 
Thank you

**Comment by tmjd** [comment]
You'll need BGP open, if you have IPIP enabled then you'll need it open, datastore access (etcd or Kubernetes).  If you're not using IPIP then you'd basically need everything open that your pods will need open as the traffic won't be encapsulated, though since you said different vlans I think you will be using IPIP.

You can check out the master docs as there has been some rework done there consolidating the requirements https://docs.projectcalico.org/master/getting-started/kubernetes/requirements.

Hope that helps.

**Comment by emanic** [comment]
Closing this as I believe we have this information in the requirements now. If any issues remain, feel free to reopen it. Thanks... cc @caseydavenport
