### ISSUE TITLE
Calico pods in CrashLoopBackOff

### ISSUE THREAD

**Issue by martcturvey** [projectcalico/calico#1867]
Hi, seem to have a problem in Calico with a cluster that has been up & running for a while. A number of pods in CrashLoopBackOff, but calico-node pods seem to be the cause.

## Expected Behavior
calico-node pods running normally

## Current Behavior
All calico-node pods are in CrashLoopBackOff
kube-system     calico-node-9gxns                                                    1/2       CrashLoopBackOff   364        118d
kube-system     calico-node-9jqx6                                                    1/2       CrashLoopBackOff   1186       118d
kube-system     calico-node-b6b7b                                                    1/2       CrashLoopBackOff   1742       118d
kube-system     calico-node-pct6c                                                    1/2       CrashLoopBackOff   160        118d
kube-system     calico-node-vwbxv                                                    1/2       CrashLoopBackOff   125        118d

$ kubectl logs calico-node-9gxns -n kube-system -c calico-node
Skipping datastore connection test
Using autodetected IPv4 address on interface eth0: xx.xx.xx.221/20
Calico node 'ip-xx-xx-xx-221.eu-west-2.compute.internal' is already using the IPv4 address xx.xx.xx.221:
 -  Check the node configuration to remove the IP address conflict
Terminating
Calico node failed to start

Appeared similar to https://github.com/projectcalico/calico/issues/1628

Installed calicoctl using https://docs.projectcalico.org/v3.0/usage/calicoctl/install (used Kubernetes API store instructions)

kubectl exec -ti -n kube-system calicoctl -- ash
~ # calicoctl get nodes -o wide
NAME                                         ASN         IPV4   IPV6   
ip-xx-xx-xx-78.eu-west-2.compute.internal    (unknown)                 
ip-xx-xx-xx-133.eu-west-2.compute.internal   (unknown)                 
ip-xx-xx-xx-183.eu-west-2.compute.internal   (unknown)                 
ip-xx-xx-xx-221.eu-west-2.compute.internal   (unknown)                 
ip-xx-xx-xx-128.eu-west-2.compute.internal   (unknown)

No IPV4 information showing

~ # calicoctl delete node ip-xx-xx-xx-183.eu-west-2.compute.internal
Failed to delete 'Node' resource: operation Delete is not supported on Node(ip-xx-xx-xx-183.eu-west-2.compute.internal)

Still investigating but a little stuck on how to proceed with Calico at the moment

## Steps to Reproduce (for bugs)
Have not found the trigger, cluster was up & running for 118 days

## Context
All pods dependent on calico network failed into CrashLoopBackOff

## Your Environment

Cluster created with kops 1.8.0 using kubernetes 1.8.4

**Comment by tmjd** [comment]
You linked to the calico v3.0 docs, though you are using kops 1.8.0 which I'm certain kops is not utilizing yet.  Also I see you said you used the kubernetes datastore installation which kops does not use for Calico, it uses ETCD as the datastore.  One or both of those are why your `calicoctl get nodes -o wide` is showing unknown. You should check on the version of Calico you are using and grab the matching calicoctl version (check the release page https://docs.projectcalico.org/v2.6/releases/) and determine your ETCD configuration.

My first guess here is that you are using autoscaling in AWS which is problematic without enabling the Node controller feature on calico/kube-controllers.  That is because nodes are not automatically cleaned up out of the datastore so when nodes are autoscaled they do not get cleaned up causing new nodes to appear to be using already existing node IPs.  You should be able to get your current nodes back to a good state by removing the old node entries as you've tried (once you are using the correct version and configuration).  Here is a link to the [Decomissioning a Node](https://docs.projectcalico.org/v2.6/usage/decommissioning-a-node) guide but it is basically what you are doing to delete the nodes.

A more permanent solution is to add the configuration to calico-node and calico-kube-controllers to enable the node controller which will automatically clean up old nodes as it has been added in the next kops release (see https://github.com/kubernetes/kops/blob/1.9.0-beta.2/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template#L341).  Or alternately disable auto-scaling, if possible (I'm not a kops expert).

**Comment by martcturvey** [comment]
@tmjd OK, that's allowed me to see what's been going wrong with the nodes & tidy things up. Thanks for your help.
