### ISSUE TITLE
OpenStack v2->v3  upgrade guide doesn't cover etcd proxy migration

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1959]
etcd v2 supported proxies and setting up a proxy per host was typical.  etcd v3 doesn't support such proxies (it has gateways instead).  We should mention that gotcha in the guide.

## Expected Behavior

Guide should tell user to migrate away from proxies before upgrading.  I.e.

- upgrade etcd to v3 (still using v2 API)
- adjust felix config to talk directly to etcd cluster, not via proxy, or install a gateway instead of proxy
- do upgrade

## Current Behavior

Not mentioned so user may upgrade while still trying to use a proxy and be stuck with a non-working system.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version  v2.6.x -> v3.1.x migration
* Orchestrator version (e.g. kubernetes, mesos, rkt): Openstack
* Operating System and version:
* Link to your project (optional):

**Comment by jocado** [comment]
I can add a small note here regarding the gateway.

We migrated to the gateway instead of the proxy before the upgrade, and it worked pretty seamlessly.

One thing to watch out for, the gateway can only be configured  to listen on one IP:Port pair, and it defaults to port `127.0.01:23790`

Because we migrated from 2.6, we had to make sure the felix and calico-dhcp-agent were using the standard etcd port `2379` [ I think dhcp-agent was using 4001 by default ], and then we set the gateway to use `127.0.01:2379`.

Notes on the gateway config may be out of scope for the docs, but someone may find this info useful none the less.

**Comment by neiljerram** [comment]
Honestly I really wonder if a doc change here is worth it.  v2->v3 is receding into the past now, and I suspect our users (exemplified by @jocado !) are already familiar with the proxy/gateway options for etcdv3.  @caseydavenport WDYT, can we just close this?

**Comment by caseydavenport** [comment]
@neiljerram I agree completely. I think this is out of scope for the Calico docs, especially given the age.
