### ISSUE TITLE
Replace Kubernetes privileged=true with more precise permissions

### ISSUE THREAD

**Issue by danderson** [projectcalico/calico#2000]
## Expected Behavior

The Calico node agent grants itself privileged=true when run on Kubernetes. This effectively disables all container security. It would be preferable to open up just the pinhole permissions that the agent needs.

## Current Behavior

The node agent sets --privileged, which translates to allowing access to all of /dev, enabling all capabilities (e.g. read all files, kill any process, load kernel modules, reboot the system, set system time...), and disabling seccomp and apparmor sandboxing (although those are currently no-op on k8s, be).

This is way more privilege than a networking agent needs. In addition to being poor practice in the abstract, the node agent forks and runs Bird, which is a network-enabled C binary with a history of "classic" C security vulnerabilities (stack overflows, use-after-free, ...). This makes it all the more important to sandbox this attack vector, so that an 0day doesn't translate to root@node.

## Possible Solution

I believe the node agent would be happy with a couple different possibilities:

 - `hostNetwork: true`, running as root, with all capabilities dropped except CAP_NET_ADMIN and `allowPrivilegeEscalation: false`
 - same as above, but also running as non-root with the binary setcap'd to allow CAP_NET_ADMIN (required because k8s doesn't set ambient capabilities).
 - same as above, but also with apparmor and seccomp sandboxes enabled with the default docker profile (possibly more dicey because uses alpha and beta annotations)

I'm not super familiar with Calico internals, but my understanding is that the only "fancy" things it does is manipulate network interfaces and iptables, both of which are granted by just CAP_NET_ADMIN.

## Steps to Reproduce (for bugs)

- Examine Calico manifests before running `kubectl apply`, because `curl | sudo bash` is an antipattern.
- Have your spidey sense triggered by `securityContext.privileged=true`, which approximately no container ever really needs.

## Your Environment
* Calico version: 3.1.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.10.2

**Comment by danderson** [comment]
Okay, did some experimenting, and a couple of things:

 - We need CAP_NET_RAW as well, because `iptables-save` and friends need it to speak netlink to the kernel.
 - With `privileged=false`, /proc is mounted read-only, so setting `rp_filter` on interfaces fails.

The second one is tricky, because there's no knob in k8s to selectively allow /proc access without allowing ~everything.

There is a solution, but it requires a change to the node agent: we can mount the host /proc/sys/net under /host_proc_sys_net in the container, and tell Calico to use that rather than /proc/sys/net for all its proc-setting needs. As a bonus, that isolates Calico's powers specifically to only network-related tunables.

Would y'all be interested in a pull request to make this happen?

**Comment by cvernooy23** [comment]
any update on this?

**Comment by lwr20** [comment]
This work in currently in progress. 
 e.g. https://github.com/projectcalico/calico/commit/624099cbc8a9cde09e7842f3b867b929a0c784cf

**Comment by hazcod** [comment]
Was this ever picked up again? Seeing this issue pop up on GKE for Calico.

**Comment by lwr20** [comment]
This work is still ongoing.  It turns out that there is no way to set limited permissions on Calico node and have all its features (especially BPF) work.  The compromise that I think it being worked on is to have the tigera-operator installer figure out when features are enabled which need this setting and *only* set `privileged=true` when its really needed. 

@mgleung did I get that correct?

Unfortunately, getting this fix into GKE may take a while - they are still running Calico v3.8, I believe, and are unlikely to ever want to use the operator installer.  However, I'm sure the GKE team will want to use a manifest with the minimum permissions needed when they upgrade, so I'd imagine they'd basically use the manifest that the operator would have created for them (if you see what I mean).

**Comment by mgleung** [comment]
Yup, there are some features in Calico node that require running as a privileged container in order to work properly. We're looking into splitting some things out and refactoring the logic so that we can offer up a minimal feature set that does not need `privileged=true` but that work is still ongoing.

**Comment by fasaxc** [comment]
> we can mount the host /proc/sys/net under /host_proc_sys_net in the container, and tell Calico to use that rather than /proc/sys/net for all its proc-setting needs

@mgleung Is that one that you tried?  Sounds like a meaningful improvement over needing `/proc/sys` for the cases where we don't need full access to `/proc`. I guess BPF would still be a problem due to needing to set the BPF programs on the cgroups and the like.

**Comment by mgleung** [comment]
> we can mount the host /proc/sys/net under /host_proc_sys_net in the container, and tell Calico to use that rather than /proc/sys/net for all its proc-setting needs
I tried something similar a while back for testing if we could run eBPF without privileges as well. I remember there were some permission issues with writing the BPF maps (not just the cgroups) but I'm not sure if I tried it with the `sysctl` settings. Definitely something to try.

**Comment by mgleung** [comment]
@mithilarun sorry for the delay, we rolled out the ability to run calico-node as a non-privileged and non-root container as a part of the v3.21.0 release. There are a few tradeoffs we had to make in order to accomplish this though. You can find the instructions for enabling this as well as a more detailed list of the drawbacks in the docs: https://projectcalico.docs.tigera.io/security/non-privileged .
