### ISSUE TITLE
Disabled ip-pools are picked up by bird_ipam.cfg

### ISSUE THREAD

**Issue by m4r10k** [projectcalico/calico#2064]
## Expected Behavior
If I disable an IP-Pool I expect that it is not picked up by calico-node in `bird_ipam.cfg` and it therefore does not create ip routes.

## Current Behavior
A disabled IP-Pool is still active in `bird_ipam.cfg` which results in the usage of it, which in turn results in active ip routes to the disabled IP-Pool.

## Possible Solution
Delete the IP-Pool comleatly (`calicoctl delete -f`) to get rid of it.

## Steps to Reproduce (for bugs)
1. Disable IP Pool
~~~
NAME                  CIDR               NAT    IPIPMODE   DISABLED   
default-ipv4-ippool   192.168.128.0/19   true   Always     true       
pool-x-1             192.168.160.0/24   true   Always     false      
pool-y-1             192.168.161.0/25   true   Always     false 
~~~
2. Cat the bird_ipam.cfg
~~~
# Generated by confd
filter calico_pools {
  calico_aggr();

  if ( net ~ 192.168.128.0/19 ) then {
    accept;
  }

  if ( net ~ 192.168.160.0/24 ) then {
    accept;
  }

  if ( net ~ 192.168.161.0/25 ) then {
    accept;
  }

  reject;
}


filter calico_ipip {

  if ( net ~ 192.168.128.0/19 ) then {

    krt_tunnel = "tunl0";
    accept;
  }

  if ( net ~ 192.168.160.0/24 ) then {

    krt_tunnel = "tunl0";
    accept;
  }

  if ( net ~ 192.168.161.0/25 ) then {

    krt_tunnel = "tunl0";
    accept;
  }

  accept;
}
~~~
3. Check ip routes
~~~
192.168.129.128/26 via x dev ens160  proto bird 
192.168.143.64/26 via x dev ens160  proto bird 
192.168.144.128/26 via x dev ens160  proto bird 
192.168.152.192/26 via x dev ens160  proto bird 
192.168.154.192/26 via x dev ens160  proto bird 
~~~

## Context
If I want to move the IP-Pool from one cluster to another one, and if I am using the same RR for both, the resulting routes would target the wrong nodes.

## Your Environment
* Calico version 
~~~
Client Version:    v2.0.4
Build date:        2018-04-20T19:51:26+0000
Git commit:        cd12a632
Cluster Version:   v3.1.1
Cluster Type:      k8s,bgp
~~~
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes native on-premise 1.10

**Comment by caseydavenport** [comment]
@m4r10k hm, yes.

I believe it currently advertises blocks the same way because disabling the IP pool doesn't remove any allocations, it just prevents new allocations from that pool.

So, one wouldn't want disabling an IP pool to actually remove the routes and thus break running workloads. 

I believe for migration purposes, the steps would look something like this:
- Disable the IP Pool
- Create the new pool.
- Restart any pods still using that pool so they get new IPs
- Once there are no workloads using that pool any more, delete it.
- Then, add the pool to the new cluster. 

Does that work?

**Comment by m4r10k** [comment]
@caseydavenport Yes, that is the correct sequence and this does work correctly. The only thing which is a little bit confusing is, that even if the node is rebooted and therefore there can't be any workloads left with the old ip pool (because it is disabled) on that node, it still maintains a routing table for the old network. That's all. :smiley: 

I guess this sequence on how to delete an ip pool should be part of the documentation maybe (like the add ip-pool)?

**Comment by caseydavenport** [comment]
> that even if the node is rebooted and therefore there can't be any workloads left with the old ip pool (because it is disabled) on that node, it still maintains a routing table for the old network. 

Yep, that is a little bit confusing, but a side-effect of the route aggregation that Calico performs. I think given that migrating an IP pool to another cluster is a relatively rare corner case, and that the above steps work in this scenario, that this is OK.

> I guess this sequence on how to delete an ip pool should be part of the documentation maybe (like the add ip-pool)?

We have docs for a similar case here: https://docs.projectcalico.org/v3.1/usage/changing-ip-pools

However, that doc covers changing IP pools on an existing cluster rather than moving an IP pool to a different cluster.

I'm going to close this since I believe in this scenario Calico is working as expected.

**Comment by m4r10k** [comment]
Yes it is a corner case and after some thinking about it, your explanation makes sense! Thank you for your time!
