### ISSUE TITLE
Monitoring the remaining available IPs for a specific IPpool

### ISSUE THREAD

**Issue by luzhongming** [projectcalico/calico#2164]
【Question】How to retrieve the remaining available IPs for a specific IPpool?

**Comment by caseydavenport** [comment]
Support for viewing IPAM allocations is currently very limited.

The best option is probably `calicoctl ipam show` as doc'd here: https://docs.projectcalico.org/v3.2/reference/calicoctl/commands/ipam/show

However, it only can show a single IP at a time currently.  Otherwise, you'd need to look into the datastore itself using `etcdctl`.

**Comment by luzhongming** [comment]
Thanks for your reply@caseydavenport. Could you make an example for viewing IPAM allocations  by using etcdctl? Thanks a lot.

**Comment by caseydavenport** [comment]
You can do this in Calico v3.8 using new `calicoctl ipam show` functionality
