### ISSUE TITLE
Release page for OpenStack is inconsistent

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#238]
The releases for OpenStack should fit into the same table as the rest of the components, rather than being a separate paragraph.

See http://docs.projectcalico.org/v2.0/releases/

**Comment by neiljerram** [comment]
Why? That just isn't how we've been releasing Calico for OpenStack.

**Comment by caseydavenport** [comment]
Well, the intention of that page is to be a listing of components and their version numbers for a specific Calico release.

I'm personally not really up to speed on what is actually in the OpenStack packages - is it anything more than a packaging of the components listed in the release table above?

_If_ it is actually something that belongs on this page, what's wrong with adding a table row like this?

| Component                        | Version
---------------------------|------------------------------
| Ubuntu PPA                       | [ppa:project-calico/calico-2.0.0-beta](https://launchpad.net/~project-calico/+archive/ubuntu/calico-2.0.0-beta)

**Comment by neiljerram** [comment]
I think your proposal may be good, but it depends on the future mapping between Felix and Calico versions. Calico for OpenStack is Felix + networking-calico, and as we knew that a big Felix change was coming (i.e. Golang), we decided to have PPAs corresponding to X.Y Felix series; so we have a 'calico-1.4' PPA that always has the latest Felix 1.4.z release, and the corresponding networking-calico from the same time. 

Then you guys suddenly invented 'Calico 1.5' and 'Calico 1.6', both mapping to Felix 1.4.z and hence to the 'calico-1.4' PPA...

Looking forwards: I think it still makes sense for us to have felix-X.Y PPAs for OpenStack, like felix-2.0 now. But there may not be a sensible mapping to Calico versions; e.g. if Calico 2.0 has Felix 2.0.0 a Calico 2.1 has Felix 2.0.1, the release page for 2.0 will then say Felix 2.0.0 and PPA felix-2.0, but that PPA will have packages from Felix 2.0.1.

(Banking this comment now because it’s really painful typing it on my phone! )

**Comment by neiljerram** [comment]
OK, after writing all that, and thinking about it, I think this is another case of: 'releases' do not have to correspond to packaging.  (I say 'another' because this is also an aspect of the Felix release process work that I'm doing.)

So in fact I think we should perhaps just add networking-calico to that table, and remove the stuff about the PPA and RPM repo; and any PPAs / repos could explain themselves elsewhere.

WDYT about that?

**Comment by caseydavenport** [comment]
I was halfway through writing up that thought myself :)
