### ISSUE TITLE
calico local build problem

### ISSUE THREAD

**Issue by zppznn** [projectcalico/calico#2476]
HI guys, I copy confd, felix, libaco-go directories to the same directory as node repo, and I change the mounting option of three local checkout from RO to RW of LOCAL_BUILD_MOUNTS variable because it causes failure to make calico/node LOCAL_BUILD=true. But after successful build and run, I still can't see the updated log messages modified in 'ipip_mgr.go' located in felix/dataplane/linux/.

can anyone give a hint on how to build files from local? And I have a question, what about other imported files like log, do they get imported from the vendor directories or somewhere else?

I am trying to modify log messages in felix dependency (which is in the same directory as node) and make calico/node LOCAL_BUILD=true in node directory. Should I make build for felix as well?

## Expected Behavior
expect to see the updated log message in /var/log/calico/felix/current on my host.

## Current Behavior
not seeing the expected result.

## Possible Solution
looking for one

## Steps to Reproduce (for bugs)
1. copy felix, confd, libaco-go dependencies in vendor directory in node to the same directory as node is in.
2. modify Makefile in node repo (change LOCAL_BUILD_MOUNTS ro to rw to bypass the make failure)
3. make calico/node LOCAL_BUILD=true in node directory
4. docker run with correct options to add my pc to my working cluster with success. Able to ping dockers in the cluster.
5. check /var/log/calico/current and not seeing the updated log message.

## Context
I am trying to modify log messages output first.

## Environment
1. ubuntu16
2. go version 1.11.5 linux/amd64
3. latest calico pulled from official repo.

Thanks!

**Comment by zppznn** [comment]
Anyone please share some thoughts thanks.

**Comment by caseydavenport** [comment]
@zppznn sorry for the long delay.

I noticed similar errors recently and I'm not sure what the cause is yet - haven't had time to dig in. I think it might be related to a different docker version or similar, since not much has changed in the LOCAL_BUILD stuff since it was last working.


I suggest using `glide.yaml` to pin to your personal modified versions of different repositories for now - that should work just fine.

You'll need to set the `repo` and `version` options in the `glide.yaml` file to tell glide to pull in the new version, and then run `glide up -v`

**Comment by zppznn** [comment]
Got it. Thank you so much.
