### ISSUE TITLE
host install manifests outside of tarfile for easier integration with other tools (e.g., kustomize)

### ISSUE THREAD

**Issue by kfox1111** [projectcalico/calico#2587]
Could we please get deployment scripts via kustomize? it is built into kubectl 1.14.0+.

**Comment by caseydavenport** [comment]
I haven't looked at kustomize yet - what would this look like? What are the benefits for Calico users?

**Comment by alwaysastudent** [comment]
Would be great if this can be reopened @caseydavenport.

You don't have to do anything special, but just have to maintain the base opinionated manifests on your repo.

With Kustomize, we can depend on the above mentioned upstream base manifest and can overlay customization in our end without tampering the base manifest that you would ship. This would help us, consumers, to easily maintain.

**Comment by caseydavenport** [comment]
My understanding is that we already maintain base opinionated manifests, like the one that you linked to.

There's nothing stopping you from downloading that manifest into a kustomize directory and applying kustomizations to it yourself. Or am I missing something?

**Comment by mstoetzer** [comment]
@caseydavenport 

At the moment calico offers a tar ball containing all files and k8s manifests.
Updating this tar ball is a bit hard to automate

See the following `kustomization.yaml`:

```
resources:
  - "https://docs.projectcalico.org/archive/v3.20/manifests/calico.yaml"
```

This updates the latest minor version.

It would be nice when the manifest is provided directly with the github release (as attachment) so one can use the release URL as remote resource in kustomization.yaml.

e.g.
```
resources:
  - "https://github.com/calico/calico/releases/download/v3.20.1/calico.yaml"
```

This would it make much easier to automate updates via the kustomization.yaml. What do you think?

**Comment by caseydavenport** [comment]
Seems reasonable that we do something like that. I'll open this to track.

For what it is worth, we're slowly moving away from using `calico.yaml` in favor of the tigera-operator managed deployments, as the operator has a number of benefits over using the raw resources including easier upgrades. Not directly related to this, but in parallel I'd recommend looking into that install method.

**Comment by caseydavenport** [comment]
@mstoetzer actually, is there a reason you can't use https://projectcalico.docs.tigera.org/manifests/calico.yaml?

**Comment by mstoetzer** [comment]
@caseydavenport with the URL to the manifest you provided, no one can be sure, which version of calico will be installed. For example, if I want to pin a specific version of the manifests in a Git Repo (in a kustomization.yaml file).

**Comment by caseydavenport** [comment]
What I would like to do even independent of this is pull the manifests out of the docs altogether and simply host them on GitHub with a single source of truth. I think that would resolve this, since then you could use the github link directly at the specific tag.

There's a bit of work to get there though. Until then, the best option is to continue to use the per-release archive if you need to specify precisely to a specific patch release version. Or, if you're OK with picking up bugfix releases, you can pin to a specific minor release via https://projectcalico.docs.tigera.io/archive/v3.19/manifests/calico.yaml

**Comment by caseydavenport** [comment]
Just merged a fix for this, but officially tagged manifests won't be available until v3.24 (we missed the boat for v3.23 on this one). 

However, if you want to try it out - master versions of the manifests are now available, e.g.: https://raw.githubusercontent.com/projectcalico/calico/master/manifests/tigera-operator.yaml

https://github.com/projectcalico/calico/tree/master/manifests

**Comment by CecileRobertMichon** [comment]
Hi @caseydavenport, we're interested in using this with kustomize for CAPZ (cluster API provider Azure), we currently have to download the release artifacts in order to pin to a specific version of Calico. Can you please confirm it will be available in v3.24.0? I don't see it as part of the v3.24.0-0.dev tag

**Comment by caseydavenport** [comment]
@CecileRobertMichon we haven't yet done any special work for integration with Kustomize. What we have done is make the manifests available at `https://raw.githubusercontent.com` URLs instead of requiring download of a .tar file containing the manifests.

**Comment by caseydavenport** [comment]
Yep, once that tag exists I would expect that URL to work. For now, you can do this for a particular commit - for example https://raw.githubusercontent.com/projectcalico/calico/8144afeb7b86b1c1afc42954f2e9b78226188103/manifests/calico.yaml - but we haven't produced any tags since this change went in.
