### ISSUE TITLE
Canal manifests do not support Jumbo frames

### ISSUE THREAD

**Issue by plnordquist** [projectcalico/calico#2588]
In my deployment I'm using jumbo frames on an interface with an mtu of 9050.  Flannel determines the correct mtu for its interfaces as 9000 but the mtu for interfaces inside of a container does not include the correct mtu and is set to the default of 1500.  I found a solution at https://github.com/kubernetes/kops/pull/6823/files#diff-cb4ad2725d7167b7bcc64358d3f0fabb where they edit the template to include the mtu settings from the Calico manifest into the Canal manifest.  I've done a similar change on my cluster while setting the veth_mtu to 9000 and that fixed this issue.  Can the default manifest include some of these configuration snippets?

**Comment by caseydavenport** [comment]
Yeah, looks like for some reason we only enable these knobs in the pure-Calico manifest: https://docs.projectcalico.org/v3.7/manifests/calico.yaml

Seems reasonable to expose the same configuration for the canal one. 

Probably just a matter of modifying the templates to say "Calico or Flannel" instead of just Calico - for example here: https://github.com/projectcalico/calico/blob/master/_includes/master/manifests/calico-node.yaml#L120-L127

Would be happy to review a PR that fixes this.
