### ISSUE TITLE
Change field `order` in api `NetworkPolicy` from float to interge

### ISSUE THREAD

**Issue by magicsong** [projectcalico/calico#2776]
## Expected Behavior
The field `order` in `networkpolicy` should be interge not float64

## Context

I am developing with calico and introducing some domain-related crds to make my user better working with calico. However in k8s, it doesn't allow me to use float as a field in spec.  
refer to <https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types> 
I have to make it be a interge and convert it to float before using calico api. 

How do you think about using float or interge as the type of field `order`?

**Comment by tmjd** [comment]
I do not think we would want to use an integer because that would be problematic for upgrades.

What you linked to suggested to not use any float, so I don't see why switching from float64 to float would be any better.

Is there actually something that is blocking you from using a float? The NetworkPolicy.projectcalico is being stored as a K8s CRD so I don't believe there is actually anything preventing you from using a float64 other than the guidelines you've linked to.

**Comment by caseydavenport** [comment]
Yes, I agree. We maybe should have used an integer to start with based on those recommendations, but I don't think we can change it now since we can't upgrade a float64 to an int.

**Comment by magicsong** [comment]
@tmjd user can choose etcd or k8s as backend of calico, and we decide to support both of them. So we use a CRD to offer a new layer of abstraction and depending on user's choice, we create a calico CRD or use `clientv3`. However, when we wanted to create new-level api, we found the field type of `order` is not supported in k8s. Right now we just use `integer` because it is convertable from `float64` to an `integer`

**Comment by caseydavenport** [comment]
>  So we use a CRD to offer a new layer of abstraction and depending on user's choice,

The `calicoctl` tool already provides an abstraction on top of the different data store backends. I don't think we can change this field since it would break existing users.
