### ISSUE TITLE
Improvements to calico documentation for network policy

### ISSUE THREAD

**Issue by ekj1711** [projectcalico/calico#2784]
This is an issue to improve documentation so that it allows new onboarding to calico pretty easy to use. 

## Expected Behavior
I installed and configured v3.8.1 of calico on my cluster. It works all fine. Later upon following examples  in https://docs.projectcalico.org/v3.8/security/calico-network-policy, the expected behavior is that I should be able to setup network policy in the latest calico version v3.8.1

## Current Behavior
The example yaml manifests don't work in v3.8.1 where its said using, ```apiVersion: crd.projectcalico.org/v3
kind: NetworkPolicy```
Change it to ```apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy``` to setup the network policy. 

I am not sure which version it does work as the documentation not mention which is the supported calico version for these examples. 

## Possible Solution
- Update the documentation with the relevant changes so that its easy to onboard to calico. 

## Steps to Reproduce (for bugs)
1. setup a network policy 

## Your Environment
* Calico version v3.8.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):v1.15.2
* Operating System and version: ubuntu
* Link to your project (optional):

**Comment by rafaelvanoni** [comment]
@ekj1711 Did you use `kubectl` or `calicoctl` to apply those manifests? It seems like you ran the command with the wrong tool.

**Comment by dahu33** [comment]
I had the same issue as @ekj1711, when using `kubectl` I got:
`error: unable to recognize "calico/my-global-policy.yaml": no matches for kind "GlobalNetworkPolicy" in version "projectcalico.org/v3"`

The reason I had this issue is because the documentation is not very clear on which tool should be used. I also think the documentation should explain what `calicoctl` brings over `kubectl` and if it's a requirement or not. If it's not a requirement, some `kubectl` compatible examples would also be welcome.

**Comment by rafaelvanoni** [comment]
Fixed in https://github.com/projectcalico/calico/pull/2963
