### ISSUE TITLE
Describe how the calico/node image works

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico#280]
I just helped a usesr try to understand this on slack, so a document describing would benefit people e.g. those who want to make changes, or deploy calico as descrete components

Example contents:
1. How it's built (e.g. the Makefile creates some Pyinstaller binaries from Python scripts and other things and pulled in externally, it's all put into a filesystem and copied into the container)
2. How it starts up - e.g. use of runit, rc.local, the startup.env etc...
3. How processes are managed e.g. stopping and starting processes using runit
4. How logs are created/managed

**Comment by djosborne** [comment]
For background, we cover calico/node components and processes are documented in: http://docs.projectcalico.org/master/reference/architecture/index.html

I'm thinking all this information should possibly go in the introduction section.

**Comment by caseydavenport** [comment]
> I'm thinking all this information should possibly go in the introduction section.

Definitely not introduction material - should probably go in reference, or better yet just in a README in the calico_node directory / repository (once we get a final home for it).  

> would benefit people e.g. those who want to make changes

We need to decide what sort of technical material goes into docs.projectcalico.org.  I think it should be user-focused, not developer focused. 

We currently have this doc: http://docs.projectcalico.org/master/reference/architecture/components

I think that one probably needs to go through a content overhaul or just removed from docs.projectcalico.org.

Closing this issue for now because it's very old and I don't think we want it.
