### ISSUE TITLE
What are the usage scenarios of BGP and ipip modes

### ISSUE THREAD

**Issue by NadamHL** [projectcalico/calico#2879]
BGP and ipip mode usage scenario: the BGP mode uses node hosts under the same VLAN, that is, the same network segment; ipip mode is mainly used to solve the problem of cross network segment.

-------------------------
Is my guess correct?

**Comment by tmjd** [comment]
BGP is used to distribute routes, it allows all the hosts in the cluster to know where to reach pods on other hosts. BGP is used across network segments too.

IPIP is used when the underlying networking between hosts would drop traffic that is not destined or originating from a host. There is a cross subnet mode of IPIP where no overlay is used for hosts on in the same subnet and IPIP is used when pod traffic is traversing subnets.

With IPIP, BGP is still used to distribute routes.

I hope this helps.

**Comment by igorcezar** [comment]
I'd like to take the opportunity to ask some questions too:

1. In the case of VXLAN CrossSubnet mode, BIRD/BGP can be disabled (setting backend to vxlan) or just for VXLAN Always mode?
 Because in the beginning I thought it would use BGP to distribute routes under the same subnet and VXLAN for cross subnets, but when I tested it seems that it doesn't need BGP at all to create direct routes for nodes in the same subnet. (uses ETCD for that?)

2. How does VXLAN know how to route to the node IP (to send UDP packet for the right VTEP/Node) if all routes are set to VXLAN interface (internal IP) as next hop?
It gets all routing information from ETCD, like flannel?

**Comment by saamalik** [comment]
These are great questions @igorcezar . Please share if you already found the answers to your questions. Thanks!

**Comment by caseydavenport** [comment]
> In the case of VXLAN CrossSubnet mode, BIRD/BGP can be disabled (setting backend to vxlan) or just for VXLAN Always mode?

Yep, VXLAN CrossSubnet does not required BIRD.

> It gets all routing information from ETCD, like flannel?

Yep, that's correct

**Comment by soulseen** [comment]
> BGP is used to distribute routes, it allows all the hosts in the cluster to know where to reach pods on other hosts. BGP is used across network segments too.
> 
> IPIP is used when the underlying networking between hosts would drop traffic that is not destined or originating from a host. There is a cross subnet mode of IPIP where no overlay is used for hosts on in the same subnet and IPIP is used when pod traffic is traversing subnets.
> 
> With IPIP, BGP is still used to distribute routes.
> 
> I hope this helps.

@tmjd @caseydavenport May I ask why BGP is still used to distribute routes under IPIP instead of getting routing information from ETCD like in VXLAN mode?

**Comment by caseydavenport** [comment]
Mostly because it's a lot of work that hasn't been prioritized super highly, because the current model "just works".

There is this PR in flight that attempts to move to this model: https://github.com/projectcalico/calico/pull/8357
