### ISSUE TITLE
calico-node pods state is Completed

### ISSUE THREAD

**Issue by farrukh90** [projectcalico/calico#2880]
Calico pod is failing where it tries to run a liveness  probe on IGW of the kubernetes cluster instead  of localhost.  Even though liveness probe is set to "localhost" 9099.  "IGW" IGW IP address

## Expected Behavior

Pods should be running as a daemonset
## Steps to Reproduce (for bugs)

```
Events:
Type Reason Age From Message
Normal Scheduled 69s default-scheduler Successfully assigned kube-system/calico-node-zrtxw to ip-100-100-76-193.corp.pri
Normal Pulled 68s kubelet, ip-100-100-76-193.corp.pri Container image "quay.io/calico/cni:v3.4.0" already present on machine
Normal Created 68s kubelet, ip-100-100-76-193.corp.pri Created container install-cni
Normal Started 68s kubelet, ip-100-100-76-193.corp.pri Started container install-cni
Normal Pulled 66s kubelet, ip-100-100-76-193.corp.pri Container image "quay.io/calico/node:v3.4.0" already present on machine
Normal Created 66s kubelet, ip-100-100-76-193.corp.pri Created container calico-node
Normal Started 66s kubelet, ip-100-100-76-193.corp.pri Started container calico-node
Warning Unhealthy 2s (x7 over 62s) kubelet, ip-100-100-76-193.corp.pri Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: dial tcp IGW:9099: connect: connection refused
```

## Your Environment

* Calico version  3.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.14.3
* Operating System and version: Debian
* Link to your project (optional):

**Comment by tmjd** [comment]
Please include logs from calico-node.
That message would not be coming from calico but from the kubelet, I think you should investigate why the kubelet is resolving localhost to 152.141.37.51.
You say expected behavior is pods should be running as daemonset, but did not include a current behavior so I can only assume that you believe they are not running as a daemonset, why do you think they are not?
