### ISSUE TITLE
Intermittent "felix is not ready" messages

### ISSUE THREAD

**Issue by mukgupta** [projectcalico/calico#2960]
I am running calico 3.8.1 in EKS 1.13. The readiness probe calls `/bin/calico-node -felix-ready` every 10 seconds. Readiness probe fails once in every ~5 minutes with message "felix is not ready"
## Expected Behavior

Readiness prove should never fail

## Your Environment

* Calico version: 3.8.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Ubuntu

**Comment by tmjd** [comment]
Please check the logs from calico-node during one of the time periods when it reports "felix is not ready" and see if that gives any indication to why it is not ready.

**Comment by mukgupta** [comment]
@tmjd Thanks for the tip. Default log level was `error`, so i couldn't find anything. Changed it to `info` and could clearly see a CRD permission issue. Fixed it and the error was gone. Thanks

**Comment by tmjd** [comment]
I'm glad you found the issue. Please consider putting up a PR if there is an incorrect manifest somewhere as I think all deployment methods should have the correct CRDs to allow calico-node to run successfully. 
If you are not comfortable putting up a PR could you please include a link to the manifests you used to install Calico?
Thank you for reporting back. I'm going to close this issue since you have fixed the issue you had.
