### ISSUE TITLE
How to configure ib0 in calico

### ISSUE THREAD

**Issue by zlwfrank** [projectcalico/calico#3369]
I tried to follow the Mellanox instruction @ https://github.com/Mellanox/k8s-rdma-sriov-dev-plugin to enable the InfiniBand HCA mode in Kubernetes. As explained in the instruction, "1. Use CNI plugin such as Contiv, Calico, Cluster. Make sure to configure ib0 or appropriate IPoIB netdevice as the parent netdevice for creating overlay/virtual netdevices." Could anyone please tell me how to configure ib0 as the parent netdevice in Calico? I appreciate your help.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by lwr20** [comment]
That sounds like a question for the Mellanox folks - Calico doesn't create or do anything with an ib0 interface as far as I know?

**Comment by zlwfrank** [comment]
So I notice that Calico will create an virtual eth0 for every pod. If I have two interfaces, e.g., eth0 and ib0, on my host, how would the virtual eth0 know which type of traffic will be routed to which interface? Thanks.

**Comment by lwr20** [comment]
Again, a question for the Mellanox folks, I think.  Calico chooses which interface to route down according to the autodetection method specified by env vars.  See https://docs.projectcalico.org/reference/node/configuration#ip-autodetection-methods

Note that Calico generally doesn't work with any networking technology that bypasses the kernel networking stack, since it works by configuring routes and iptables rules.

**Comment by zlwfrank** [comment]
@lwr20 Thanks for the clarification. I will read the doc you send to get a better understanding on the interface selection and I will ask the Mellanox for help.

**Comment by xieydd** [comment]
@zlwfrank Have some solution?
