### ISSUE TITLE
Port bind conflict between Nginx TCP Service and Calico

### ISSUE THREAD

**Issue by thiagosantosleite** [projectcalico/calico#3424]
Summary:
Its quite difficult to reproduce, but there are some situations that port bind conflict happen between Nginx TCP Service(ingress) and Calico. In my env I have some tcp services from 40k to 50k and and nginx bind to this ports after Calico and calico-node bind dynamically to ports from 40k to 65k (I'm not sure but looks like it is the range) so I have errors and ingress never starts:

Calico
```root@ip-172-23-163-50:~# netstat -alpn | grep calico
tcp        0      0 127.0.0.1:9099          0.0.0.0:*               LISTEN      30488/calico-node   
tcp        0      0 172.23.163.50:40005     10.43.0.1:443           ESTABLISHED 30490/calico-node   
tcp        0      0 172.23.163.50:60732     10.43.0.1:443           ESTABLISHED 30488/calico-node   
unix  2      [ ACC ]     STREAM     LISTENING     98894    30628/bird           /var/run/calico/bird.ctl
unix  2      [ ACC ]     STREAM     LISTENING     97463    30629/bird6          /var/run/calico/bird6.ctl
```
Nginx startup
```  0.0.0.0:40005 failed (98: Address already in use) ```

nginx configmap - tcp-services:
```apiVersion: v1
data:
  "40004": xxxxx/xxxx:5044
  "40005": xxxxx/xxxx:5000
  "40007": xxxxx/xxxx:5044
  "40008": xxxxx/xxxx:5044
kind: ConfigMap
metadata:
  annotations:
  name: tcp-services
  namespace: ingress-nginx
```

is there a way to limit the port range for calico-node?

**Comment by tmjd** [comment]
I don't believe calico-node supports limiting the ephemeral ports it uses for source ports specifically.
That can be controlled in general on linux and I believe that would work for calico-node too.
You could try something like https://stackoverflow.com/questions/28573390/how-to-view-and-edit-the-ephemeral-port-range-on-linux

**Comment by thiagosantosleite** [comment]
do you know why there are these 2 established connections? I didnt see it in the network requirements.

https://docs.projectcalico.org/getting-started/kubernetes/requirements

**Comment by tmjd** [comment]
I do not think they are a requirement, they are random ports selected by the kernel.
When a connection is created, usually a random ephemeral port is selected locally for the source and return traffic to use. I am guessing that the source port that the linux kernel selects for the outgoing connection calico is making happens to match what your service is attempting to use.
I'm also guessing the reason it is difficult to reproduce is because it is a random port selected by the linux kernel for the source of the local traffic.

**Comment by caseydavenport** [comment]
I don't think this is a Calico issue, and I'm not even sure what we could do about this.

When Calico starts it needs a source port to initiate outgoing connections. The linux kernel will randomly allocate it one from the available ports.

If your app tries to grab a specific source port for some reason, then it's possible that linux has already handed that out to someone else (it doesn't necessarily need to be Calico). 

You could try making sure that your nginx service is started first somehow, so that linux won't hand a port to Calico before nginx starts?
