### ISSUE TITLE
Pod can't receive to the response outside the cluster after set NATOutgoingAddress to vip

### ISSUE THREAD

**Issue by lyyao09** [projectcalico/calico#3438]
## Expected Behavior
When set vip as `NATOutgoingAddress`, I can get a response after sending a request from the container to outside the kubernetes cluster.

## Current Behavior
As mentioned in [projectcalico/calico#2222](https://github.com/projectcalico/calico/issues/2222), calico support `NATOutgoingAddress` option to use `SNAT` instead of `MASQUERADE` in nat-outgoing chain. When set vip(on the same interface as one of the master IP of the kubernetes cluster) as `NATOutgoingAddress`, I can't get a response after sending a request from the container to outside the kubernetes cluster.

```
master1: ip=192.168.0.1; vip=192.168.0.11
master2: ip=192.168.0.2; podIP=177.177.0.1
master3: ip=192.168.0.3;

node outside the cluster: 192.168.0.4

Enter the container on master2 and execute ping command
ping 192.168.0.4 (no responding cause message stopped after being sent to vip node)
```

## Steps to Reproduce (for bugs)

1. Set `NATOutgoingAddress`=vip
2. Deploy a kubernetes cluster with 3 master(vip in one of the master) and calico v3.8.0
3. Enter any container and send a ping command to outside the kubernetes cluster
4. The ping command cannot receive the response message normally

## Your Environment

* Calico version V3.8.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.15
* Operating System and version: CentOS 7.6
* Link to your project (optional):

**Comment by tmjd** [comment]
I'm not really familiar with the natoutgoingaddress and how to use it but from reading the description of the config option and the #2222 issue you linked I'm going to try to help.
In your setup you say the vip is on master1 but the pod you are sending from is on master 2. Is there something you've setup so that traffic to master1 destined for the pod will be sent to master2? I don't think Calico/felix would configure anything to handle getting that traffic from master1 to master2.
With NatOutgoingAddress I would think you need to specify the address for each host where you need to use NATOutgoingAddress and that address would need to cause traffic to be routed back to that host.
@caseydavenport do you know how NATOutgoingAddress is suppose to work?

**Comment by lyyao09** [comment]
Thanks for your answers.

**Comment by lyyao09** [comment]
>  Is there something you've setup so that traffic to master1 destined for the pod will be sent to master2?

@tmjd Thanks for reply. I have not set anything other than the NATOutgoingAddress param, I think this's why the response traffic does not return from master1 to master2. 

As you say, if Calico/felix would't configure, I‘m not sure if it's appropriate to set it to vip. So... what about the best practice of NATOutgoingAddress param? each node can only configure its own nodeIP?

**Comment by tmjd** [comment]
Yeah I do not think NATOutgoingAddress can help with VIP.
I believe it is useful in situations where your nodes have multiple addresses and you need to specify which address should be used on traffic leaving the host which will be NAT'ed.
