### ISSUE TITLE
JSON Format Error Applying ALP patch

### ISSUE THREAD

**Issue by sherwoodzern** [projectcalico/calico#3468]
Installed Istio 1.4.8 and attempted to do the following according to the Calico documentation:
calicoctl patch FelixConfiguration default --patch \
   '{"spec": {"policySyncPathPrefix": "/var/run/nodeagent"}}'

The command results in the following error message: 
Hit error: permorming strategic merge patch: invalid JSON document

## Expected Behavior

I would expect the patch to be applied to the FelixConfiguration

## Steps to Reproduce (for bugs)

1. Have a Kubernetes cluster running 1.15.7
2. Installed Calico 3.13.2 and Calicoctl 3.13.2
3. Installed Istio 1.4.8 (I had also experienced the same failure with 1.5.1)
4. Execute the command: calicoctl patch FelixConfiguration default --patch \
   '{"spec": {"policySyncPathPrefix": "/var/run/nodeagent"}}'

This results in  the JSON format error

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I just copied / pasted that command exactly and it worked fine for me.

**Comment by waheedi** [comment]
I have also hit this error few times, with newer versions, I would like to understand the root cause honestly, its either the error message is too far from reality or there is something missing.

**Comment by waheedi** [comment]
I think I just found out the root cause, which seems to be related to the user running the patch command.

So in the first scenario:

shell is using root user:

su k8s -c "calicoctl  -l debug  patch felixconfiguration default --patch '{"spec":  {"bpfEnabled": true}}" 
results in the below json error
Hit error: permorming strategic merge patch: invalid JSON document

shell is using k8s user directly:
calicoctl  -l debug  patch felixconfiguration default --patch '{"spec":  {"bpfEnabled": true}}
Successfully patched 1 'FelixConfiguration' resource


So the k8s user which is the one that has the .config files in its home directory had no problem, which seems to be a user permission problem which needs to be caught and displayed correctly IMO.

All my best,
