### ISSUE TITLE
Can't access docs for older releases

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#3475]
## Expected Behavior

Versioned URLs should continue to work.  Releases drop-down links should go to the release I picked.

## Current Behavior

For example:

https://docs.projectcalico.org/v3.8/release-notes/

redirects to

https://docs.projectcalico.org/release-notes/

Also, all the entries in the drop-down menu for releases redirect to the current release.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I think the dropdown links are bad.

We recently moved older versions to the "archive" URL

e.g., https://docs.projectcalico.org/archive/v3.8/release-notes/

This was to fix an issue with search returning _very_ old results, thus leading users astray. We probably just need to update the dropdown to bring users to the archive URLs instead of the non-archive URLs, which are currently re-directed.

**Comment by caseydavenport** [comment]
#3478 has fixed the dropdown links. Thanks for raising this!
