### ISSUE TITLE
Calico and tftp on k8s not working by default

### ISSUE THREAD

**Issue by strus38** [projectcalico/calico#3578]
I have deployed calico 3.10 on a kubernetes cluster from the default configuration.
When I deploy a tftp server, and expose it as a service using metallb 69/udp.
The tftp server works from the pod, but not when using the service: timeout every time.
The expected behavior would be that it works out of the box, since no documentation is warning about tftp case.
Looking on forums and so, someone is pushing to update the natOutgoing parameter to false, but I guess, it comes with side effects, and even, does not seem to work either (except if I did a mistake).
So, could you please explain how to get it working?
Thanks

**Comment by caseydavenport** [comment]
@strus38 any updates on this? I think I will need some more information in order to help, here.

We need to identify why the timeout it occurring / where the packets are going wrong. Could you check to see if the tftp server is available from another pod using its pod IP? or is it only via a service that it goes wrong?

**Comment by strus38** [comment]
Hi
Trying to get my cluster back to the state where I can put more logs!

Le mer. 17 juin 2020 à 19:16, Casey Davenport <notifications@github.com> a
écrit :

**Comment by strus38** [comment]
Ok, I guess I fixed it by loading the tftp conntrack module on the host.
Thanks

Le jeu. 18 juin 2020 à 19:58, Indigo Ping <indigoping4cgmi@gmail.com> a
écrit :
