### ISSUE TITLE
Support for armhf

### ISSUE THREAD

**Issue by winromulus** [projectcalico/calico#3583]
Is there a way to support Calico on `armhf` (not `arm64`)?
It would be great to be able to support a mixed architecture kubernetes cluster that includes `armhf`

## Expected Behavior
Run Calico in a cluster which includes `armhf` nodes.

## Current Behavior
Only `arm64` nodes are supported

## Your Environment
* Calico version 3.14
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.18.3
* Operating System and version: Raspbian on `armhf`

**Comment by klimisa** [comment]
It would be awesome if you start doing builds for `armhf`

**Comment by fasaxc** [comment]
arm64 support was added by the community; I can't see why we wouldn't accept PRs to add armhf too

**Comment by xiaolei0125** [comment]
try to build calico/node for armhf,  but failed,   hope to support armhf

**Comment by aalaesar** [comment]
Hi.
As mentioned [Here](https://github.com/projectcalico/cni-plugin/issues/869#issuecomment-742168053), I have also built calico for 32bits arm, late 2020, and I'm willing to contribute. (finally started refining my changes).
As this issue is stall since summer 2020, following the contributing code, do I need to open a new issue or can we continue on this tread ?

Regards
Aal.

**Comment by lmm** [comment]
So I think what you'll need to do is

Add a new Dockerfile to https://github.com/projectcalico/go-build for armhf. You can see from here https://github.com/projectcalico/go-build/blob/master/Makefile.common#L18 that the file extension for the Dockerfile is used as the GOARCH env var used when buidling a project for a specific arch. https://github.com/projectcalico/cni-plugin/blob/master/Makefile#L90-L100

Then add Dockerfiles for armhf for all the Calico projects that build binaries like cni-plugin, node, felix, etc.

**Comment by aalaesar** [comment]
Thank you @lmm.

Maybe the project should choose the canonical name for this architecture ?  
It has many variants (arm, armv7, armhf, etc) but it can't only have one for all the project's components.  
For now I use 'arm' (because I'm lazy 😄 )

Here a list of PR to follow the arm integration :

- [ ]  [bird](https://github.com/projectcalico/bird/pull/89)
- [ ]  [go-build](https://github.com/projectcalico/go-build/pull/211)

More to come

Regards.

**Comment by frozenprocess** [comment]
I also agree with @aalaesar on closing this issue. https://hub.docker.com/r/calico/node/tags?page=1&ordering=last_updated&name=armv7

@winromulus yes at the moment documentation is not reflecting support for `armhf`. (Sounds like a new contribution if you feel like it )

**Comment by aalaesar** [comment]
@winromulus @frozenprocess
J'ai, probably my Gault as I tagge most of PR 'no Doc/release note required'.  
so probably the CI didn't catch anything for the release note.  
Sorry. :pensive:
