### ISSUE TITLE
Calico blocks IPIP traffic

### ISSUE THREAD

**Issue by liorfranko** [projectcalico/calico#3665]
We use Calico as a policy enforcer of the K8s cluster.
We have nodes in different subnets and the ippool is configured "CrossSubnet"
We have a group of nodes that blocks ingress IPIP traffic with iface tun0. 
The source IP of the blocked traffic is the ipv4IPIPTunnelAddr of nodes located on a different subnet.

## Expected Behavior
Calico should remove the IPIP header first and only then check if the source IP is allowed.

## Current Behavior
It looks like Calico checks if the source IP is allowed before it removes the IPIP header.

## Your Environment

* Calico version - v3.3.2
* Kubernetes: - k8s v1.15.6
* Operating System and version: CentOS 7

**Comment by lwr20** [comment]
Its possible I've misunderstood, but the reason for that rule is to prevent traffic injection into the cluster by sending IPIP packets from a node outside the cluster.  i.e. its absolutely required to prevent a security hole.

The list of IPs of nodes in the cluster should be maintained by a controller in kube-controllers (at least in recent releases).  Note that Calico v3.3.2 is ancient - I recommend that you upgrade to get all the bug fixes that have happened since then.

**Comment by liorfranko** [comment]
I agree on how it should work, for some reason it doesn't.
I'll start with an upgrade and sync if there are still issues after that.

**Comment by liorfranko** [comment]
I upgraded the cluster and I see the same behavior.
I have two nodes located in different subnets, with IPIP tunnels between them.
Traffic is working well without the Calico Policy.

This is the topology design:
![Blank Diagram (1)](https://user-images.githubusercontent.com/20726865/88157512-866da900-cc13-11ea-8685-1de912a92c82.png)

As you can see, the dropped packets are sourced ipv4IPIPTunnelAddr.
If I migrate the pods to be on nodes on the same subnet without iPiP it doesn't get blocked.

**Comment by caseydavenport** [comment]
@liorfranko to clarify, in your diagram, the packet appears to have the following

Inner header:
- Source address is Node1 IPIP tunnel device.
- Dest addresses is a pod on Node 2

Outer header:
- Source address is Node1 primary interface IP
- Destination address is Node2 primary interface IP.

Is that right?

> It looks like Calico checks if the source IP is allowed before it removes the IPIP header.

I believe this is expected, but I would expect the remote node's IP address to be in the "allowed list" of IPIP tunnel source addresses. 

What do the ipsets look like on the receiving node?

**Comment by liorfranko** [comment]
You're right about the inner and outer headers.
What output are you looking to see on the ipsets? can you send me the specific command to run?

**Comment by caseydavenport** [comment]
@liorfranko did you ever get past this?

**Comment by liorfranko** [comment]
No, I didn't, I moved on to something else.

**Comment by ghobadimhd** [comment]
Hi
we have had this issue for a long time and we have to define Global network policies that allow tunnel addresses for every node.
our ingress (Nginx) pods use Hostnetwork and packets forwarded from ingress to our second data center, reached at target pod with tunnel IP address as the source address. 
The problem is the namespace owner does not know tunnel interface addresses and cannot define the correct policy.

**Comment by ghobadimhd** [comment]
This issue coused by this route 
![image](https://user-images.githubusercontent.com/9274387/163676483-a10ee03b-7981-4bdf-a6c4-1ed11ace1e86.png)

is there any way that let us choose the preferred source address for the packets originating from Host?

**Comment by caseydavenport** [comment]
> The problem is the namespace owner does not know tunnel interface addresses and cannot define the correct policy.

@ghobadimhd I'd recommend opening another issue to discuss this further, but you can use automatic host endpoints to avoid needing to spell out IP addresses manually.
