### ISSUE TITLE
Flannel to Calico migration not working 

### ISSUE THREAD

**Issue by ragunathan23** [projectcalico/calico#3706]
## Expected Behavior

Flannel to Calico migration should succeed.
## Current Behavior

The migration controller stopped with the following error:
```
[ERROR][1] ipam_migrator.go 348: Failed to validate existing default IPv4 IP pool (cidr/blocksize/nat/vxlanMode) {CIDR:10.10.0.0/16 VXLANMode:Always IPIPMode:Never NATOutgoing:true Disabled:false BlockSize:26 NodeSelector:all() IPIP:<nil> NATOutgoingV1:false}
[ERROR][1] migration_controller.go 171: Error initialising default ipool and Felix configuration. error=Failed to create default ippool
[FATAL][1] migration_controller.go 138: Migration controller stopped

```
## Steps to Reproduce (for bugs)

1. Install calico controller yaml
2. Install the calico migration job
3.
4.

## Your Environment

* Calico version : v3.15.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.18.1
* Operating System and version: Centos 7
* Link to your project (optional):

**Comment by frozenprocess** [comment]
Have you tried installing canal first then running migration code?
I have not use it with your setup. however, I remember a similar error when I was working with the script.

# Since this is experimental please try this in a lab environment first.
`
1. Install Canal from https://docs.projectcalico.org/getting-started/kubernetes/flannel/flannel
2. Install calico controller yaml
3. Install the calico migration job
`

>  remember to change CIDR in https://docs.projectcalico.org/manifests/canal.yaml @ net-conf.json section

**Comment by song-jiang** [comment]
@ragunathan23 Can you paste logs before `[ERROR] ipam_migrator.go 348: Failed to validate existing default IPv4 IP pool` ? Especially I am looking for this line  https://github.com/projectcalico/kube-controllers/blob/master/pkg/controllers/flannelmigration/ipam_migrator.go#L289
