### ISSUE TITLE
Prevent access to a specific namespace

### ISSUE THREAD

**Issue by akcrisp** [projectcalico/calico#3806]
Hi this is a question rather than an issue. Completely new to calico...(apologies if there's a better forum to post this in)

So we are looking to try and centrally administer some aspects of our kubernetes estate whilst also trying to empower our app teams to own as much as possible.

With this in mind we would like to prevent people being able to access specific namespaces  without having to somehow define (and know in advance) all the other aspects of their application deployment access requirements.  Now from what i can see so far there is a global-deny but then you need to go in and customise the specific access required for everything else(which of course will vary with every application).

Is there a way to say deny: <namespace> as a default, so nothing can access it (unless you then specifically allow specific resources access to it for example on a port). I've looked at rbac and again without having to specify everything it doesn't look possible there - There is a git ticket for people asking for a deny ability - https://github.com/kubernetes/kubernetes/issues/85963

Thanks

Andy

**Comment by caseydavenport** [comment]
@akcrisp simply selecting one or more pods will enact a default deny behavior for those pods, so that you will then need to explicitly define allow rules in order to enable certain matching traffic to access the selected pods.

You can do this cluster-wide using a Calico GlobalNetworkPolicy (https://docs.projectcalico.org/reference/resources/globalnetworkpolicy), or per-namespace using NetworkPolicy. 

You can also, with Calico policies, do explicit deny rules for certain matching traffic, in case you wanted to implement a denylist appraoch rather than an allowlist.
