### ISSUE TITLE
Allow graceful switching from full-mesh to RR peers

### ISSUE THREAD

**Issue by mihalysz22** [projectcalico/calico#3819]
We're experiencing a ~2 seconds network disruption on the whole cluster when trying to switch from a full-mesh setup to a Route Reflector based one, namely when we're turning of the full-mesh in the default BGPConfiguration with nodeToNodeMeshEnabled. This happens because Mesh_ sessions must be teared down before the newly configured Node_ sessions can be established. During this reestablishment Calico routes are lost for a brief period on every Node.

## Current Behavior
In versions prior to Calico 3.13 - i've specifically tested 3.9.6 and 3.12.2 - the workaround of disabling Mesh_ sessions (w/ `birdcl -s ... disable Mesh_`) on non-RR nodes worked fine, because the other end - a RR - had only one session defined, so a non-RR node was able to **initiate** the Node_ session to the RR node.

This [PR](https://github.com/projectcalico/confd/pull/311) has been integrated into 3.13 though, that keeps Mesh_ sessions on RRs as well, while in previous versions Mesh_ sessions has been kept on non-RR nodes only.

Because the BGP standard [https://tools.ietf.org/html/rfc4271#section-6.8](https://tools.ietf.org/html/rfc4271#section-6.8) states:
>In the event of connection collision, one of the connections MUST be closed.

I assume we're running into a corner-cases we shouldn't run into when two sessions (Mesh_ and Node_) are defined between the same IPs on both peers.

## Possible Solution
I understand we might be hitting an unusal Calico use case (switching from full-mesh to RR), but as having multiple sessions defined between the same IPs is somewhat in contrast to the standard, but definitely confusing for both humans and - as far as I can see - to the BGP implementation of BIRD as well, I suggest some preference between which session is configured when by Calico confd.

## Steps to Reproduce (for bugs)
1. Follow: https://www.tigera.io/blog/configuring-route-reflectors-in-calico/
2. Watch for any podsubnet to podsubnet pings when adding `nodeToNodeMeshEnabled: false`

## Your Environment
* Calico version: 3.13.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.18
* Operating System and version:
* Link to your project (optional):

Thank you!

**Comment by mihalysz22** [comment]
I mean something like putting Node_ sessions before the Mesh_ sessions in the BIRD confd templates. This way BIRD will prefer the Node_ sessions over the Mesh_ ones once we disable the latter for a seamless full-mesh->RR migration experience.

https://github.com/mihalysz22/confd/commit/a6f7ff5c2c6db4b3a373a84d731c535a0b315c18

**Comment by caseydavenport** [comment]
In one point of view, Calico is accurately respecting the provided intent - you've given it two peering configs and it is attempting to action both. 

However, I understand that the switch from mesh->RR requires that either:
- You disable full mesh first, thus temporarily withdrawing all routes.
- You enable the RR first, thus hitting this conflict. 

So given that, it seems reasonable to me that if two sessions are defined between the same peers that one of them is preferred, so that we don't end up with multiple simultaneous connection attempts temporarily breaking the peering.

**Comment by coutinhop** [comment]
This was implemented, in a way, by excluding RR nodes from the full node-to-node mesh. That way, it is possible to cordon/provision new nodes so that dataplane traffic is not disrupted. https://github.com/projectcalico/confd/pull/619 has the confd changes and https://github.com/projectcalico/calico/pull/4992 added a description of the steps to the docs.
