### ISSUE TITLE
How to do gitops with calico NetworkPolicy

### ISSUE THREAD

**Issue by fliphess** [projectcalico/calico#3841]
Hi! We're using [fluxcd](https://fluxcd.io/) in our cluster to do all the k8s deployment and configuration from git. 

I want to update our configuration for use with calico network policies, and I prefer to use the calico api versions as the extension on the k8s security policies is very nice to use for larger rule bases. 

How to do this? Flux doesn't know how to deal with calicoctl and having the network policies manually applied on a cluster with 10k of pods sounds very error prone and pretty much like a big pain in the neck. 

I don't want to resort to additional shell scripts, ansible, terraform and other mechanisms that need to be applied straight after our cd pipeline has run as this is an outage waiting to happen and is extremely error prone as it requires manual interaction.  (And besides, using git with fluxcd works very well for everything else in the k8s landscape just not for calico). 

Is there a generic way to do this without having to use calicoctl? Is there any documentation of how to avoid using calicoctl?

**Comment by caseydavenport** [comment]
Hey @fliphess, thanks for raising this!

The ability to use kubectl directly to apply Calico resources is an enhancement request that we're already tracking here: https://github.com/projectcalico/calico/issues/2923

It's something I'd really like to do, but there are some subtleties that we need to work out in order to implement it. Would love if you could chime in on that issue. 

I'm going to close this issue for now so we can keep discussion in one place. Thanks!
