### ISSUE TITLE
calico need to restart RR after added a new node

### ISSUE THREAD

**Issue by zhaixigui** [projectcalico/calico#3915]
This is the problem of the Kube-Router. I wonder if calico also exists?

kube-router issue： https://github.com/cloudnativelabs/kube-router/issues/676

**Comment by mgleung** [comment]
Hi @zhaixigui, that's a good question. From my understanding of that issue, it appears that the issue you are looking to fix is the need to do a soft-restart in order to update the BGP configuration. If that's the case, Calico shouldn't need a restart in order to update it's BGP configuration. Calico monitors some BGP resources and updates the BGP configuration for each node accordingly. You can find some examples of how we work with the BGP configuration in our [docs](https://docs.projectcalico.org/networking/bgp).

That being said, I haven't personally tested this scenario with adding a new node though I would expect it to work without needing a restart. If you find that it doesn't work, let us know and can look into it.
