### ISSUE TITLE
slowness when nmap is executed from pod

### ISSUE THREAD

**Issue by vigneshkaladharan** [projectcalico/calico#3955]
## Expected Behavior
when we run nmap to find open ports from a node or within a pod it should  complete within same amount of time

current Behavior
nmap commands take  more time when we execute it within a pod.

no of packets sent within a pod is less when  compared with node

pods use calico interface.
nodes use eth0 interface.

**Comment by caseydavenport** [comment]
I think this issue needs a bit more information in order to properly triage. 

A few bits of information that might help:

- Could you share a sample of what the nmap commands you're running look like (both from within the pod and from the host)? 
- Are you running nmap against DNS names or known IP addresses? Are they cluster locations or outside the cluster? 
- How are you measuring the time it takes to execute the command? 
- Is it only nmap that is affected, or are other connections from pods slow?
- Do you have any network policies defined in the cluster?

**Comment by fasaxc** [comment]
FWIW, I would expect that to be slower; Calico is policing the traffic that your pod can send, that requires work and nmap generates lots of unusual packets that will all look like new flows.
