### ISSUE TITLE
ipv4 ipip/vxlan mode: no tunl route added if the source ip is different from calico-node ip

### ISSUE THREAD

**Issue by zq-david-wang** [projectcalico/calico#4234]
Two nodes in different subnet, and each node is itself in two different subnets, so totaly 4 subnets: suba1, suba2, subb1 and subb2
nodeA  ipa1/suba1 ipa2/suba2  calico-node ip: ipa1
nodeB  ipb1/subb1 ipb2/subb2  calico-node ip: ipb2

when nodeA try to connect ipb1, it would use source ip ipa1
when nodeA try to connect ipb2, it would use source ip ipa2

Each calico-node is setup using ipip/vxlan mode for ipv4, hence ipv4 bgp has no use under this configuration.
But brid module refuse to create tunl route for ipip/valan mode.

I think the problem is that for nodeB, it receive a bgp package with ipa2 as it source ip address and  ipa1 as the real configuration.

   

## Expected Behavior

In ipip/vxlan mode, bird should not prevent tunl routing even if it detects some inconsistency.

## Current Behavior

No tunl routing created, and pod-pod communication failed

## Possible Solution

Bird module should ignore some error or just do nothing when ipv4 is in ipip/vxlan mode, but it should still function for ipv6

## Steps to Reproduce (for bugs)

As mentioned above
1.
2.
3.
4.

## Your Environment

* Calico version
release-v3.16
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes
* Operating System and version:
centos7
* Link to your project (optional):

**Comment by mgleung** [comment]
Hi @zq-david-wang , would you be able to post some logs for this? I want to try to verify if BIRD is our issue or if our vxlan implementation is.

**Comment by zq-david-wang** [comment]
https://gist.github.com/zq-david-wang/90ebf63daafe9a1e5b5b3000e8f4e4c6
@mgleung  
The logs were captured via "docker logs [calico-node] | grep -v kube-system" 
and at the end , the output of "calicoctl node status" is pasted

**Comment by caseydavenport** [comment]
@mgleung

**Comment by caseydavenport** [comment]
@zq-david-wang I'm re-reading this now and IIUC, I think what you're trying to do won't work.

> Each calico-node is setup using ipip/vxlan mode for ipv4, hence ipv4 bgp has no use under this configuration.
But brid module refuse to create tunl route for ipip/valan mode.

Are you using IPIP or VXLAN encapsulation? They are both implemented differently and so the distinction is important. VXLAN doesn't rely on BIRD programming routing, whereas IPIP routing is implemented within BIRD and so _needs_ BGP to be turned on.

I think, based on what I can see, you're trying to use IPv4 in IPIP mode without BGP but IPv6 unencapsulated using BGP?

If so, that's not a possible scenario at the moment, since IPIP is itself programmed by BIRD based on routes learned over BGP. I think you will need to do the following:
- Switch your IPv4 pool to use VXLAN, since VXLAN is not implemented via BIRD today.
- Disabled BGP for IPv4 by turning off IPv4 address auto-detection. with `IP=None`

**Comment by zq-david-wang** [comment]
@caseydavenport  yes, I use IPIP mode for IPV4.
 Thanks for the suggestions.
