### ISSUE TITLE
calico-felix container config not documented

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#446]
calico-node configuration is documented here: http://docs.projectcalico.org/v2.0/reference/node/configuration

WIBNI calico-felix had a similar document?

**Comment by lwr20** [comment]
@shaun points out that there's this: http://docs.projectcalico.org/v2.0/usage/configuration/  

But it isn't clear about how to calico/felix (either mount in a config file or pass environment vars).  

And its hard to find :)

**Comment by caseydavenport** [comment]
I think the unspoken plan is that the usage/configuration guide gets moved into the reference section so that the reference section has clearly marked areas for each component and how to configure it.

e.g you can see sections for calico/node, calicoctl, CNI plugins, policy controller there today.  There should (probably) also be a section for Felix, BIRD, etc (and we probably should clearly mark that these are components within calico/node and the interactions at a config level)

**Comment by caseydavenport** [comment]
There is now a felix configuration reference.
