### ISSUE TITLE
Running multiple instances of external calico/node on a host pointing to two different Kubernetes cluster

### ISSUE THREAD

**Issue by pankajagarwal** [projectcalico/calico#4615]
calico/node has a hard configured interface tunl0 which is causing conflict in a situation where we are deploying two container's on a host pointing to two different Kubernetes cluster.

by watching ifconfig -a it show's the IP get's switched from the two different cluster cidr range.

## Expected Behavior
there should be two different unique interfaces like tunl0 or tunl1 if tunl0 is already in use.

## Current Behavior
both the container's are updating tunl0 interface on the host.

## Possible Solution
Not seeing a variable i can pass to dynamically separate the interface name. Possibly we can define/update the bird config template to make it work.

## Steps to Reproduce (for bugs)
1. Have 2 Kubernetes cluster with non-overlapping CIDR range
2. deploy two external calico node container's on a single host pointing to two different Kubernetes cluster.
3. Watch ifconfig -a or netstat -r to see routes and interface fighting to control the interface named tunl0

## Context
I am trying to make it work in my existing environment.

## Your Environment

* Calico version : 3.8.9
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.18.3
* Operating System and version: Centos
* Link to your project (optional):

**Comment by lmm** [comment]
Hi @pankajagarwal, running two calico-node's on the same host is not something we test -- I'm not sure it will work actually.

Not related to your question but v3.8.9 is super old - I'd recommend using a newer Calico version since there will have been many bugfixes since.

**Comment by lmm** [comment]
Ahh, I found your Slack thread 🙂 https://calicousers.slack.com/archives/CPEPF833L/p1621520096035500

**Comment by caseydavenport** [comment]
Yeah, running two calico/node instances on a single host is definitely not something we design for.

From the slack thread, it sounds like you want to have connectivity from a single node to two different clusters - that is certainly possible to do, but I don't think running two calico/nodes is the way to do it.

I would recommend looking into Kubernetes services as a means of exposing access to the node, rather than to pods directly. You can also look at using a single BGP instance on your external node that is peered to both of your clusters, rather than two BGP instances each peered to a single cluster.
