### ISSUE TITLE
Should OUTPUT chain link to felix-TO-ENDPOINT?

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#467]
I think we only add rules to the INPUT and FORWARD chains right now.  That leaves the compute node able to ping/access the workloads that it hosts.  Obviously, the compute node is privileged but I'm wondering if it will create some uncertainty, "why can I access the VM from this node but not that one?".

**Comment by fasaxc** [comment]
Assigning to Cory for opinion/history behind any previous design decisions here.

**Comment by Lukasa** [comment]
So, this has been a known wart for a long time. It originally happened because we were piggybacking on OpenStack's rule setup, which doesn't set up filter rules in the OUTPUT chain (because why would it?). We then left it in place, mostly because it provides a really useful debugging aid.

If we did this, we'd have a minor security increase: programs running without CAP_NET_ADMIN would be unable to reach VMs hosted on the machine. That's probably a good thing, and I suspect it's good enough to justify adding the function.

It's worth noting that it does not provide any truly hard form of security, because obviously anyone who gets root on the box can do whatever the hell they please.

**Comment by fasaxc** [comment]
Probably reduces our attack surface a bit.  Closes off attacks where the attacker somehow tricks the host to send data to a VM (without actually taking control of the host, for example).  Nothing specific that I'm aware of but probably has some value.

**Comment by plwhite** [comment]
It's very useful to be able to access the VM from the host. Feels to me like not worth doing, but equally I'm not strongly opposed.

**Comment by lxpollitt** [comment]
+0.5 for @plwhite's point of view, but I don't have a strongly informed opinion - hence +0.5 rather than anything else.  :-)

**Comment by fasaxc** [comment]
Talked this over with the customer I visited yesterday.  I think they were +2 for allowing hypervisor to access VMs.  Usefulness trumps nebulous (and speculative) security benefit for them.

Something we might want to mention in our docs to dispel any FUD though?

**Comment by matthewdupre** [comment]
Agreed, I think this is useful too.  Changing this to a documentation issue.

**Comment by Lukasa** [comment]
This is no longer an enhancement, it's a docs change.

**Comment by fasaxc** [comment]
We now have a Securing Calico doc, which explains how we use iptables.
