### ISSUE TITLE
NodeLocal DNS with Calico/BPF

### ISSUE THREAD

**Issue by lluczaj** [projectcalico/calico#4689]
We have an EKS cluster with Calico/BPF enabled (no Kube-proxy). Before BPF we used to run NodeLocal DNSCache in our clusters and it worked fine:

https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

However, we have issues running it in a cluster with Calico/BPF mode enabled. Traffic is not forwarded to node-local-dns at all in this case. In docs there is only Kube-proxy/IPVS mode described. Cilium guys provide a solution with LocalRedirectPolicy in their docs for BPF mode but I haven't found anything for Calico. Is there any suggested solution for this for Calico BPF ?

## Your Environment

* Calico version: 3.19.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.20 / EKS
* Operating System and version: Amazon Linux 2 (5.4.117-58.216.amzn2.x86_64)

**Comment by song-jiang** [comment]
@fasaxc Could you help?

**Comment by fasaxc** [comment]
No workaround known right now. node-local DNS uses iptables hacks to bypass kube-proxy.  However, BPF bypasses iptables so we partially bypass the node-local DNS hacks too.

**Comment by lluczaj** [comment]
Thanks for your answer @song-jiang @fasaxc 
We are thinking about workaround with injecting node-local DNS local IP directly in Kubelet's config so it populates it in resolv.conf files for pods. This way they will communicate directly with node-local DNS without any iptables hacks. Is there any potential issue with this approach from Calico-BPF perspective ?

One thing that we noticed is that tigera-operator cannot communicate with EKS cluster-endpoint in BPF mode when we inject node-local DNS ip into Kubelet and node-local DNS is not yet deployed (timeouts). Then when it is deployed into cluster tigera-operator starts to work fine but cluster DNS overall is not yet working properly as there are no calico-node pods and CoreDNS is still in Pending state therefore cannot handle any requests. So why does it matter ?

**Comment by fasaxc** [comment]
> We are thinking about workaround with injecting node-local DNS local IP directly in Kubelet's config so it populates it in resolv.conf files for pods. This way they will communicate directly with node-local DNS without any iptables hacks. Is there any potential issue with this approach from Calico-BPF perspective ?

If you can get it to talk directly to the host on one of the host's IPs then I'd expect that to work.

**Comment by zbkannan** [comment]
We have to remove the calico and use AWS CNI to fix this issue.

**Comment by sfudeus** [comment]
I just stumbled over this one as well after having enabled eBPF in our setup. I'll try the suggestion with the host-ips, but the good thing rewriting the "original" cluster DNS IP was a transparent failover if the local pod wasn't there for some reason. 
I suggest to mention this on at least https://docs.tigera.io/calico/latest/operations/ebpf/enabling-ebpf#not-supported. 
Maybe as well here: https://docs.tigera.io/calico-enterprise/latest/networking/configuring/node-local-dns-cache

**Comment by sfudeus** [comment]
My first attempt to work round this was to deploy a node-local cache (equivalent coredns config as the "official" node-local cache) as a DaemonSet and use a dedicated clusterIP and `internalTrafficPolicy: Local` to stay on the optimal routing. But seemingly this didn't work properly (and would have been suboptimal, since a missing pod on a node would have broken DNS resolution for all pods on the node). I just found out about https://github.com/projectcalico/calico/issues/8255 in this context. 

Then I went back to using the hostIP:
Running the cache as a DaemonSet (not even in hostNetwork), just using `hostPort: 53` and tuning the KubeletConfiguration to add $hostIP to the resolv.conf, and keep the ClusterIP for cluster DNS as a secondary DNS works fine. 
Downside is: The fallback to the central cluster DNS when the local cache fails is only with a client-observable timeout - but at least there is a fallback. 
Mind to adapt your network policies if traffic to hostIPs from pods is restricted.

**Comment by tomastigera** [comment]
I think we can make this work. Yes, there is a fair amount of hackery in the node-local-dns, but all we essentially need is to tell our kube-proxy that a certain clusterIP (service) is special and we should not resolve it. What node-local-dns does it creates dummy ifaces to route the dns clusterIP and some other local IPs to the local host. But this all happens before kube-proxy rules in iptables are hit. In contrary, our ebpf programs are hit first so we resolve the clusterIP to a backend and even if we hit the iptables (which we mostly do not hit), it would not match in the backend pod IP.

And we would also need not to track these connections as the rules set by the dns cache apply only to Linux conntrack and not to our conntrack :weary:
