### ISSUE TITLE
[tigera-operator] calico-typha pods preventing cluster-autoscaler from removing nodes

### ISSUE THREAD

**Issue by pjajootibco** [projectcalico/calico#4695]
[tigera-operator] calico-typha pods preventing CA to scale-down the underutilized node

## Expected Behavior
We are using v1.13.2 of tigera-operator in AWS EKS, which creates a calico-typha deployment and typha-autoscaler creates a replica per node. But this is preventing our ClusterAutoscaler to scale down an underutilized or empty node. Is there way we can tell tigera-operator to create "daemonset" instead of a deployment for calico-typha or is there way to reduce the number of replicas of calico-typha pods, as I presume there is no need to have 1 replica per node.

## Current Behavior
Same as explained in the summary above.

## Possible Solution
Asking for suggestions as explained in the summary above

We are using the yaml files from here - https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-operator.yaml and https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-crs.yaml

i.e. AWS Documentation - https://docs.amazonaws.cn/en_us/eks/latest/userguide/calico.html

**Comment by tmjd** [comment]
The autoscaling done for typha does not deploy one per node, for the version that you're deploying see https://github.com/tigera/operator/blob/v1.13.2/pkg/controller/installation/typha_autoscaler.go#L89 for the scaling. For the operator version you're using, you will see one typha for each node up to 4, above 4 you will not see any additional typhas until you get to above 250 nodes. Newer versions of the operator deploy one typha for each node up to 3 and then the 4th isn't added until 200 nodes are reached.

So I'm assuming you are trying to scale to less the 4 nodes, how small are you wanting to scale?
Is there a way to tell the ClusterAutoscaler to ignore typha pods? The operator should scale down the number of typha pods if the ClusterAutoscaler removed a node, though it might not be immediate.

**Comment by pjajootibco** [comment]
Okay that's good to know, I tried scaling upto 4 nodes only. So as per your comment, looks like I won't see any more typha pods until 250 nodes after 4.

Currently cluster-autoscaler says following -

> I0622 17:32:55.525875       1 cluster.go:192] Fast evaluation: node <aws node name> is not suitable for removal: failed to find place for calico-system/calico-typha-8f4bfd7fb-95kzb

And because of this, even though the node is underutilized, cluster-autoscaler is not able to evict the pod and hence cluster-autoscaler cannot scale down the node.

**Comment by syan-tibco** [comment]
@tmjd Try to think in this case; we use big EC2 machine. Our workload is dynamically created. (like FaaS) So ideally we have 1 node always running and hope to dynamically scale up the node when needed and scale back to 1 node when not needed.

The real number in our case that I saw is around 30 pods fit in one node. And we are using multiple EKS in dev environment. (10 ~ 40 EKS clusters and use similar pattern)

 It is not good to always keep 3 extra nodes running for all these EKS clusters.

**Comment by tmjd** [comment]
@syan-tibco I understand the desire. That's why I was asking if there was any configuration possible with the Cluster Autoscaler to ignore typha. There isn't much we can do without reducing the production readiness of the installation since the operator does not know the intentions of the Cluster Autoscaler to scale down the nodes.
I've created this issue https://github.com/kubernetes/autoscaler/issues/4177 on the Cluster Autoscaler. They already ignore daemonsets for scaling down so I requested the ability to configure the ability to ignore specific deployments.

**Comment by frjonsen** [comment]
We are facing this issue as well.

We have a very small number of constant nodes: just one or two that are constantly running. However we run GPU workloads, and use cluster-autoscaler to to scale these nodes, all the one down to 0 when we have no work to run. Normally we prevent non-workload pods from being scheduled on these nodes by using taints, but it appears the Helm chart for the operator is [set up to tolerate *any* taints](https://github.com/projectcalico/calico/blob/c11bccc08f9b6c98c6dfc1142db2ff2082450a74/_includes/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml#L21)? Please correct me if I'm wrong here, I haven't used taints much.

This is effectively preventing CA from shutting down these GPU nodes, and inducing quite a bit of unnecessary cost for us in AWS, since the GPU nodes are just running idle at night and weekends.

To clarify: Our main problem is really the tolerations. The GPU nodes we spin up are temporary nodes to run a specific workload. We don't really want Calico to be getting scheduled on them in the first place, but it wouldn't really be a major issue if that wasn't also causing the scaledown to fail. My understanding from the previous comments on this issue is that it can't really be helped from this side that CA doesn't understand that it's fine to evict Calico even though the pod cannot be rescheduled, but it *should* be possible to allow the user of the tigera operator chart to tweak the tolerations to ensure Calico isn't getting scheduled there.

**Comment by caseydavenport** [comment]
Would using the TyphaAffinity option solve this for you guys? https://github.com/tigera/operator/blob/master/api/v1/installation_types.go#L149

You can specify a RequiredDuringScheduling affinity to ensure that typha pods aren't scheduled to your GPU nodes. The only thing you'd need to do is make sure that there are enough suitable nodes for typha to run on.

**Comment by syan-tibco** [comment]
Hi, @caseydavenport our issue is a little bit different from @frjonsen's issue. We don't have GPU node and we only want the cluster to be able to scale back to 1 node.

**Comment by caseydavenport** [comment]
@syan-tibco I think the node affinity configuration should still work for your case though - you can use a node affinity to ensure the Typha instance always lands on a certain node, and the scheduler will prevent scheduling to anything that doesn't match the affinity. Let me know if I'm misunderstanding!

**Comment by karlyan** [comment]
@caseydavenport thanks for thinking about this. I kind of understand what you mean but that will require we create another nodeset (ASG) to run calico for this issue. This can be done but this is not ideal solution. When we have load we will create 10+ nodes; in such case I still want calico to scale to 2 or 3 to provide better scalability and fault-tolerant for the whole cluster. this will be very complex to coordinate different node groups to do this.

**Comment by prashilgupta** [comment]
@caseydavenport We have a similar issue blocking upgrade of managed node group as typha cant be evicted. Any solution you suggest?

**Comment by frjonsen** [comment]
> The only thing you'd need to do is make sure that there are enough suitable nodes for typha to run on.

If I'm understanding things correctly, "enough suitable nodes" means 3, right? If so, that's not really something we can do. We generally only have one or two nodes running our orchestrator and a few auxiliary deployments, which are enough to handle dozens of worker nodes, of which we generally have none running during the night and weekends.

Not being able to scale down to 1 node was really a dealbreaker for us, and we've unfortunately already migrated to Cilium, which does not have this restriction.

**Comment by tmjd** [comment]
Running Typha as a daemonset would not make sense, Typha is meant to ensure that on large clusters the Kubernetes API server isn't overwhelmed by calico-node connections and watches. So there are just a few/handful of typhas connecting to the Kubernetes API server and then calico-node connects to Typha, so running it as a daemonset would defeat its purpose.

**Comment by caseydavenport** [comment]
> Is there presently a workaround to this

I believe the only workaround at the moment is to use the TyphaAffinity option to ensure typha pods are only scheduled to a pre-determined node / set of nodes, thus forcing the Typha pods not to land on nodes that might be auto-scaled away.

We're still thinking through what the right solution for this is long term though.

**Comment by tmjd** [comment]
We're expecting to discuss issues around scaling and Typha next week (Sept 8th, 2021) in the Calico community meeting if anyone here wants to join to be part of that discussion feel free to join. You can find the details to join here https://github.com/projectcalico/community

**Comment by caseydavenport** [comment]
I think one thing we want to try here is to reduce the number of Typhas deployed for smaller clusters. 

This would mean there is always at least one other node available for Typha to be rescheduled onto, and should prevent this deadlock situation that we're seeing now.

The only bit I'm not sure about is the edge case of scaling from 1 -> 0 nodes. I need to test that case.

**Comment by caseydavenport** [comment]
One update - we merged a PR that allows the `ControlPlaneTolerations` field to be applied to Typha pods, which seems like it should have been from the get-go: https://github.com/tigera/operator/pull/1507

Hopefully that helps some of the use-cases here. We're also looking at adjusting how scaling is done to address the other half here: https://github.com/tigera/operator/pull/1506/

**Comment by maslowskimarcin** [comment]
Hi, Is there any information on when this PR might be merged?

**Comment by caseydavenport** [comment]
Just merged https://github.com/tigera/operator/pull/1506 - will cherry pick this so it is in v3.21 from the start. Thanks for your patience.
