### ISSUE TITLE
Set pod affinity for calico-node deployed using tigera operator

### ISSUE THREAD

**Issue by alfianabdi** [projectcalico/calico#4731]
When installing the calico using tigera operator, the calico-node daemonset only have nodeSelector ( kubernetes.io/os=linux ), there is no option to add affinity, for example when we need to exclude fargate nodes when running on AWS EKS. 
https://docs.projectcalico.org/reference/installation/api#operator.tigera.io/v1.InstallationSpec

## Expected Behavior

There is option to add affinity when deploying calico using tigera-operator

## Your Environment
Tigera-operator: v3.19

**Comment by mgleung** [comment]
Hi @alfianabdi , if I'm understanding correctly, you're looking for a way to prevent the `calico-node` daemonset from running on specific nodes (fargate nodes in your use case)? We generally provide the `controlPlaneNodeSelector` option in the Installation which should allow you to select the proper nodes for the other pods except for the daemonsets (which sounds like it doesn't quite fit your use case. 

I'm not super familiar with running clusters with fargate nodes but the `calico-node` daemonset generally needs to be running on each node to enforce policy so if it is not running on the fargate nodes, then you'll have to be careful about how you craft network policy to reach those pods. What happens if the `calico-node` pods attempt to run on a fargate node? Do they cause any issues or is there another reason you would like to keep them off of those nodes?

**Comment by alfianabdi** [comment]
Hi @mgleung 

It is impossible to run the calico-node in fargate, it is a special microvm node, where only one pods can run inside the node. Without the affinity, I will see many pending calico-node pods, as many as the number of fargate nodes. 

https://docs.aws.amazon.com/eks/latest/userguide/calico.html
Without tigera-operator, I can set the affinity, but I would like if tigera-operator support it as well.

**Comment by caseydavenport** [comment]
Looks like we already have built-in logic for a very similar scenario on AKS: https://github.com/tigera/operator/blob/caac83c79646a11ea94a0f2efff388f0b22bf989/pkg/render/node.go#L663-L678

We could automatically add this when running on EKS pretty easily I think.

It seems inevitable as well that we'll need to expose general controls for node affinity for calico/node, although we originally tried to avoid this because it introduces a potential avenue to break your cluster via misconfiguration. CC @tmjd

**Comment by balous** [comment]
I also look for this feature but my use case is different. We use custom installation of calico and CNI plugins. `calico-node` runs as systemd service, CNI plugins are installed as debian package, and kubelet is directed to load them from non-default path.

We'd like to migrate this setup to tigera operator. We're looking for a way how to configure the new setup and than switch nodes one by one. I think that, when we'll be able to configure the daemonset's affinity to some node label, we could proceed in following steps (for each node):

1) drain the node
2) reconfigure kubelet and stop calico-node systemd service
3) relabel the node and let the deamonset's pod inside
4) uncordon the node

I believe having this feature would enable us to convert to tigera operator without cluster outage.

**Comment by niranjan94** [comment]
@mgleung I have raised a PR to resolve this in the operator by adding proper affinity - https://github.com/tigera/operator/pull/1725
