### ISSUE TITLE
Calico Node v3.19.1 vulnerabilities

### ISSUE THREAD

**Issue by mateiStanescu** [projectcalico/calico#4798]
As part of our patching process we would like to upgrade Calico components, but our security tool Aqua found the following vulnerabilities for the Calico Node.
 
Could you please help us with more info regarding those vulnerabilities (can we discard them, are they exploitable, will they be fixed in future versions)?
This would help us in acknowledging those vulnerabilities so we can progress further.
 
Please see below the vulnerabilities that we have in Aqua – regarding Calico Node v3.19.1:

Critical:

1. ** DISPUTED ** GNU Libc current is affected by: Mitigation bypass. The impact is: Attacker may bypass stack guard protection. The component is: nptl. The attack vector is: Exploit stack buffer overflow vulnerability and use this bypass vulnerability to bypass stack guard. NOTE: Upstream comments indicate "this is being treated as a non-security bug and no real threat."
 
2. The mq_notify function in the GNU C Library (aka glibc) versions 2.32 and 2.33 has a use-after-free. It may use the notification thread attributes object (passed through its struct sigevent parameter) after it has been freed by the caller, leading to a denial of service (application crash) or possibly unspecified other impact. 

3. In the GNU C Library (aka glibc or libc6) through 2.29, proceed_next_node in posix/regexec.c has a heap-based buffer over-read via an attempted case-insensitive regular-expression match.

High:

1. In the GNU C Library (aka glibc or libc6) through 2.28, attempting to resolve a crafted hostname via getaddrinfo() leads to the allocation of a socket descriptor that is not closed. This is related to the if_nametoindex() function.

2. In the GNU C Library (aka glibc or libc6) through 2.29, check_dst_limits_calc_pos_1 in posix/regexec.c has Uncontrolled Recursion, as demonstrated by '(\227|)(\\1\\1|t1|\\\2537)+' in grep.

3. The string component in the GNU C Library (aka glibc or libc6) through 2.28, when running on the x32 architecture, incorrectly attempts to use a 64-bit register for size_t in assembly codes, which can lead to a segmentation fault or possibly unspecified other impact, as demonstrated by a crash in __memmove_avx_unaligned_erms in sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S during a memcpy. 

4. ** DISPUTED ** In the GNU C Library (aka glibc or libc6) through 2.29, check_dst_limits_calc_pos_1 in posix/regexec.c has Uncontrolled Recursion, as demonstrated by '(|)(\\1\\1)*' in grep, a different issue than CVE-2018-20796. NOTE: the software maintainer disputes that this is a vulnerability because the behavior occurs only with a crafted pattern. 

5. An exploitable signed comparison vulnerability exists in the ARMv7 memcpy() implementation of GNU glibc 2.30.9000. Calling memcpy() (on ARMv7 targets that utilize the GNU glibc implementation) with a negative value for the 'num' parameter results in a signed comparison vulnerability. If an attacker underflows the 'num' parameter to memcpy(), this vulnerability could lead to undefined behavior such as writing to out-of-bounds memory and potentially remote code execution. Furthermore, this memcpy() implementation allows for program execution to continue in scenarios where a segmentation fault or crash should have occurred. The dangers occur in that subsequent execution and iterations of this code will be executed with this corrupted data. 

6. The iconv function in the GNU C Library (aka glibc or libc6) 2.32 and earlier, when processing invalid input sequences in the ISO-2022-JP-3 encoding, fails an assertion in the code path and aborts the program, potentially resulting in a denial of service.

Thank you,
Matei

**Comment by mgleung** [comment]
I think @manojah99 might be able to give you some of the info regarding these vulnerabilities.

**Comment by manojah99** [comment]
@mgleung one of the issue with above findings is that the CVE information is missing though descriptions did a good job to point out involved components.
CVE information helps us identify issues and false positives from the tools such as mentioned above.

Though I will check on my end and update you about the path forward, thanks !

**Comment by mateiStanescu** [comment]
Hi,

Attaching additional CVE info for the above vulnerabilities:

Critical:

1. CVE-2019-1010022,  based on https://nvd.nist.gov/vuln/detail/CVE-2019-1010022, Installed Resource glibc 2.28-151.el8
2. CVE-2021-33574, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-33574, Installed Resource glibc 2.28
3. CVE-2019-9169, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9169, Installed Resource glibc 2.28
4. (new one) CVE-2021-35942, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-35942

High:

1. CVE-2018-19591, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-19591, Installed Resource glibc 2.28
2. CVE-2018-20796, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-20796, Installed Resource glibc 2.28
3. CVE-2019-6488, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-6488, Installed Resource glibc 2.28
4. CVE-2019-9192, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9192, Installed Resource glibc 2.28
5. CVE-2020-6096, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-6096, Installed Resource glibc 2.28
6. CVE-2021-3326, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-3326, Installed Resource glibc 2.28
7. (new one): CVE-2020-1751, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-1751, Installed Resource glibc 2.28
8. (new one): CVE-2020-1752, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-1752, Installed Resource glibc 2.28

Low (but high vulnerability score, >7.5)
1.  CVE-2019-20838, based on https://access.redhat.com/security/cve/CVE-2019-20838, Installed Resourcepcre 8.42-4.el8
2. RHSA-2020:4547, based on https://access.redhat.com/security/cve/CVE-2019-15165, Installed Resource libpcap 14:1.9.0-3.el8

Let me know if i can help with further info about the vulnerabilities our tool is reporting.

**Comment by manojah99** [comment]
Thanks @mateiStanescu, this will help us a lot !

**Comment by mateiStanescu** [comment]
Hi,

We have scanned v3.19.3, and unfortunately  it seems that the above vulnerabilities are still there.

Best Regards,
Matei

**Comment by lmm** [comment]
@mateiStanescu sorry for the delay, were the scan results the same as what you originally posted?

**Comment by mateiStanescu** [comment]
Yes, with minor differences but all the vulnerabilities are still present.

**Comment by lwr20** [comment]
@gpang-tigera Can you comment on this issue please?

**Comment by gpang-tigera** [comment]
Hi, below is our analysis of the vulnerabilities reported:

CVE-2019-1010022, based on https://nvd.nist.gov/vuln/detail/CVE-2019-1010022, Installed Resource glibc 2.28-151.el8
- node is not affected by this vulnerability

CVE-2021-33574, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-33574, Installed Resource glibc 2.28
- node is not affected by this vulnerability

CVE-2019-9169, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9169, Installed Resource glibc 2.28
- node is not affected by this vulnerability

(new one) CVE-2021-35942, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-35942
- node is not affected by this vulnerability

CVE-2018-19591, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-19591, Installed Resource glibc 2.28
- node is not affected by this vulnerability

CVE-2018-20796, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-20796, Installed Resource glibc 2.28
- node is not affected by this vulnerability

CVE-2019-6488, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-6488, Installed Resource glibc 2.28
- node is not affected by this vulnerability

CVE-2019-9192, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9192, Installed Resource glibc 2.28
- node is not affected by this vulnerability

CVE-2020-6096, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-6096, Installed Resource glibc 2.28
- node is not affected by this vulnerability

CVE-2021-3326, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-3326, Installed Resource glibc 2.28
- node is not affected by this vulnerability

(new one): CVE-2020-1751, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-1751, Installed Resource glibc 2.28
- node is not affected by this vulnerability

(new one): CVE-2020-1752, based on https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-1752, Installed Resource glibc 2.28
- node is not affected by this vulnerability

CVE-2019-20838, based on https://access.redhat.com/security/cve/CVE-2019-20838, Installed Resourcepcre 8.42-4.el8
- local vulnerability

RHSA-2020:4547, based on https://access.redhat.com/security/cve/CVE-2019-15165, Installed Resource libpcap 14:1.9.0-3.el8
- node is not affected by this vulnerability

Since we do not believe any of these vulnerabilities affects node, we currently do not have plans to provide a patch release. We will however, look into addressing the false positives and updating the packages (where possible) for our next release.

Please let me know if you have any questions.

**Comment by GabrielaTepor** [comment]
Hello, thank you for all you answers and help on this topic.
I am in the same team as @mateiStanescu. Today we scanned again the calico image v3.19.1 and we found another vulnerability that is new. 
Please see it below: 

**CVE-2021-38604
metrodigital.azurecr.io/calico/node:v3.19.0 (Ad Hoc Scans)** ->In librt in the GNU C Library (aka glibc) through 2.34, sysdeps/unix/sysv/linux/mq_notify.c mishandles certain NOTIFY_REMOVED data, leading to a NULL pointer dereference. NOTE: this vulnerability was introduced as a side effect of the CVE-2021-33574 fix. 

Can you please confirm/advice us if this vulnerability is not affecting any node or the optimal functionality of the application. 

Thanks a lot, 
Gabriela

**Comment by gpang-tigera** [comment]
Hey Gabriela,

For CVE-2021-38604, we believe node is not affected by this vulnerability.

**Comment by GabrielaTepor** [comment]
Hello @gpang-tigera, 

Thanks a lot for your quick reply.

**Comment by GabrielaTepor** [comment]
Hi @gpang-tigera @lwr20 , 

Opening this topic again as due to scanning again the image with our tool (Aqua), 2 new vulnerabilities have now the score >=7.5. 
Wanted to mention that at the time we opened this topic, only the vulnerabilities posted for initial confirmation had the score =>7.5.

As our internal process requires that images should be compliant only if there aren't vulnerabilities with score =>7.5, can you please take a look at the above vulnerabilities and let us know if there is something we should be aware or can we discard/acknowledge them or if they will be fixed. 

We have also scanned the image v3.21.0 and the same 2 vulnerabilities with the score >=7.5 are present (as for v3.19.3):

1) CVE-2021-3326
The iconv function in the GNU C Library (aka glibc or libc6) 2.32 and earlier, when processing invalid input sequences in the ISO-2022-JP-3 encoding, fails an assertion in the code path and aborts the program, potentially resulting in a denial of service.
Installed Resource
glibc 2.28
Published by NVD
2021-01-27
CVSS Score
NVD CVSSv3 7.5
NVD CVSSv2 5.0

2) RHSA-2021:4358 
An update for glibc is now available for Red Hat Enterprise Linux 8. Red Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section. The glibc packages provide the standard C libraries (libc), POSIX thread libraries (libpthread), standard math libraries (libm), and the name service cache daemon (nscd) used by multiple programs on the system. Without these libraries, the Linux system cannot function correctly. Security Fix(es): * glibc: Arbitrary read in wordexp() (CVE-2021-35942) * glibc: Use-after-free in addgetnetgrentX function in netgroupcache.c (CVE-2021-27645) * glibc: mq_notify does not handle separately allocated thread attributes (CVE-2021-33574) For more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section. Additional Changes: For detailed information on changes in this release, see the Red Hat Enterprise Linux 8.5 Release Notes linked from the References section. This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original. glibc: Use-after-free in addgetnetgrentX function in netgroupcache.c glibc: mq_notify does not handle separately allocated thread attributes glibc: Arbitrary read in wordexp() 
Installed Resource
glibc 2.28-151.el8
Fixed Version
0:2.28-164.el8
Published by vendor
2021-11-09
CVSS Score
**Vendor CVSSv3 9.1**
**NVD CVSSv3 9.1**
NVD CVSSv2 6


Thank you so much for your help, 
Gabriela

**Comment by GabrielaTepor** [comment]
Hello @gpang-tigera  @lwr20 


Can you please confirm that you have seen the message above?
We would like to finish the upgrade process in the near future and I was wondering if you are able to provide us an insight about the vulnerabilities posted earlier. 

Thank you, 
Gabriela

**Comment by lwr20** [comment]
This is the first time I've been pinged by github about this.  Please don't re-open closed Issues like this - if you create a new Issue, it will get noticed and actioned faster.

**Comment by GabrielaTepor** [comment]
Hi @lwr20 

I am sorry, I did not know that for the closed issues notifications are not being sent. 

Do I need now to open a new issue at this moment?

Thank you, 
Gabriela

**Comment by lwr20** [comment]
It might be safer to make sure, so yes please.

**Comment by GabrielaTepor** [comment]
ok, thank you, just opened: https://github.com/projectcalico/calico/issues/5153
