### ISSUE TITLE
Document new Pool selection features

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#493]
This issue description will be updated to keep track of all documentation related to the new pool selection features.

### Kubernetes Pod Annotations
On a per-pod basis, operators can now use kubernetes annotations to:
- Select a particular IP for a pod
  - Assigned by IPAM
  - Bypassing IPAM
- Select an existing ipPool for a pod

[Here's an example of the annotation to specify ipPools to use for the pod](https://github.com/projectcalico/cni-plugin/issues/213#issuecomment-277875954)

**Action:** 
- [x] Add "Kubernetes Usage" or "Kubernetes FAQ" doc which explains these three methods for selecting pools using annotations

### Pool Selection via CNI Conf
On a per-host basis, operators can configure a CNI network with a Pool to introduce host / rack affinity.

**Actions:**
- [x] [(PR) Document new field in CNI conf](https://github.com/projectcalico/calico/pull/492)
- [ ] (v2.1.0?) Add a "Usage" doc on Rack affinity. At a minimum, just explains the concept of editing each host's configuration to use a different pool. Stretch goal would be to start to explain how to better aggregate those routes by configuring a BGP TOR for each rack. (cc: @kprabhak ?)

### Pool Selection in Mesos (v2.1.0?)
Unlike Kubernetes, Mesos operators can load multiple CNI networks and choose which one to launch a task on. Using CNI conf pool selection, Mesos operators can define multiple CNI networks, each with their own CNI subnet, and select which pool a pod will use by choosing the appropriate network.

**Action:**
- [ ] Document per-task pool selection in Mesos via multiple Calico CNI networks.

cc: @gunjan5

**Comment by lwr20** [comment]
So there's two major IPAM features here - configuring via CNI config and configuring via pod annotation.  

Can we ensure that the docs cover the interactions between them please?  i.e. what happens if I've got CNI config for a nodes preferring particular ippools and then I create pods with an annotated pod spec?

FWIW, I've just tried it, and what seems to happen is that the pod annotations win (and pods get spread over the nodes, so we end up with pods on nodes which do not use the node's preferred pool), though I've not explored all the interactions exhaustively.

**Comment by gunjan5** [comment]
@djosborne should we have a separate issue for the last task in the ckecklist? `Document per-task pool selection in Mesos via multiple Calico CNI networks.` ?

**Comment by tomdee** [comment]
@gunjan5 I think it would be OK for you to open a new issue to track that last point

**Comment by gunjan5** [comment]
Fixed in #524 (last 2 checkpoints have their own issues for v2.2 #547 and #548)
