### ISSUE TITLE
Calico installation using tigera operator does not allow to explicitly the source of calico images.

### ISSUE THREAD

**Issue by NearchPasipou** [projectcalico/calico#5057]
## Expected Behavior
The below image registry/repository/tag must be configurable.
calico-typha: docker.io/calico/typha:v3.20.0
calico-node: docker.io/calico/pod2daemon-flexvol:v3.20.0
calico-kube-controller: docker.io/calico/kube-controllers:v3.20.0

## Current Behavior
At the moment there is no control over the below images and they are pulled from public docker registry.
calico-typha: docker.io/calico/typha:v3.20.0
calico-node: docker.io/calico/pod2daemon-flexvol:v3.20.0
calico-kube-controller: docker.io/calico/kube-controllers:v3.20.0

## Possible Solution
Expose the related values on tigera operator level so as to be able to control the source of image pulling.

## Context
Our requirement is that all images should be pulled from ECR (or private) registries.
This is a security requirement.
Also docker.io has a rate related to image pulling.

## Your Environment
Env: EKS
Tigera operator version: v3.20.0

**Comment by tmjd** [comment]
The operator does support being able to configure those. Please review the [InstallationSpec](https://docs.projectcalico.org/reference/installation/api#operator.tigera.io/v1.InstallationSpec), specifically see `registry` and `imagePath` fields.

>Also docker.io has a rate related to image pulling.

It is possible to provide specify image pull secrets that will be used and that would remove the image rate limiting.

I'm going to close this because I think this is available. Please let me know if I'm mis-understanding something and we can re-open this.
