### ISSUE TITLE
Neutron's DHCP agent is too slow under high churn

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#509]
I ran a churn test, deleting and recreating 10 VMs every 30s or so.  The DHCP agent quickly gets backed up and seems to have no mechanism to catch up.

It doesn't do any batching in its calls to dnsmasq; instead it synchronously processes each update in turn from the rabbit queue.  It rewrites the config for each update and kicks dnsmasq for each update.

**Comment by fasaxc** [comment]
Removing an IP binding requires an expensive shell-out too.  That takes about ~100ms so, without parallelising those calls, 10 VM/s of churn is the limit.

**Comment by fasaxc** [comment]
@Lukasa @neiljerram Just FYI I made a little start on a felix DHCP prototype (forgot to push my branch).  I didn't get very far but it did flush out a bunch of issues:

* The Neutron DHCP agent does more than just DHCP; it also configures dnsmasq as a DNS server.
* If the DNS proxy function is needed, then every agent really does need all the addresses of the other nodes.  **Do you know if this is actually needed?**
* Felix doesn't have all the information it needs to fill in the dnsmasq config.  It needs hostnames (and any DHCP extra options) as well as the IP/MAC mapping.  Not clear if the plugin can provide those easily.
* The DHCP agent supports adding DHCP options and additional routes to the DHCP offer.  Not sure if this is used.

Given the DNS part, it might be better to stick with optimizing the neutron DHCP agent.  There's still a lot of low hanging fruit there.

**Comment by Lukasa** [comment]
> If the DNS proxy function is needed, then every agent really does need all the addresses of the other nodes. Do you know if this is actually needed?

Yup, it definitely is. =) It's exposed through the Horizon UI and I've definitely used it in the past.

**Comment by fasaxc** [comment]
We have a patched version of the DHCP agent that we can build on demand.  I think the next action is with @neiljerram to either merge that to our Neutron fork or propose something else.  (Largely depends on the outcome of his meetings at the Openstack conference)

**Comment by matthewdupre** [comment]
I'm going to merge the WIP fix for this in after 0.22 goes out shortly.

**Comment by matthewdupre** [comment]
The Icehouse and Juno fixes are now merged.

We still need to create a fix for Kilo though.

**Comment by Lukasa** [comment]
Ok, I'll move the fix to Kilo.

**Comment by Lukasa** [comment]
We're actually no longer convinced this is needed, so I'm putting this back on the pile until we're sure.

**Comment by matthewdupre** [comment]
@neiljerram @fasaxc did you two decide whether this fix is needed or not?

**Comment by neiljerram** [comment]
@fasaxc and I discussed, and we agreed that we don't yet fully understand whether this fix is needed.  But we don't want to back it out, because we have customers with highly scaled systems and whose Neutron code includes this change - we don't want to risk breaking those systems.

We need to do more of our own scale testing to pin this down.  The timescale for that is not 1.0, but the timescale over which we'd like to have 0 patches against upstream Neutron.

**Comment by matthewdupre** [comment]
@neiljerram OK - presumably that means we need to rebase the fix to Kilo before 1.0, and then pass it to @plwhite to test?

**Comment by neiljerram** [comment]
I'd rather not just port this fix to Kilo, because I guess (70%) that it isn't needed in practice for Kilo, and because I don't want to add unnecessarily to the amount of Neutron patching that we're carrying for Calico, that will eventually have to reconciled somehow against upstream Neutron.

To close out this issue properly, we should rerun the original churn test with current Neutron tip and - if it shows the problem, and if we think the churn test is simulating something that could happen in a real OpenStack deployment - report and fix that as an upstream Neutron bug; then backport that fix.

**Comment by matthewdupre** [comment]
We've agreed that we're not going to close this down inside 1.0.

**Comment by matthewdupre** [comment]
We've now moved to the calico-dhcp-agent, which gets around the main scale limitations of our usage of the neutron-dhcp-agent.  Closing this.
