### ISSUE TITLE
Uninstalling calico interrupts any network communication

### ISSUE THREAD

**Issue by brennerm** [projectcalico/calico#5100]
After installing Calico on my EKS cluster, creating some network policies and deleting them again I wanted to uninstall Calico. Doing so works just fine but leaves any network communication within the cluster not working.

Reinstalling Calico makes everything works just fine. I double checked that there are no network policies are left.

Is this expected behavior or the cluster go back to the default state of allowing all network communication?

## Expected Behavior
Uninstalling Calico results in all network communication in the cluster to be allowed.

## Current Behavior
When uninstalling Calico, all network communication from within the cluster is being denied.

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. install Calicio on EKS using the aws-calico Helm chart
2. uninstall the aws-calico Helm chart
3. create a pod in any namespace and try to ping an external IP

## Your Environment
EKS version: 1.20.7-eks-d88609
Calico chart version: 0.3.8
Calico app version: 3.19.1

Let me know if you need any further infos.

**Comment by caseydavenport** [comment]
@brennerm this is currently expected behavior - when calico is removed, there are still some rules left programmed on the node for enforcing default behavior. These rules are important while Calico is running to ensure no pod receives network access before Calico has time to program policy for the pod.

You will likely need to flush iptables / remove any `cali-*` chains on the nodes to remove those.

**Comment by brennerm** [comment]
@caseydavenport Thanks for the quick response! Is this behavior documented somewhere? Definitely wasn't able to find it.
Will restart all nodes after the installation and will report back.

**Comment by brennerm** [comment]
Rebooting the nodes made everything come back to normal operation. Thanks!
