### ISSUE TITLE
K8S new a node,the calico not ready

### ISSUE THREAD

**Issue by wwc13485375003** [projectcalico/calico#5128]
my four server  is  172.28.138.127,172.28.138.128,172.28.252.244，172.20.196.48 and 172.20.196.48 is new
the 172.28.138.127 calico
+—————-+——————-+——-+————+————-+

| PEER ADDRESS | PEER TYPE | STATE | SINCE | INFO |

+—————-+——————-+——-+————+————-+

| 172.28.138.128 | node-to-node mesh | up | 2021-11-09 | Established |

| 172.28.252.244 | node-to-node mesh | up | 2021-11-09 | Established |

| 172.20.196.48 | node-to-node mesh | start | 01:50:43 | Connect |
the 172.20.196.48 calico
+—————-+——————-+——-+———-+———+

| PEER ADDRESS | PEER TYPE | STATE | SINCE | INFO |

+—————-+——————-+——-+———-+———+

| 172.28.138.127 | node-to-node mesh | start | 02:40:48 | Passive |

| 172.28.138.128 | node-to-node mesh | start | 02:40:48 | Passive |

| 172.28.252.244 | node-to-node mesh | start | 02:40:48 | Passive |

+—————-+——————-+——-+———-+———+

**Comment by caseydavenport** [comment]
Please follow the issue template when creating new issues. There's not really enough information here to explain the failure. If I had to guess, it is due to a firewall rule between the two networks preventing BGP traffic.

This is likely a node routing issue and not a Calico issue anyway, as Calico relies on proper node networking for BGP to establish.
