### ISSUE TITLE
/proc/sys/net/ipv4/neigh/*/proxy_delay setting failure should not be a critical error

### ISSUE THREAD

**Issue by Ukko-Ylijumala** [projectcalico/calico#5341]
## Expected Behavior
Running Calico binaries inside an unprivileged Linux container should work.

## Current Behavior
Trying to run Calico binaries in an unprivileged Linux container fails because /proc/sys/net/ipv4/neigh/*/proxy_delay parameter is not exported to user namespace. The current behaviour to promote this minor error to a critical failure is nonsensical since setting this parameter is at best marginally useful.

## Possible Solution
The following error checks should be changed to warnings:
* [cni-plugin/pkg/dataplane/linux/dataplane_linux.go:394](https://github.com/projectcalico/calico/blob/0e9c2865822eb48a7049d1933d37fc0316a9c2aa/cni-plugin/pkg/dataplane/linux/dataplane_linux.go#L394)
```
if err = writeProcSys(fmt.Sprintf("/proc/sys/net/ipv4/neigh/%s/proxy_delay", hostVethName), "0"); err != nil {
        return fmt.Errorf("failed to set net.ipv4.neigh.%s.proxy_delay=0: %s", hostVethName, err)
}
```
* [felix/dataplane/linux/endpoint_mgr.go:1193](https://github.com/projectcalico/calico/blob/0e9c2865822eb48a7049d1933d37fc0316a9c2aa/felix/dataplane/linux/endpoint_mgr.go#L1193)
```
err = m.writeProcSys(fmt.Sprintf("/proc/sys/net/ipv4/neigh/%s/proxy_delay", name), "0")
if err != nil {
	return err
}
```

## Steps to Reproduce (for bugs)
1. Install a Kubernetes cluster (with KubeletInUserNamespace=true feature gate) inside nested LXC containers
2. Install Calico as the networking backend
3. Observe that cali* network interfaces fail to get configured and pods fail to start

## Context
Running Calico in user namespace / unprivileged container works otherwise (after patching this particular setting out of the code and rebuilding). This allows to build f.ex. Kubernetes clusters without virtualization overhead in mixed (VM / container) clusters.

Changing the error behaviour of proxy_delay setting should not cause any significant issues.

## Your Environment
* Calico version: v3.22.0-0.dev-24823-g0737725e9d95-dirty / Git commit: 0737725e9 (patched)
* Orchestrator version: Kubernetes 1.22.4
* Kernel version: 5.11.0-43-generic
* OS Image: Ubuntu 20.04.3 LTS
* Container runtime version: containerd://1.5.5
* kubelet version: v1.22.4

**Comment by Ukko-Ylijumala** [comment]
From kernel sources, [net/core/neighbour.c:3773](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/core/neighbour.c?h=v5.16-rc7#n3773)
```
       /* Don't export sysctls to unprivileged users */
	if (neigh_parms_net(p)->user_ns != &init_user_ns)
		t->neigh_vars[0].procname = NULL;
```

**Comment by mgleung** [comment]
Hi @Ukko-Ylijumala , was `proxy_delay` the only setting that had issues? I'm not super familiar with LXC containers, but if I am understanding correctly, I would have expected there to be issues trying to set the other sysctl settings as well. I think in a docker environment we would get around this since the CNI plugin is installed as a binary on the host and so any sysctl changes would be propagated from the host OS to the docker containers. It sounds like this shouldn't work for unprivileged LXC containers, though I am surprised that only `proxy_delay` seems to be causing issues since I would have thought all of the sysctl settings would have been unwritable.

**Comment by Ukko-Ylijumala** [comment]
Hi @mgleung , that seems to be the only sysfs setting that calico-node trips over for our setup, and then only because the sysfs files under /neigh are missing and the error is triggered. The trick with unprivileged containers is that the root in the container namespace has most of regular root's privileges _inside_ the container, but from the host's perspective the container root is (usually) UID 100000. The primary benefit in unprivileged containers is added security, since UID 0 in the namespace has no rights in the host itself.

Please see for example: https://lwn.net/Articles/796700/

I would suggest that demoting this error to warning would be a rather straightforward approach to solve this particular issue (at least for now). As I mentioned, changing `proxy_delay` is optional and should not be a fatal error.

**Comment by mgleung** [comment]
@Ukko-Ylijumala , thanks for the explanation. Seems I misunderstood and the issue isn't really that we don't have the required permissions in the container but that the settings under `/neigh` are missing in your environment because they are not exposed to unprivileged users.

I agree that demoting the error would be the easiest fix, though we might want to also want to add checks to check for the existence of the files as well so our warnings can be a little more prescriptive as to what is happening.

**Comment by cyclinder** [comment]
hi everyone, can I have this?

**Comment by mgleung** [comment]
Hi @cyclinder . PRs are always welcome. Feel free to put something up and we'll go ahead and review it.
