### ISSUE TITLE
full-mesh doesn't support maxRestartTime, bgp password

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#5461]
## Expected Behavior

BGP password and maxRestartTime should work on full-mesh clusters.

Alternatively, global BGP peers should be enhanced to support `passive` on one end of the connection in order to fix the GR race-condition as seen in the full-mesh configuration.

## Current Behavior

Users need to make a choice between full-mesh, which has built-in protection for GR race conditions, and the BGP password and maxRestartTime features which are only available via global BGP peer objects.

## Possible Solution

I think we have three options:

- Implement BGP password and maxRestartTime for full-mesh
- Enhance our global BGP peer template to be smarter such that when the remote end is another Calico instance, it adds in the passive configuration appropriately.
- Both of the above

**Comment by caseydavenport** [comment]
After discussing with @neiljerram and @fasaxc, we think the best option is this:

> Enhance our global BGP peer template to be smarter such that when the remote end is another Calico instance, it adds in the passive configuration appropriately.

It should be relatively straight forward, and means we don't have multiple ways to achieve the same end while also fixing a bug that exists in the current code when using global BGPPeer objects to connect two Calico instances.

**Comment by bradbehle** [comment]
So if I understand correctly, the proposed solution will mean that for any existing clusters that are using a full mesh, these clusters will have to switch to using a global BGPPeer in order to be able to set maxRestartTime (BGP graceful restart) and/or BGP password?

So if that is the case, then will it still be the case that when switching from full mesh to a global BGPPeer, that nodes in a k8s cluster will have all their pod to pod network connections interrupted as the bird/bgp daemons renegotiate all their connections and route sharing?   We are trying to set the maxRestartTime without having a pod-to-pod network outage in existing clusters.

**Comment by caseydavenport** [comment]
I believe that going from no password -> password is fundamentally a disruptive activity based on my memory of a discussion with @neiljerram, so whether or not this is done via a full-mesh or global peer there is likely to be disruption enabling that feature on an existing cluster. 

You make a good point re: maxRestartTime though - if that _can_ be adjusted without disruption, then we need to either ensure that the switch from full-mesh -> global peers is graceful, or we need to add that config option to full-mesh mode.

**Comment by bradbehle** [comment]
Yeah, the BGP password feature I could see requiring a small disruption, that seems reasonable.  the masRestartTime one is the one we think is more important to either work with a full mesh, or find a way to change it in a non-disruptive way.

**Comment by mgleung** [comment]
Both of the fixes are in and targeted for Calico v3.23.
