### ISSUE TITLE
Recommended way to install Calico on AWS EKS

### ISSUE THREAD

**Issue by samm-git** [projectcalico/calico#5636]
It is not clear what is a recommended way to install Calico on EKS and how to make it correctly using only Helm and Tigera operator.

In the [official Calico doc about EKS](https://projectcalico.docs.tigera.io/getting-started/kubernetes/managed-public-cloud/eks) it is recommended (still) to use generated manifest `calico-vxlan.yaml`. Also installation process requires to delete `aws-node` daemonset and patch `calico-node` daemonset later.  This must be done before nodegroup creation. This procedure works fine for me.

From other side many other pages recommending to use Helm which setting up Tigera operator, which should handle installation. Also official aws doc [recommends this](https://docs.aws.amazon.com/eks/latest/userguide/calico.html).

I tried to migrate to the Helm setup (new cluster) but nodes never been able to get to healthy state due to `cni` errors. Also it is not clear if operator would/should handle `aws-node` deletion and if result would be similar to the `calico-vxlan.yaml`. So at the moment i reverted to old, manifest based setup. 

## Expected Behavior

Documentation on how to setup EKS with Helm/Tigera or note that it is not [yet] supported.

## Current Behavior
Page about Manifest based setup is very detailed and provides working Calico setup and Helm based installation failing and no details are covered. E.g. how to tell Tigera to use images from the private ECR, of if Tigera must be created before node groups, do we need to delete `aws-node` daemonset, etc.

## Possible Solution
Update documentation about EKS/Calico installation.

## Steps to Reproduce (for bugs)

1. Create new EKS cluster
2. Install calico from helm
3. Nodes are never comes up to ready state due to CNI errors.

## Context
I would like, if possible, to use Helm based installation to simplify upgrade process.

## Your Environment

AWS EKS setup, latest helm version.

**Comment by caseydavenport** [comment]
@samm-git the doc that you linked to itself has a link to the official EKS documentation for installing Calico on EKS: https://docs.aws.amazon.com/eks/latest/userguide/calico.html

That guide includes instructions for how to use a helm chart to install Calico. The helm chart itself includes the tigera operator as its install mechanism, and results in EKS with Amazon VPC CNI networking.

For installing Calico networking on EKS, the instructions currently only include a manifst-based approach for v3.22, although we are working on updating the docs to include an operator-based approach (which will also work for helm).

This is the install config I needed for Calico to run with Calico networking (not VPC CNI) on EKS:

```
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
```

**Comment by mconigliaro** [comment]
From the official EKS docs: `The recommended way to install Calico on Amazon EKS is by using the Calico Operator instead of these charts or manifests.`

**Comment by caseydavenport** [comment]
We'll need to submit a PR to update that to be more precise. The Amazon EKS team does not maintain the charts or manifests in the procedure, nor do they maintain the Calico Operator. However, the chart in the procedure **is** the very same Calico Operator that they recommend.

There is history here:

1. Amazon used to maintain their own manifest for installing Calico
2. Amazon used to maintain their own helm chart for installing Calico
3. Amazon has since deprecated and removed support for both of those methods above.
4. Instead, Amazon now recommends the use of the Calico Operator helm chart, supported by the Calico team.

I believe the warning is referring to (1) and (2) when it mentions the unsupported manifest and chart, whereas the instructions have been updated to use (4), which is the recommended way.
