### ISSUE TITLE
Add support for deploying calicoctl via tigera-operator

### ISSUE THREAD

**Issue by telmich** [projectcalico/calico#5639]
Currently one has to install the same/similar version of calicoctl manually after installing the tigera-operator.

## Expected Behavior

In terms of the helm chart, I'd recommend to extend

```
calicoctl:
  image: docker.io/calico/ctl
  tag: v3.22.0
```

with:

```
calicoctl:
  image: docker.io/calico/ctl
  tag: v3.22.0
  enabled: true
```

to also deploy calicoctl.

## Current Behavior

```
helm repo add projectcalico https://docs.projectcalico.org/charts
helm install calico projectcalico/tigera-operator --version v3.20.2
kubectl apply -f https://docs.projectcalico.org/manifests/calicoctl.yaml
```

... potentially mismatching the version of calico

## Possible Solution

Simple wrapper in the tigera-operator to include the correct version of calicoctl, if calicoctl.enabled = true

## Steps to Reproduce (for bugs)

See above

## Context

Kubernetes

## Your Environment

any k8s with helm

**Comment by telmich** [comment]
Just after creating this ticket I did actually run into this problem:

```
[19:37] bridge:server100% calicoctl create -f - < ./calico-bgp.yaml 
time="2022-02-20T19:37:25+01:00" level=error msg="failed to decode \"{\\\"level\\\":\\\"debug\\\", \\\"msg\\\": \\\"nsexec-0[28333]: forward stage-1 (28334) and stage-2 (28335) pids to runc{\\\"level\\\":\\\"debug\\\", \\\"msg\\\": \\\"nsexec-1[28334]: signal completion to stage-0\\\"}\" to json: invalid character 'l' after object key:value pair"
time="2022-02-20T19:37:25+01:00" level=error msg="failed to decode \"\\\"}\" to json: unexpected end of JSON input"
Version mismatch.
Client Version:   v3.22.0
Cluster Version:  v3.20.4
Use --allow-version-mismatch to override.

command terminated with exit code 1
[19:37] bridge:server100% 
```

**Comment by caseydavenport** [comment]
I don't think it really makes sense to install calicoctl as part of the operator, given it's a CLI utility and most users either don't want it installed at all or they want it installed on their local machine (and not the cluster).

The operator _does_ install the Calico API server, which logically fulfills the same purpose as calicoctl (allowing the use of `kubectl` to manage most Calico configuration.

**Comment by caseydavenport** [comment]
```
helm install calico projectcalico/tigera-operator --version v3.20.2
kubectl apply -f https://docs.projectcalico.org/manifests/calicoctl.yaml
```

^ You can pin the version of calicoctl by the way. The tar file attached to each release should include a calicoctl manifest to use with that release: https://github.com/projectcalico/calico/releases/tag/v3.20.2

**Comment by telmich** [comment]
While yes, I can do

```
kubectl apply -f https://docs.projectcalico.org/archive/v3.20/manifests/calicoctl.yaml
```

But my point is that a) this is not patch level specific b) this is out of flow: 99% is done by the tigera operator and calicoctl is separated from it.

The main motivation for installing calicoctl is to apply BGP configurations.

Checking the calico-kube-controller pod which is installed by default, it does not contain calicoctl:

```
[11:44] blind:~% kubectl -n calico-system exec -ti calico-kube-controllers-5bc647dbbf-6rs5c -- calicoctl
ERRO[0000] exec failed: container_linux.go:380: starting container process caused: exec: "calicoctl": executable file not found in $PATH 
command terminated with exit code 1
```

So in short: we are looking for a consistent way of applying calico cni + calicoctl inside a cluster with the exact same version. I understand that it might seem counter intuitive at first, but adding support for `calicoctl.enabled=true` could be very self explanatory and I think also very helpful for others.

**Comment by caseydavenport** [comment]
> this is not patch level specific

Yep, but we do ship patch-specific manifests within the .tgz file attached to each release, and in general we highly recommend that you maintain your own manifests in your own config management tooling / githops workflow anyway. 

> this is out of flow

`calicoctl` is a CLI tool that is largely meant to be run on a user's client machine and shouldn't need to be deployed to the cluster itself, and the operator is responsible for installing Calico components that run on the cluster, so it's not a great fit. Yes, we provide some convenient manifests for running calicoctl as a pod, but IMO those should be deprecated and removed, as it's a bit of an anti-pattern.

The issue here is that the project as a whole is moving away from recommending `calicoctl` as the way to manage Calico API resources. You should be able to do that just fine via `kubectl` or other means of interacting with the Kubernetes API so long as the Calico API server is installed, which the operator will already do for you. 

I don't want to encode `calicoctl` as a part of our helm chart / operator API because over the coming months, I expect that for most scenarios that's not the tool users should be using, and kubectl is a more appropriate tool.

**Comment by JonasJasas** [comment]
Is it possible to create calico resource:
```yaml
apiVersion: projectcalico.org/v3
kind: HostEndpoint
``` 
using calico operator?
