### ISSUE TITLE
Allow disabling the RPF check for specific pods

### ISSUE THREAD

**Issue by AloysAugustin** [projectcalico/calico#5643]
This feature request is about having the possibility to (at least partially) disable the RPF check that is performed on the traffic coming from the pods. It would allow some pods to send traffic with a source IP address which is not the pod address, i.e. the pods will be able to spoof their IP address. For this to be possible, the pods will typically also require CAP_NET_RAW or CAP_NET_ADMIN.

## Expected Behavior
We'd like to have a way to configure pods so that the RPF check is not enforced at the host level for the traffic they send.

## Current Behavior
Currently, pods are unable to spoof their IP addresses.

With the iptables dataplane, this is enforced with an iptables rules in the raw PREROUTING chain that uses the rpfilter module. In addition to that, in IPv4, the kernel `/proc/sys/net/ipv4/conf/<interface>/rp_filter` sysctl control an additional check.

## Possible Solution
A possible solution could be to add an annotation to the pods that would control the RPF check enforcement. This annotation could either entirely disable the RPF check for the pods, or selectively define some source addresses / prefixes that the pods is allowed to use.
This has security implications, so the annotation should be properly documented, and potentially disabled by default unless felix is specifically configured to accept it.
We have a working implementation of this for the iptables dataplane here: https://github.com/calico-vpp/calico/tree/rpf-tests 

## Context
This was initially discussed with Shaun here: https://calicousers.slack.com/archives/CPEPF833L/p1645036827971669

The use case we have for this feature is that we'd like to have a set of pods behave as a single virtual endpoint for VXLAN traffic.
For the traffic going towards these pods we can just send it to a UDP service targeting them and the packets will get load balanced across the pods.
For the traffic sent by the pods however, if the source IP addresses are the pod addresses, then the other end of the tunnel won't recognize the packets as being part of the same tunnel, it expects them to have the service IP as source IP. That's why we'd like to have the possibility to send packets with the service IP as source from our pods.

Using this model means that the remote end of the VXLAN tunnel doesn't need to be aware of the specific IP addresses of the individual pods, and it's configuration doesn't need to be updated when the service scales up / down.

## Your Environment
* Calico version: 3.20.0
* Orchestrator version: EKS, k8s v1.20.11-eks-f17b81
* Operating System and version: Ubuntu 20.04

**Comment by fasaxc** [comment]
Think this would be a useful feature.  However, since it does poke a hole in our security model, I do think it'd make sense for it to be disabled by default in a similar way to the [`ipAddrsNoIPAM` annotation](https://projectcalico.docs.tigera.io/reference/cni-plugin/configuration#requesting-a-specific-ip-address).

Perhaps a new annotation in the same vein: `cni.projectcalico.org/extraRoutes: '["10.1.2.0/24"]'` that then maps through to a field in the `WorkloadEndpoint`.

Some issues that will need to be addressed:
* Calico doesn't currently write ECMP routes for local workloads.  If there are two workloads that both have the same IP then only one will "win" right now.
* If the `extraRoutes` are allowed to be non-32s we'll need to audit for code that assumes that workload routes are /32s. I think felix has a number of places that assume that the ipNetworks field contains /32s only.
* Should `extraRoutes` be required/forbidden form overlapping any IP pools.  OTOH, IP pools are the way to tell Calico how to treat a block of IPs (wrt to NAT/Wireguard/overlay/etc); OTOH, we don't want Calico to auto-allocate conflicting IPs.  Perhaps require an IP pool with a particular `allowedUse` that prevents it from being used for normal allocations.

**Comment by AloysAugustin** [comment]
Thanks for the feedback, I think there are two different ways to approach this.

The first one, which is the one I think you're thinking to, consists in adding routes tactically so that the rpf check naturally succeeds. However this has several drawbacks that you've pointed out:
- It may disrupt the cluster routing. 
- If two pods that need to use the same spoofed IP end up on the same node, only one of them will work (at random, the traffic from the other one will be silently dropped) - that is the biggest concern for me.

An other approach would be to do tweak the iptables rules installed by felix (and the rp_filter sysctl in ipv4) to skip reverse path filtering from some traffic. The drawback of this approach is that it would require specific code in each dataplane to work, but I think that it is still outweighed by not having the drawbacks of installing additional routes.

My initial prototype took this path, and sets up something like this in the `raw` table (for the iptables dataplane):
```
-A cali-PREROUTING -j MARK --set-xmark 0x0/0xf0000
-A cali-PREROUTING -i cali+ -j MARK --set-xmark 0x40000/0x40000
-A cali-PREROUTING -m mark --mark 0x40000/0x40000 -j cali-rpf-skip # <- New rule
-A cali-PREROUTING -m mark --mark 0x40000/0x40000 -m rpfilter --validmark --invert -j DROP
-A cali-PREROUTING -m mark --mark 0x0/0x40000 -j cali-from-host-endpoint
-A cali-PREROUTING -m mark --mark 0x10000/0x10000 -j ACCEPT
-A cali-rpf-skip -i <pod-interface> -s <allowed-prefix> -j ACCEPT
-A cali-rpf-skip -i <pod-interface> -s <allowed-prefix-2> -j ACCEPT
-A cali-rpf-skip -i <pod-interface-2> -s <allowed-prefix> -j ACCEPT
```
The controlling annotation is similar: `cni.projectcalico.org/allowedSourcePrefixes: '["10.1.2.0/32"]'`

Which approach do you think we should pursue?

**Comment by Jaeyo** [comment]
+1
@fasaxc 
We also have a unusual network environment and cannot adopt calico because of rpfilter.
I'd like to ask you to put on/off options for rpfilter itself, not only just by pod annotation.
