### ISSUE TITLE
setting felix / typha healthport does not work 

### ISSUE THREAD

**Issue by manuelbuil** [projectcalico/calico#5697]
I would like to change the felix healthport from the default 9099. By looking at `felixconfigurations.crd.projectcalico.org`, I can see the parameter there:

              healthPort:
                type: integer

However, after setting that parameter, I still see felix using 9099.

I guess the problem is that the operator has that value hardcoded as 9099:

https://github.com/tigera/operator/blob/master/pkg/render/node.go#L1586

## Expected Behavior

I would like to have a way to set healthports, for example felix or typha, in case I have some other pods using that port too

## Current Behavior

Not possible to change those ports when using the operator

## Possible Solution

Expose the healthport numbers in the operator CRD

## Steps to Reproduce (for bugs)

1. Deploy calico via the operator
2. Change the felix healthport in felixconfigurations.crd.projectcalico.org
3. Reboot the calico-node daemonset with the new value
4.

## Context

Deploy with other apps using the default port

## Your Environment

* Calico version: v3.21.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Ubuntu 20
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Yep agree this is a bug. Operator should not be hard-coding that value.

**Comment by caseydavenport** [comment]
We could, in theory, just have the operator monitor the value in FelixConfiguration and use that. The awkward part is that changes to FelixConfiguration take effect immediately, where as changing the probes on the pod requires a rolling update and so will take some amount of time.

The alternative is to deprecate the felix configuration version of this field and switch to an operator-only based configuration.

CC @tmjd @fasaxc for input.

**Comment by caseydavenport** [comment]
Whatever we decide, felix `HealthHost` probably needs similar treatment.

**Comment by tmjd** [comment]
If we have the operator set an env var then Felix would not change until the pod was rolled. So we can force the value to only change with the pod.

**Comment by caseydavenport** [comment]
> If we have the operator set an env var then Felix would not change until the pod was rolled. So we can force the value to only change with the pod.

Correct - that's my second option above, but it would mean that the FelixConfiguration is essentially dead and deprecated (setting it would have no effect on an operator-managed cluster)

**Comment by manuelbuil** [comment]
Thanks for investing time in this! We will have the same problem with `typha healthport`, should I open a new issue?

**Comment by caseydavenport** [comment]
@manuelbuil nope we can track both with this issue.

**Comment by fasaxc** [comment]
I think it'd be good to solve the problem of operator defaulting felixconfig values so that the user can just write to felixconfig and operator will realise "user has overriden my value of this non-critical field".

**Comment by tmjd** [comment]
> > If we have the operator set an env var then Felix would not change until the pod was rolled. So we can force the value to only change with the pod.
> 
> Correct - that's my second option above, but it would mean that the FelixConfiguration is essentially dead and deprecated (setting it would have no effect on an operator-managed cluster)

I'm not suggesting that FelixConfiguration should be dead. I'm suggesting the operator can monitor FelixConfiguration for the value to use but take that value and set it as an Environment Variable. That will keep all the running pods from switching until the pod itself is updated.

> I think it'd be good to solve the problem of operator defaulting felixconfig values so that the user can just write to felixconfig and operator will realise "user has overriden my value of this non-critical field". ManagedFields is supposed to do that?

I'm not sure if we'd need to be concerned with ManagedFields for this, I don't think the operator will need to care if it previously set the field or if the user set the field. The operator only needs to take what is set and apply the value read from configuration.
I think the only cases where we need to be concerned with ManagedFields is if the operator needs to know if it previously set a field or if the user has modified it. Maybe an edge case we need to consider is a disabling case for the metrics.

Unfortunately all this discussion ^ is not applicable to Typha because we don't have a current config option for Typha. My hacky (avoiding coming up with a new API) thought is to just make Typha's port be Node-1 (since it is set to 9098 right now).

**Comment by caseydavenport** [comment]
>  I'm suggesting the operator can monitor FelixConfiguration for the value to use but take that value and set it as an Environment Variable. That will keep all the running pods from switching until the pod itself is updated.

Ah, I originally thought this wouldn't work because all of the felixes in the cluster will have already spotted the FelixConfiguration change and restarted, but I suppose if it's _always_ set via the env var then the config update will be ignored by the felixes and we'll get a nice rolling update. That is actually good enough I think.

> I'm not sure if we'd need to be concerned with ManagedFields for this, I don't think the operator will need to care if it previously set the field or if the user set the field

Yep, we should look at managed fields but that's for a different problem IIUC - namely the case where the operator and a user might want to set a field within FelixConfiguration. In this case, the operator's use of the field is read-only.

**Comment by caseydavenport** [comment]
I had some code lying around from before so stuck it in a PR: https://github.com/tigera/operator/pull/1846

Need to test it out and review it, but it might do the trick for felix at least.

**Comment by howels** [comment]
Could we please ensure that Felix healthport and typha healthport are both exposed via the operator, to avoid conflicts with existing services during installation.

**Comment by caseydavenport** [comment]
After discussing internally we think a better solution might be to move off of using HTTP probes for readiness / liveness altogether and switch to something like a unix domain socket + exec based probe that way there will be no TCP ports opened on the host.

**Comment by howels** [comment]
> After discussing internally we think a better solution might be to move off of using HTTP probes for readiness / liveness altogether and switch to something like a unix domain socket + exec based probe that way there will be no TCP ports opened on the host.

Sounds more robust and less likely to clash with existing host services.

**Comment by howels** [comment]
@caseydavenport looks like https://github.com/tigera/operator/pull/1846 is going to deal with the Felix healthport, can we also add a similar fix to manage the Typha healthport? Both sit on a couple of contiguous IANA un-claimed ports by default and likelihood of clashing with other applications is pretty high.

**Comment by tmjd** [comment]
I think @howels you are aware that PR will adjust Typha also but if not or for any others that come across this issue. That PR also sets the Typha healthport, it sets it to FelixHealth-1. So if Felix HealthPort is set to 9399, typha will use 9398.

**Comment by tmjd** [comment]
I don't think there is anything left to do for this issue so I'm going to close it.
If I'm wrong please comment and we can re-open this issue. Thank you. :wave:
