### ISSUE TITLE
Bug:ResourceExhausted trying to send message larger than max (3035218 vs. 2097152)

### ISSUE THREAD

**Issue by luckymrwang** [projectcalico/calico#5819]
## Current Behavior

Dual stack, the ipv6 mask is 64, blocksize is 110
The error is happened when clainming ipv6 block.And the detail cni.log is following picture.

## Steps to Reproduce (for bugs)

1. Configure dual stack
2.
3.
4.

## Your Environment

* Calico version
v3.21.4
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes v1.20.10
* Operating System and version:
centOS8
* Link to your project (optional):

**Comment by luckymrwang** [comment]
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/8869360/160737991-eab13654-e470-42e0-920b-3120337be5f8.png">

**Comment by lwr20** [comment]
I don't know the IPAM code well - perhaps @caseydavenport knows better?

**Comment by mgleung** [comment]
Hi @luckymrwang , the error message here is telling us that the [IPAM block we create](https://github.com/projectcalico/calico/blob/31d683f0caaada2fff30843f2ae763baf13ba8ba/libcalico-go/lib/ipam/ipam_block.go#L44) is larger than the apparent 2 MB limit on the client. I do not think we have an accessible setting for changing the client message size limit, but one easy thing we could do to check this is to try changing the blocksize and IPv6 mask. Can I have you try that and see if that fixes things? If it works, it means that we will need to provide some parameters for increasing the client message size (or increase the client message size for all calls).

Also, just for our information, are you running Calico with the Kubernetes datastore or do you have your own etcd datastore? I do not think it should matter too much since the error is on the client side but it might provide more insight into why you are hitting this error.

**Comment by luckymrwang** [comment]
@mgleung Thanks your reply. You are right and it's ok after I changed the blocksize bigger than 115. The `ippool` crd is also mentioned that the IPv6 blocksize value should be 116 and 128. Just when I execute `calicoctl edit ippool default-ippool-ipv6` to edit IPv6 blocksize, I will get error `IPv6 block size must be between 116 and 128`. But when I execute `kubectl edit ippool default-ippool-ipv6`, I get nothing. It means that 1 to 128 are all allowed, and it does not throw any error. Finally when `IPAM creating block` throw a rpc error `ResourceExhausted ....` above mentioned.

**Comment by mgleung** [comment]
> Just when I execute calicoctl edit ippool default-ippool-ipv6 to edit IPv6 blocksize, I will get error IPv6 block size must be between 116 and 128. But when I execute kubectl edit ippool default-ippool-ipv6, I get nothing. It means that 1 to 128 are all allowed, and it does not throw any error.

When editing a lot of the Calico specific resources, it is always a lot safer to use `calicoctl` just because a lot of our validations are baked into the utility to prevent issues. That being said, we should probably explore our options so that we can allow for some larger blocksizes.

**Comment by caseydavenport** [comment]
> it is always a lot safer to use calicoctl just because a lot of our validations

You should use the `projectcalico.org/v3` API, either via `calicoctl` or the Calico API server (with kubectl). 

Main thing is don't ever modify `crd.projectcalico.org` resources - they are NOT validated.
