### ISSUE TITLE
Avoiding specific Node-to-Node routes for CNI traffic

### ISSUE THREAD

**Issue by howels** [projectcalico/calico#6013]
We have a setup where Nodes are connected by a number of disjoint networks, some of which are intended for bulk-transfers and can often become congested, leading to dropped traffic or otherwise undesirable conditions. We use BGP between Nodes, which can lead to these sub-optimal paths being used and timeouts occurring.

## Expected Behavior

Want to be able to tell the BGP daemon to prefer routes between Nodes, or to blacklist certain routes.

## Current Behavior

All routes are used and we observe timeouts or inconsistencies in CNI traffic.

## Possible Solution

Allow configuration of the BGP daemon to prevent traffic to certain routes.

## Your Environment

* Calico version - 3.20
* Orchestrator version - Kubernetes 1.21
* Operating System and version: SLES 15 SP3

**Comment by caseydavenport** [comment]
https://github.com/projectcalico/calico/blob/89f90a81558ff2c4fa71e7e052af458750e3a85d/confd/etc/calico/confd/templates/bird.cfg.template#L212-L214

^ Calico sets the `source address` parameter for BGP sessions based on the auto detected node IP. 

There are a few ways to configure this: https://projectcalico.docs.tigera.io/networking/ip-autodetection

I suspect you just need to configure auto detection such that BGP binds to the correct source address on the network that you want pod traffic to be routed over.

Note that if you're using BGPPeer objects, you will need to set `UseNodeIP` to force this binding (as described here: https://projectcalico.docs.tigera.io/reference/resources/bgppeer). This field was introduced in Calico v3.22.0.

For full mesh, looks like we always set the source address option so that isn't needed.

**Comment by howels** [comment]
> https://github.com/projectcalico/calico/blob/89f90a81558ff2c4fa71e7e052af458750e3a85d/confd/etc/calico/confd/templates/bird.cfg.template#L212-L214
> 
> ^ Calico sets the `source address` parameter for BGP sessions based on the auto detected node IP.
> 
> There are a few ways to configure this: https://projectcalico.docs.tigera.io/networking/using 
> 
> I suspect you just need to configure auto detection such that BGP binds to the correct source address on the network that you want pod traffic to be routed over.
> 
> Note that if you're using BGPPeer objects, you will need to set `UseNodeIP` to force this binding (as described here: https://projectcalico.docs.tigera.io/reference/resources/bgppeer). This field was introduced in Calico v3.22.0.
> 
> For full mesh, looks like we always set the source address option so that isn't needed.

We are using `nodeAddressAutodetectionV4:  interface:` but this appears to result in issues we describe where the nodes have multiple addresses. From reading the docs it appears that this address is used to establish the BGP mesh, but once the mesh is established Nodes on the same subnet can form paths over alternative interfaces. Can you confirm that this address is the only one which will be used for CNI traffic with a BGP mesh configuration and not just the address used to identify the Node?

**Comment by caseydavenport** [comment]
If you're using BGP mesh, then yes you should see `source address <node IP>` set in your BIRD configuration on each node. My understanding is that will tell BIRD to use that IP as the next hop address advertised to remote BGP peers. 

What those remote BGP instances do with that next hop information, however, is dependent on how routing is configured on that node. For example, if for some reason the remote BIRD believes that the received next hop is only reachable via a different interface, it will try to route traffic via that interface instead.

It might help if you share some more details of a couple of the nodes in your cluster, in case I'm misunderstanding something. e.g., 

```
ip addr show
```
```
ip route show
```

**Comment by mgleung** [comment]
It looks like there hasn't been that much recent activity on this issue so I'm going to close it. I'll reopen the issue if there's more activity.
