### ISSUE TITLE
Guideline for migrate existing AWS Calico helm to tigera operator

### ISSUE THREAD

**Issue by nathanwang-comp** [projectcalico/calico#6052]
Please help provide a solution which can help use migrate existing AWS Calico helm to tigera operator. The solution should work for both new installation and existing AWS Calico installation.
I am doing auto update with terraform.

**Comment by caseydavenport** [comment]
@nathanwang-comp I'm afraid we'll need more information than that in order to help. Please fill out the issue template when submitting new issues. Specifically, we need to know how you installed Calico on your cluster with links to the chart and documentation, as well as the version of Calico you're running and steps you have tried.

**Comment by tmjd** [comment]
Excepts from [duplicate issue on tigera/operator](https://github.com/tigera/operator/issues/1948)
>Have you followed [this doc](https://projectcalico.docs.tigera.io/maintenance/operator-migration) which the [deprecation notice on aws-calico chart on amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-calico/README.md) points to?
>
>Since it seems like this is already provided I'm going to close this issue. If you believe this issue needs to be opened back up please explain why and I can do so.

@caseydavenport  I closed the issue on tigera/operator because it seems this already exists. I'll leave it to you if you want to do the same.

**Comment by caseydavenport** [comment]
Yeah, going to close this one since I believe this is documented. Please comment here if you follow the linked documentation and still have questions.
