### ISSUE TITLE
Support for defining the replica count for Deployments via Helm Chart

### ISSUE THREAD

**Issue by michelzanini** [projectcalico/calico#6100]
Hi,

It should be possible to define the replica count for Deployments (`spec.replicas`), in order to run 2/2 instead of 1/1, for example.

Places that should support the configuration are:

- tigera-operator (from main Helm chart level)
- calico-typha (created by the operator)
- calico-kube-controllers (created by the operator)

Would be good to support it on the Tigera Operator Helm chart.

Thanks.

**Comment by song-jiang** [comment]
tigera-operator and calico-kube-controllers are `controllers` so adding more replicas makes little sense and may create race between two replicas. 

calico-typha replica count is controlled by operator and is not something we encourage users to make a change.

**Comment by caseydavenport** [comment]
> calico-typha (created by the operator)

This deployment in particular is actually auto-scaled based on the cluster size by the operator. 

I think we might be open to making it user-configurable if the right use-case arises, but I'm not sure what that would be right now since it is really a function of cluster size so can be determined automatically. 

The other two I agree were not designed to need multiple running copies.

**Comment by caseydavenport** [comment]
Given this, I don't think it actually makes sense to do this since those deployments aren't meant to run in a horizontally scaled manner (or are already horizontally scaled)
