### ISSUE TITLE
I upgraded calico from 3.14 to 3.23.1, I got this errors:

### ISSUE THREAD

**Issue by ruanshudong** [projectcalico/calico#6129]
I upgrade calico from 3.14 to 3.23.1, I got this errors:

[60] felix/watchercache.go 181: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices"
2022-05-20 11:00:53.272 [INFO][60] felix/watchercache.go 194: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=resource does not exist: KubernetesEndpointSlice with error: the server could not find the requested resource
2022-05-20 11:00:54.007 [WARNING][60] felix/health.go 211: Reporter is not ready. name="int_dataplane"
2022-05-20 11:00:54.007 [WARNING][60] felix/health.go 211: Reporter is not ready. name="async_calc_graph"
2022-05-20 11:00:54.273 [INFO][60] felix/watchercache.go 181: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices"

## Environment
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.18.8
* Operating System and version: ubuntu20.04

**Comment by caseydavenport** [comment]
Please check the system requirements for Calico before upgrading: https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements#kubernetes-requirements

v3.23 is not supported on Kubernetes v1.18 - the Kubernetes EndpointSlice API is not available yet in that version.

v3.14 and k8s v1.18 are both quite old - when upgrading, you need to make sure that the versions of Kubernetes and Calico are compatible with each other.

**Comment by seh** [comment]
@caseydavenport, I see this same failure in _some_ of my "calico-typha" containers running atop Kubernetes version 1.19.9, which _does_ have the "endpointslices" resource registered with the API server.

**Comment by seh** [comment]
This is with Calico version 3.23.1 atop Kubernetes mid-upgrade from version 1.19.9 to version 1.21.14.

What's bizarre is that out of Typha's three pods commissioned by its _Deployment_, one or two of them will become healthy, and the rest will not become healthy, even though all three are using the same pod spec.

[Here is the log](https://github.com/projectcalico/calico/files/9002999/calico-typha-log.txt) from one of the unhealthy pods. That pod is running on a node at Kubernetes version 1.19.9.

**Comment by caseydavenport** [comment]
@seh so Calico v3.23.1 will use the v1 EndpointSlice API, which I believe was introduced in Kubernetes v1.21, whereas v1.19 will use the v1beta1 EndpointSlice API (I believe, based on https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/) 

I suspect the problem is that your apiserver is still serving v1beta1 and your Calico pods are looking for the v1 API?

**Comment by caseydavenport** [comment]
> s complaining about the resource "kubernetesendpointslices" in a Calico-related API group, and not the built-in Kubernetes "endpointslices" resource.

Yeah, I think that's just because the log is coming from a bit of code that abstracts away the fact that this is backed by a Kubernetes resource. It's still calling into the k8s EndpointSlice API though.

**Comment by caseydavenport** [comment]
I guess I'm surprised that Calico v3.23 worked at all to start with against v1.19.9, and similarly surprised that this only happens on upgrade of the k8s API to an endpoint slice API that should actually work with the version of Calico you have installed.

**Comment by seh** [comment]
To clarify, it appears that the failures start when Calico 3.23 tries to get going in a cluster in which _none_ of the API servers have been upgraded past version 1.19.9. I'm not sure if having _some_ of those API servers upgraded helps or not. With _kOps_, there's a race where it may start replacing control plane machines before it notices that the newly upgraded Calico pods are unhealthy. Replacing that first control plane machine may allow the Calico pods to become healthy, because then the new discovery GV becomes available.

I'm going to try to work around using Calico 3.23 on such an old Kubernetes version, and instead try to hold back on upgrading Flatcar Container Linux until we have a Calico version in place that can [tolerate the _ipset_ compatibility requirement](https://kubernetes.slack.com/archives/C3QUFP0QM/p1656377352153789).
