### ISSUE TITLE
No IPAM documentation

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#63]
_From @caseydavenport on February 3, 2016 0:50_

I can't find any documentation that describes Calico's IPAM behavior and how it interacts with pools.  This would be useful info for Calico users to have.

_Copied from original issue: projectcalico/calico-containers#784_

**Comment by djosborne** [comment]
_From @robbrockbank on February 9, 2016 2:15_

@caseydavenport Casey - are you after beefing up our API docs in libcalico (i.e. someone writing to use libcalico), or adding some docs in calico-containers to indicate how our IPAM module assigned IPs from pools etc.  The latter is somewhat dependent on orchestrator though because it might be possible to specify which pool you choose from based on the environment.

**Comment by djosborne** [comment]
_From @caseydavenport on February 9, 2016 17:27_

@robbrockbank - My original intent here was to document how our IPAM module assigns blocks and pools.  I believe I raised this after answering a number of different questions about how Calico assigns IP addresses on Slack.

Maybe this is something that needs to be documented per-orchestrator.

**Comment by djosborne** [comment]
_From @caseydavenport on September 16, 2016 21:21_

Assigning to Turk since he's going to be looking into our docs in the near future.

@djosborne I think the requirement here is a doc that explains the philosophy behind Calico's IPAM behavior, why one would use it, and what it does.

**Comment by ozdanborne** [comment]
Opened #795 to summarize and create a fresh issue
