### ISSUE TITLE
Info on getting calicoctl

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#632]
Someone in the slack was having a hard time figuring out how to get going with calicoctl.

I think we should have a basic install doc that explains

- download the latest release
- put it anywhere that has access to your datstore
  - could be your dev box outside the cluster
  - could be a host inside your cluster
- configure it with access to etcd [link to relevant doc]

cc: @lwr20

**Comment by caseydavenport** [comment]
Yep, this sounds like a good "Usage" guide.

Title: "Installing and Configuring calicoctl"

> configure it with access to etcd

Note that we'll want to support kdd as well - will need to think about how to structure this doc so that it's equally easy for both.

**Comment by tmjd** [comment]
There is already information on configuration that exists in the reference section for calicoctl.  Whoever takes this task should take stock of that and figure out if any of that should be changed or moved or just be linked from the new Usage doc.

**Comment by tmjd** [comment]
I've got a the PR #805 up for this.  The configuration section is kind of light because there is so much already in the Reference section for calicoctl.  @caseydavenport and @ozdanborne do you think I should relocate more of that info into this page or additional Usage pages (perhaps nested under this new one) or just go with linking to the reference?  I don't feel like it is inappropriate where it is currently so I'm inclined to leave it there.

**Comment by ozdanborne** [comment]
Just links to reference is perfect. I'm just looking for a short and sweet guide on how to start using calicoctl. No more information than the bare minimum I listed above is needed.
