### ISSUE TITLE
calico node image v3.23.2 has vulnerability  CVE-2022-1292

### ISSUE THREAD

**Issue by amitbaxi777** [projectcalico/calico#6385]
Issue Description: MEDIUM Vulnerability found in os package type (rpm) - openssl-libs (cvss_v3_base_score=9.8)(CVE-2022-1292 - https://access.redhat.com/security/cve/CVE-2022-1292)
Package path: pkgdb
Severity: MEDIUM
CVSS_V3_Base_Score: 9.8
Advisory_Name: CVE-2022-1292
Advisory_Link: https://access.redhat.com/security/cve/CVE-2022-1292
Type: vulnerabilities(package)

Please fix this for calico node image.

**Comment by coutinhop** [comment]
Hi @amitbaxi777, thanks for reporting this. From what I understand of the advisory, the issue is in this `c_rehash`, which may or may not be included in the calico image, but most probably it is not executed (much like the advisory says for RHEL). Tagging @caseydavenport to check if this is addressed by the upcoming v3.23 patch release and @gpang-tigera for more insight on the CVE...

**Comment by caseydavenport** [comment]
Please rescan calico/node v3.23.3, which has several CVE fixes included.

**Comment by amitbaxi777** [comment]
This is still getting reported with the v3.23.3 image. Can you please recheck and confirm ...?

@caseydavenport
