### ISSUE TITLE
Document need to clean up WEPs for k8s pods when a k8s node is restarted

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#657]
Currently when k8s nodes are rebooted/crash a Delete to the CNI plugin is not done on the nodes and endpoints are leaked.  We should document this perhaps in a FAQ.  It would be great to provide an example or two to clean up those endpoints but I don't know if we want to maintain that.  Maybe a blog post or something would be good to make something like that available.

**Comment by djosborne** [comment]
We should open up a feature request for the true long term solution of this as well.

**Comment by ozdanborne** [comment]
The description is missing a few details. I'll summarize what the desired information should look like:

- In Kubernetes, kubelet can go down and come back up without any disruption of service to the pods.
- However, if a node is down for longer than the `node-monitor-grace-period`, the controller manager will mark the node as unhealthy, and then start evicting its pods.
- This pod eviction process does not send a `CmdDel` to the CNI plugin (Calico), so Calico has no idea the pod has been shut down.
- This results in some cleanup that is never called, such as:
  - releasing the IP address the pod was using
  - deleting the endpoint calico is storing for that pod
- For now, the process of cleaning up these orphaned endpoints is manual.

The goal of this issue is to better document this^ and ideally provide a means of cleaning up those pods (while we work on an automatic solution)
