### ISSUE TITLE
Could I use calico for docker container now?

### ISSUE THREAD

**Issue by linhil** [projectcalico/calico#6698]
I know that calico is used for k8s mostly, but for some specific scenarios, I have to configure the single container rather than pods. Obviously, docker is best for me, I would like to use calico for good performance in BGP mode. 

I know that  `docker run --driver calico ` will fail now. 

I'd like to ask could I use calico for docker? If not, can I use Calico directly in containerd?
 I'm just starting to learn K8s, and K8s is a little difficult for me to deploy a lot of containers as pods cluster.

Thanks a lot.

**Comment by mgleung** [comment]
@linhil out of curiosity, do you have a cluster of different docker containers or are you trying to set up connectivity to an existing K8s cluster from your container? I **think** that it could work in a container, but there is a lot of extra setup that is probably more work than learning how to set up a Kubernetes cluster (i.e. you will need to set up a separate etcd datastore and then modify the Calico configuration to talk to that datastore). I think it might be better in the long run to learn K8s rather than to try to learn enough about Calico in order to make this use case work.

**Comment by lwr20** [comment]
> I'd like to ask could I use calico for docker? If not, can I use Calico directly in containerd?

While this is possible in theory, its certainly _not_ a scenario for beginners.

> I'm just starting to learn K8s, and K8s is a little difficult for me to deploy a lot of containers as pods cluster.

If you're a beginner, may I suggest https://kind.sigs.k8s.io/docs/user/quick-start/ for setting up a k8s cluster?  Or micro-k8s, k3s or one of the other "run a k8s cluster on your laptop" tools?

**Comment by lwr20** [comment]
Here's a tutorial for creating a kind cluster with Calico: 
https://alexbrand.dev/post/creating-a-kind-cluster-with-calico-networking/

**Comment by linhil** [comment]
> Here's a tutorial for creating a kind cluster with Calico: https://alexbrand.dev/post/creating-a-kind-cluster-with-calico-networking/

OK, I have just configured the etcd and calicoctl seperately without k8s. I'll try, thanks a lot
