### ISSUE TITLE
Installed summarized routes per node don't have the source address set

### ISSUE THREAD

**Issue by svallala** [projectcalico/calico#6712]
We configured FELIX_DEVICEROUTESOURCEADDRESS to use the node IP. This is ensuring that all the pods running on the local node have the source correctly set for the routes installed as shown below:

[root@centos-60-205 ~]# hostname -i
fd74:ca9b:3a09:868c:10:9:60:205

fd74:ca9b:3a09:868c:172:18:0:5d80 dev calic50a86f0887 src **fd74:ca9b:3a09:868c:10:9:60:205** metric 1024 pref medium
fd74:ca9b:3a09:868c:172:18:0:5d81 dev calic5478f31ebd src **fd74:ca9b:3a09:868c:10:9:60:205** metric 1024 pref medium

But the summarized routes for the IPAM blocks for the node don't have the source set. Actually any routes learnt via BGP when installed on the host does not have the source specified.

fd74:ca9b:3a09:868c:172:18:0:5f80/122 via fd74:ca9b:3a09:868c:10:9:20:103 dev br0 proto bird metric 1024 pref medium
fd74:ca9b:3a09:868c:172:18:0:6500/122 via fd74:ca9b:3a09:868c:10:9:60:207 dev br0 proto bird metric 1024 pref medium
fd74:ca9b:3a09:868c:172:18:0:68c0/122 via fd74:ca9b:3a09:868c:10:9:20:101 dev br0 proto bird metric 1024 pref medium
fd74:ca9b:3a09:868c:172:18:0:7ec0/122 via fd74:ca9b:3a09:868c:10:9:60:206 dev br0 proto bird metric 1024 pref medium

We have a floating IP address that is assigned to the nodes. Since there is no source address set, when connecting to a pod or service resolving to an endpoint on a different node, the floating IP address is used as the source for the packets. When the floating IP address moves we are seeing a lot of connection issues.

Even for these routes, the FELIX_DEVICEROUTESOURCEADDRESS should be used to set the source address

Calico: v3.21.5
Kubernetes: v1.23.8
Kernel Version: 3.10.0-1127.13.1.el7.x86_64

**Comment by Josh-Tigera** [comment]
Just to double-check since you're using IPv6 addresses are you setting `FELIX_DEVICEROUTESOURCEADDRESS` or `FELIX_DEVICEROUTESOURCEADDRESSIPV6`?

**Comment by lwr20** [comment]
> We have a floating IP address that is assigned to the nodes. 
This sounds like an unusual setup.  Can you describe how to set this up in enough detail that we could repro please?

**Comment by svallala** [comment]
We have keepalived running on a few nodes and the VIP assigned will float based on the health of the node. We configured the bridge interface on the node and since it's the primary interface Calico will use that interface. The issue is not tied to a bridge being present, the issue will be seen even on interfaces without the bridge interface.

**Comment by caseydavenport** [comment]
FELIX_DEVICEROUTESOURCEADDRESS is only meant to cover the device routes programmed by Calico (specifically Felix). The purpose of this configuration option is to handle traffic sent from the local host to pods running on that host, since cali veths do not have a host-side IP address assigned to them.

Learned BGP routes programmed by BIRD don't use the same source address, they use the source of the interface on the host that the next hop is reachable over. This generally doesn't need to be configured because the the real devices used on the host have IPs assigned to them from which to select a source address. 

> when connecting to a pod or service resolving to an endpoint on a different node, the floating IP address is used as the source for the packets

What IP address is Calico autodetecting for it's BGP session? It should be visible on the Node resource in the annotations via `kubectl get node <name> -o yaml>

**Comment by svallala** [comment]
@caseydavenport you are right, there is no need to explicitly configure this parameter and typically this can be left to the kernel and it will pick the appropriate source address.

The fact that this environment variable was added means that there are use cases where there is a need to control the source IP address picked. We have such a use case.

When passing this parameter as you mentioned, routes added by Felix are as expected, but summarized routes are not. In our case, as mentioned we have a floating IP address, when this IP address moves, we are seeing connection issues.

If this environment variable is used for the summarized routes also, then it will provide a consistent behavior.

**Comment by caseydavenport** [comment]
I'm not trying to say your scenario is invalid necessarily, rather I was providing context to the existing behavior, and the use-case which prompted the original implementation of FELIX_DEVICEROUTESOURCEADDRESS, which is not the same as your scenario. The presence of this config option doesn't imply anything about your situation, as it was meant to solve a different problem - selecting an IP address to use on device routes pointing at local veth interfaces that have no IP assigned to them. Overriding this config option to also select the source used for non-device-routes learned from other 

> What IP address is Calico autodetecting for it's BGP session? It should be visible on the Node resource in the annotations via kubectl get node <name> -o yaml

Could you provide this? I'd like to see if the VIP is being chosen by Calico, or a "real" address. To be honest, I am not sure BIRD (our BGP stack) supports setting the source address on the routes that it programs. We set the "source address" field in our configuration based on the auto-detected IP, which is why I am curious.

As an aside, in many VIP based setups that I have seen (regardless of Calico), the VIP has been applied to the host's `lo` interface in order to avoid it being accidentally picked up and treated as a "real" IP address of the host. Not sure if that would work in your case, but throwing it out there as a potential workaround while we dig into this.

**Comment by svallala** [comment]
@caseydavenport I understand this is a very specific use case. We are seeing this issue in only certain V6 setups where the Pod CIDR and the node subnets are overlapping. This is a very corner case, I was just curious to know why there is a difference in the routes added by Calico (Felix and Bird understood), and if there was a way to make this behavior consistent.

Calico auto-detection picks the right IP address, we enforce this by adding a static route forcing the node IP instead of floating IP.

Based on the Pod CIDR, node subnet, etc, the static route we added is not covering the case for Bird injected routes.

You are right about the VIP and configuring it in a way to make it least preferable over the real IP address of the host. We have found a way around this issue by setting the "preferred_lft" to 0 in keepalived.

Please feel free to close this issue.

FELIX_DEVICEROUTESOURCEADDRESSIPV6 not working can be ignored? 

FELIX_DEVICEROUTESOURCEADDRESSIP works fine for us though.

Thanks

**Comment by lwr20** [comment]
> FELIX_DEVICEROUTESOURCEADDRESSIPV6 not working can be ignored?
@Josh-Tigera thoughts on this?
