### ISSUE TITLE
Does Calico support Advanced Layer 2 within Metallb or Just BGP ?

### ISSUE THREAD

**Issue by deeco** [projectcalico/calico#6789]
## Expected Behavior

Can connect to external IP on Load Balancer

## Current Behavior

Unable to connect to external assigned Loadbalancer IP from outside cluster

Can connect to LoadBalancer IP from within the control plane and worker nodes , unable to connect from outside even in same vlan or lan

## Possible Solution
Network Policy but only see BGP as supported here https://projectcalico.docs.tigera.io/security/services-cluster-ips

## Steps to Reproduce (for bugs)

1. Apply MetalLB address pool
2. nginx ingress retrieves and assigns from pool
3. external ip set correctly from LAN pool
4. can connect via curl from any node in cluster 
5. cannot connect from any vm or host outside of cluster

## Context
Trying to connect to ingress in cluster from LAN in Vanilla k8s v1.23.5

## Your Environment

* Calico version: v3.22.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.23.5
* Operating System and version: rhel 8
* Link to your project (optional):

**Comment by song-jiang** [comment]
BGP should work but I'm not sure if Calico supports Metallb Layer 2 mode. @caseydavenport may know?

**Comment by caseydavenport** [comment]
It's not something that we have tested ourselves I'm afraid. I believe I have spoken to users who have done this, but I can't recall very clearly.

If you try it, please report back and let us know what you find.

**Comment by deeco** [comment]
will do , waiting on external network team to enable and provide subnets

**Comment by jonahbohlmann** [comment]
I can tell that for IPv4, I got it working with Layer2 config. For metallb, just make sure it has an L2Advertisement, next to IPAddressPool.
Not adding L2Advertisement will have the described result, that loadbalancer ip is not reachable from outside.

I just have problems with IPv6. Only every third request has success. I will report as soon, as I have a solution.

**Comment by zentavr** [comment]
@jonahbohlmann could you please share your configuration for MelalLB Layer2 and Calico? Do you have several interfaces in your cluster node? I have an issue https://github.com/metallb/metallb/issues/610#issuecomment-1418326496 and cannot make it work.

**Comment by zentavr** [comment]
@caseydavenport, @deeco, @song-jiang: had you a chance to test that?

**Comment by jonahbohlmann** [comment]
@zentavr this is my IPPool in Calico:

```
spec:
  allowedUses:
    - Workload
    - Tunnel
  blockSize: 24
  cidr: 10.233.64.0/18
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Always
```

For metallb IPAddressPool I have this:
```
spec:
  addresses:
    - 10.0.82.200-10.0.82.250
  autoAssign: true
  avoidBuggyIPs: false
```

And then my L2 Advertisement for Metallb:
```
spec:
  ipAddressPools:
    - metallb-pool-1

```

On production I just have one interface. But with vagrant for local tests I have two (one for nat, one for internal). The same configuration, I think nothing changed. Maybe kubespray does some magic around, I can't tell you right now.

**Comment by zentavr** [comment]
@jonahbohlmann if you have more than one interfaces, source base routing configuration is required as well.

**Comment by OLED1** [comment]
Is there currently any working solution? I am trying to get it running since days without any luck.

**Comment by zentavr** [comment]
@OLED1 check this issue:
https://github.com/metallb/metallb/issues/610

**Comment by rpersee** [comment]
So it's not supported then? @caseydavenport is it possible to provide a definitive answer? It looks like @jonahbohlmann is leveraging MetalLB Speaker to announce his L2 pool, not Calico.

**Comment by caseydavenport** [comment]
My answer hasn't changed much here - MetalLB in L2 mode is something I have heard many users have set up, but I do not have much experience with it myself and it's not a configuration that is part of our standard test matrix. Most Calico users in my experience opt for BGP advertisement instead, which is supported.

I'd say give it a try, and if it works that's great. If not, I'm happy to discuss and review any reasonable PRs to make the integration better. I don't have time to take that on myself, I'm afraid.

**Comment by BloodyIron** [comment]
I have Calico in eBPF mode + MetalLB in ARP Layer 2 mode (managing a single IP for inbound traffic, in my case) working very well right now! I had to add in kube-vip in Daemonset mode to do ARP Layer 2 of another IP for the HA kubernetes api-server serivce IP replacement for Calico to use as the Kubernetes API-Server interfacing, but that was actually pretty quick to set up. My validation thus-far shows this very reliable and working in every way that I can tell! Even retains the SourceIP aspect correctly ;)

**Comment by mvrk69** [comment]
Hi @BloodyIron i also have Calico in eBPF mode in a Fedora CoreOS kubernetes 1.31.1, but MetalLB in L2 doesn't seem to work, i see ARP requests, about the LB ip address, arriving at the kubernetes nodes, but never a reply.

My Calico setup:

helm repo add projectcalico https://docs.tigera.io/calico/charts

helm repo update

helm install calico projectcalico/tigera-operator --version ${CALICO_VERSION} --namespace tigera-operator --create-namespace --set installation.flexVolumePath="/etc/kubernetes/kubelet-plugins/volume/exec" --set installation.calicoNetwork.linuxDataplane="BPF" --set installation.calicoNetwork.ipPools[0].allowedUses[0]="Workload" --set installation.calicoNetwork.ipPools[0].allowedUses[1]="Tunnel" --set installation.calicoNetwork.ipPools[0].blockSize="26" --set installation.calicoNetwork.ipPools[0].cidr="${K8S_POD_SUBNET}" --set installation.calicoNetwork.ipPools[0].disableBGPExport="false" --set installation.calicoNetwork.ipPools[0].encapsulation="None" --set installation.calicoNetwork.ipPools[0].name="default-ipv4-ippool" --set installation.calicoNetwork.ipPools[0].natOutgoing="Enabled" --set installation.calicoNetwork.ipPools[0].nodeSelector="all()"

#Apply the ConfigMap to have calico talk directly to the API server
kubectl apply -f calico-kubernetes-services-endpoint.yaml

#Apply patch on felixconfiguration/default in order to enable DSR mode
calicoctl patch felixconfiguration default --patch='{"spec": {"bpfExternalServiceMode": "DSR"}}'

#Apply patch on felixconfiguration/default in order to disable IPIP
calicoctl patch felixconfiguration default --patch='{"spec": {"ipipEnabled": false}}'

#Apply patch on felixconfiguration/default in order to disable VXLAN
calicoctl patch felixconfiguration default --patch='{"spec": {"vxlanEnabled": false}}'

#Apply patch on daemonset/kube-proxy in order to disable kube-proxy
kubectl patch ds -n kube-system kube-proxy -p '{"spec":{"template":{"spec":{"nodeSelector":{"non-calico": "true"}}}}}'

---------------------

My MetalLB setup:

helm repo add metallb https://metallb.github.io/metallb

helm --namespace metallb-system install --create-namespace metallb metallb/metallb

kubectl apply -f metallb-pool.yaml

kubectl apply -f metallb-l2.yaml

#metallb-pool.yaml:
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.4-192.168.0.5

#metallb-l2.yaml:
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool


Do you have any idea what could be the issue?

**Comment by mvrk69** [comment]
Hi @BloodyIron, could you share in detail how you deployed Calico in eBPF mode and MetalLB L2? 
Did you removed kube-proxy as suggested in Calico docs or you added the patch so Felix would not interfere with kube-proxy?

Right now i'm having issue with MetalLB L2 not sending the ARP advertising the LB ip address, inside the cluster nodes i can contact the LB ip, but for example from my laptop (on same network as the kubernetes nodes) doesn't work.
