### ISSUE TITLE
Upgrading to Calico >= 3.23 does not automatically remove the nodeagent~uds/uds binary installed by previous Calico version

### ISSUE THREAD

**Issue by nickperry** [projectcalico/calico#6849]
## Expected Behavior
Calico could consider automatically removing the uds binary or provide a procedure to do it in the upgrade documentation.

## Current Behavior

When upgrading to >= 3.23 currently, the uds binary at `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds` will just be left in place and can continue to cause problems like https://github.com/projectcalico/calico/issues/5356.

## Possible Solution

Automatically remove the uds binary or provide a procedure to do it in the upgrade documentation.

## Steps to Reproduce (for bugs)

1. Upgrade to 3.23 or 3.24 from 3.22 or earlier.
2. SSH to a node and observe that `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds` still exists.

## Context

We had to manually clean up the binary from our nodes as it was causing https://github.com/projectcalico/calico/issues/5356 and making our control plane nodes run hot and send 600GB a day of log noise to Splunk.

## Your Environment

* 3.23.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.22
* Operating System and version: RHEL 7
* Link to your project (optional):

**Comment by lwr20** [comment]
pinging @Josh-Tigera

**Comment by caseydavenport** [comment]
The binary being left in place shouldn't cause problems if it's not being called. We should see why the binary was still being executed first. The most important bug here was the linked one - https://github.com/projectcalico/calico/issues/5356. Without this, the uds binary being present would be a non-issue.

Removing a binary from the host is awkward, especially in newer versions where that daemonset doesn't exist any more so we don't have a great hook to do so (@mgleung can correct me if I'm wrong here, though). @mgleung how might this look if we decided to do it?

**Comment by mgleung** [comment]
> Removing a binary from the host is awkward, especially in newer versions where that daemonset doesn't exist any more so we don't have a great hook to do so
This is the biggest reason we decided to leave the uds binary installed in place on the hosts. There is an increased complexity to removing the binary but also having the permissions to do so from a container that we decided to skip since the binary's existence shouldn't cause any issues.

If we were to decide to do this, we would need to tie the flex volume (requires the uds binary) configuration to Calico node in such a way where the operator would know that it would need to restart Calico node every time the flex volume configuration is changed in order to add the uds binary back. This would make this an operator-only feature though and there are a bunch of edge cases that can cause issues for non-operator installs.
