### ISSUE TITLE
Missing Tigera Operator v1.28.5 image in Calico v3.24.5 release

### ISSUE THREAD

**Issue by stevehipwell** [projectcalico/calico#6964]
## Expected Behavior

The Tigera Operator chart released as part of Calico `v3.24.5` should work.

## Current Behavior

The Tigera Operator chart released as part of Calico `v3.24.5` reference the non existent `quay.io/tigera/operator:v1.28.5` image.

## Possible Solution

Don't release Calico until the corresponding Tigera Operator version has been released.

## Steps to Reproduce (for bugs)

1. Attempt to use the Tigera Operator chart released as part of Calico `v3.24.5`
2. Image pull error

## Your Environment

* Calico version: v3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: n/a
* Link to your project (optional):

**Comment by stevehipwell** [comment]
CC @caseydavenport

**Comment by caseydavenport** [comment]
🤦 

@mgleung is doing that release.

**Comment by caseydavenport** [comment]
@mgleung this is probably the next part of our release process to tighten up. This is the order of operations in the release process today IIUC:

- Produce quay.io/calico/X images and publish them as well as the tag and helm chart.
- Produce OpenStack and Operator releases which package up the newly produced Calico version.
- Update the documentation on the live site and update the helm index to point at the new chart.

Obviously this has a problem of the helm chart being produced and attached to the GitHub release prior to the operator release existing, so there's a race condition.

I think something we've wanted to do for a long time is move the operator manifests and chart to the operator repository rather than the Calico repository, which I think would remove this problem.

**Comment by stevehipwell** [comment]
@caseydavenport I think adding the chart to the Tigera Operator repo would be the way forward. Especially if you were to publish the chart to GH Pages backed repository (and OCI). I'd be happy to contribute my Tigera Operator chart and automation as the starting point if you'd like?

By moving the chart you would have the decision of do you publish two charts, for Calico use the additional Tigera Operator CRDs cause issues, or do you make the operator controllers only run when required (e.g. Tigera mode) so all Cards can be present for Calico mode.

**Comment by stevehipwell** [comment]
@caseydavenport @mgleung FYI the Tigera Operator OCI image (`quay.io/tigera/operator:v1.28.5`) wasn't available 30 mins after the [v1.28.5 release](https://github.com/tigera/operator/releases/tag/v1.28.5). It's there now but this was the first time the image hasn't been available with the release.

**Comment by mgleung** [comment]
@stevehipwell sorry, there was a delay in the build process that caused the image to not get pushed on time. We're still improving things in terms of our release process so I'm hoping that this will be better moving forward.

**Comment by mgleung** [comment]
Closing this since this work is tracked elsewhere, but please shout out again if you witness the issue again.
