### ISSUE TITLE
documentation: no mention of disabling FELIX_AWSSRCDSTCHECK on EKS in upgrade docs for 3.22

### ISSUE THREAD

**Issue by emp2** [projectcalico/calico#6985]
Hello,

during a recent upgrade of Calico on EKS we noticed (after a few days of trying to hunt down the issue) that the upgrade documentation for version 3.22 has no mention of needing to disable FELIX_AWSSRCDSTCHECK on EKS clusters, while the installation instructions mention it.

## Expected Behavior
The upgrade instructions describe the same needed settings as the installation docs.

## Current Behavior
See (https://projectcalico.docs.tigera.io/archive/v3.22/maintenance/kubernetes-upgrade) compared to (https://projectcalico.docs.tigera.io/archive/v3.22/getting-started/kubernetes/managed-public-cloud/eks)

## Possible Solution
As I'm not aware of all places in the documentation where this might have to be fixed I submit this as an issue instead of a straight PR. But generally, I would expect the upgrade documentation to mention (or link to) steps needed to adapt to new features the same way the installation docs do.

**Comment by caseydavenport** [comment]
> has no mention of needing to disable FELIX_AWSSRCDSTCHECK on EKS clusters, while the installation instructions mention it.

Generally the upgrade instructions shouldn't need to duplicate all of the content in the installation guide, and assumes a functioning cluster prior to upgrade. Of course new requirements should go in the upgrade steps if an action is required on the user's part as part of that upgrade, but to my knowledge disabling AWS src/dst checks has been a requirement of running Calico on AWS since the project's inception ~6 years ago, so I don't think that's the case here.

@emp2 did you change any other config as part of your upgrade? What mode are you running Calico in on EKS? I'm curious if my understanding is wrong or an upgrade path that we haven't thought of.
