### ISSUE TITLE
Felix should have a respawn limit on Ubuntu

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calico#705]
When Felix fails, we restart it, but on Ubuntu there's no limit to the number of times.  This is misleading, because `service calico-felix status` reports that everything is fine at first glance.

We do have a limit on Red Hat (systemd) - 5 restarts inside 10 seconds is the limit.  This sounds sensible for Ubuntu too (it's enough time for Felix to start doing some real work).

**Comment by fasaxc** [comment]
I'm a bit wary of giving up when we're considering 100s of nodes.  That's a lot of operator intervention required to restart all those felixes once the problem is corrected.

Wish there was a more advanced algorithm here.  Upstart will give up completely after the 5 tries are up, I believe; it doesn't make 5 attempts every 10s.  Even if it had unlimited retries but rate-limited them, that would be better.

**Comment by matthewdupre** [comment]
I'm not totally happy here either (also 2 seconds per failure isn't always long enough if Felix does a lot of startup work before crashing).

It is possible to be more sophisticated - http://serverfault.com/questions/472955/how-to-make-upstart-back-off-rather-than-give-up suggests using a Post-Stop script to restart it, or (and this isn't something we could ship) using a cron job.  It's a bit fiddly though.
