### ISSUE TITLE
Typha. Watch error received from Upstream ListRoot="/calico/ipam/v2/host/" error=too old resource version

### ISSUE THREAD

**Issue by ivanovpavel1983** [projectcalico/calico#7126]
Hello.
Have the issue after upgrade from calico 3.16 to 3.23.3(migrated from manifest to tigera-operator)

![image](https://user-images.githubusercontent.com/5180093/209290400-451a4a06-2ec5-42ff-b5ab-bcdaaf8ce3e9.png)

And after that have info logs:

![image](https://user-images.githubusercontent.com/5180093/209290528-c514688e-67c2-4bfc-8df7-59155420b6bc.png)

In k8s api server there are errors:

![image](https://user-images.githubusercontent.com/5180093/209290602-3a3af99d-0b90-45b9-85fa-bdb889151275.png)

Maybe I need to remove manually some old resources?

**Comment by caseydavenport** [comment]
The "too old resource version" error usually indicates that Calico is falling behind on its watches against the Kubernetes API server. However, I'd expect it to attempt to resolve itself.

Would you be able to provide a full calico-typha, calico-node, and calico-apiserver log file so we can analyze them?

**Comment by ivanovpavel1983** [comment]
I'm attaching logs from one of environments.
The situation is repeated on all updated environments.
[TEST.zip](https://github.com/projectcalico/calico/files/10325653/TEST.zip)

**Comment by karr1gan** [comment]
same issue here

**Comment by tomastigera** [comment]
ping @caseydavenport

**Comment by caseydavenport** [comment]
@karr1gan was your issue also after switching from manifest to operator?

It's odd - I don't see any errors in the calico API server logs that would hint at why we're seeing timeouts in the main apiserver log. I wonder if there is some networking issue between the two? 

what does `kubectl get apiservice v3.projectcalico.org -o yaml` show? That might provide some hints.

**Comment by szywivon** [comment]
Not sure if this is related, but we also noticed those in logs after upgrading from 3.21.6 -> 3.24. Calico installation is managed by AKS, but we've already been using `tigera-operator as of 3.21.6. After upgrading to 3.23 we've started to notice those errors/infos:

> [INFO][8] watchercache.go 125: Watch error received from Upstream ListRoot="/calico/resources/v3/projectcalico.org/kubernetesnetworkpolicies" error=too old resource version: 289126932 (292086336)

Comparing two environments that both run different versions of Kubernets + Calico (1.24.9 + 3.24 and 1.22.15 + 3.21.6) those are only popping up in the 1.24.9 + 3.24 combination.

Looking at the [logs.txt](https://github.com/projectcalico/calico/files/11062709/logs.txt) it seems to be just doing resyncing of all resources (and then occasionally some others)

> what does kubectl get apiservice v3.projectcalico.org -o yaml show? That might provide some hints

```
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
Error from server (NotFound): apiservices.apiregistration.k8s.io "v3.projectcalico.org" not found
Error from server (NotFound): apiservices.apiregistration.k8s.io "show" not found
```

**Comment by thoot-235** [comment]
linux Rocky 9.1 kubernetes 1.26.2  calico v3.25.0 
[root@tddst0 ~]# kubectl logs --namespace=kube-system pod/calico-typha-68bb875fd9-ttw89

2023-04-14 07:32:55.750 [INFO][7] watchercache.go 125: Watch error received from Upstream ListRoot="/calico/ipam/v2/host/" error=too old resource version: 2446 (12932)
2023-04-14 07:32:56.247 [INFO][7] watchercache.go 181: Full resync is required ListRoot="/calico/ipam/v2/host/"

**Comment by mazdakn** [comment]
ping @caseydavenport

**Comment by linganmin** [comment]
> linux Rocky 9.1 kubernetes 1.26.2 calico v3.25.0 [root@tddst0 ~]# kubectl logs --namespace=kube-system pod/calico-typha-68bb875fd9-ttw89
> 
> 2023-04-14 07:32:55.750 [INFO][7] watchercache.go 125: Watch error received from Upstream ListRoot="/calico/ipam/v2/host/" error=too old resource version: 2446 (12932) 2023-04-14 07:32:56.247 [INFO][7] watchercache.go 181: Full resync is required ListRoot="/calico/ipam/v2/host/"

same issue

**Comment by caseydavenport** [comment]
This log isn't necessarily a problem. The log message occurs when the watch revision is too old for the API server. This can happen in a number of normal circumstances. For example, when one or more APIs that Calico isn't watching (i.e., has a lot of changes) and another API that Calico is watching sees no changes. This results in the revision number used by Kubernetes to increment, but the watcher Calico is using hasn't received an update to indicate as much.

I would say that if you see this message, and it's:

- Not causing any noticeable degradation in service
- Not occurring very frequently (e.g., on loop every few seconds).

It is likely normal behavior and you have nothing to worry about (hence the log is at INFO level).

However, if you see this message occurring repeatedly on a tight loop. e.g., more than once every few minutes, it is likely either a misconfiguration with your API server or etcd cluster (might not be resourced or configured for the number of events that it needs to handle). Or there is a bug in Calico not refreshing its cached revision number (which is possible, but I believe we have this area pretty well covered in testing). Or there is something else going on - like a rogue client or two that are generating a LOT of requests when they shouldn't be. 

The fact that his is occurring pretty much exclusively for the `/calico/ipam/v2/host/` tree suggests to me that this is simply a matter of the watch getting out of date due to lack of activity, and it refreshing itself, which is normal and healthy behavior. The IPAM host tree stores IPAM block affinities, which in most cases don't see very many updates at steady state, as it is tied to the coming and going of nodes in the cluster, making it a relatively quiet API.

Hopefully that helps explain this one a bit better!

**Comment by paulcostinean** [comment]
thanks for the explanation @caseydavenport
