### ISSUE TITLE
Calico not publishing routes from bird till 4 mins, when multiple nodes are restarted

### ISSUE THREAD

**Issue by royanirban76** [projectcalico/calico#7144]
The issue is seen if we reboot two nodes in the cluster. Nodes normally boot up in 4 - 5 mins. If we time the reboots of two nodes in  such a way that there is around 3+ mins of difference between them, we observe that node1 (first to be booted) comes up and by the time it becomes ready, node2 (second to be booted) is still around 4+ mins away from becoming ready. When I say ready, I mean "Ready" state in the k8s cluster.
The issue is that in node1 the routes from bird are not getting published till 4 mins or node2 comes up, which ever is first.
From the logs we see the following two line from bird
_bird: Graceful restart started
bird: Graceful restart done_
and the routes are getting published only after that.
Setting the graceful restart time to 60s through the "nodeMeshMaxRestartTime" and restarting the PODs also does not help.

## Expected Behavior
Setting the graceful restart time should have reduced the time to wait.

## Current Behavior
The wait time is 240s.

## Steps to Reproduce (for bugs)

Reboot two nodes as described above.

## Your Environment

* Calico version  3.23.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):  K8s 1.25.0
* Operating System and version:  SLES 15 SP4
* Link to your project (optional):

**Comment by royanirban76** [comment]
It seems we can change the described behavior by changing the value of "DEFAULT_GR_WAIT" in BIRD's code.
Is there any way currently to parameterize this timer value during the k8s cluster deployment/upgrade?

**Comment by royanirban76** [comment]
Can someone comment on these queries:
1. Why is this time kept at 240 seconds.
2. What implications could be there if it is reduced to, say 90 seconds.

**Comment by lwr20** [comment]
pinging @nelljerram who knows the most about BGP settings and the likely implications of changing DEFAULT_GR_WAIT

**Comment by nelljerram** [comment]
Not sure I'm following.  You said you initiate boot of node2 3m after initiating boot of node1.  Therefore, when node1 is ready, we expect at least 3m before node2 is ready.  And in practice I think you're saying it's 4m before node2 is ready.  So there is an unexpected additional latency of 1m.  Is that correct?

**Comment by royanirban76** [comment]
Hi @nelljerram,
     The issue is such,
     Node1 is booted. It will take around 4+ mins to boot. Once it is booted I wait for 3 mins 10 - 15 secs and boot Node2.
     Now Node1 comes up is another 50 or less secs, Node2 is still booting and expected to come up in the next 3+ mins.
     I login to Node1 and check for the routes.
     There will be no routes from BIRD with the kernel till Node2 does not comes up or if Node2 takes more than 4 mins (this is not easy to time) then I see the routes getting published for the other nodes in the cluster, in Node1.
     Basically, in Node1 the routes are getting published,
     1. If Node2 comes up.
     2. Or if Node2 takes more that 4 mins then at the 4 min mark (after Node1 is up) the routes are published without Node2.

I changed the DEFAULT_GR_WAIT from 240 to 90 and after that Node1 will always publish routes after 90s of being up without Node2.
Now, we would like that wait time to be reduced. Hence those queries,
1. Why is this time kept at 240 seconds?
2. What are the implications if it is reduced to, say 90 seconds or less?
3. How low can that be made, I suppose the cluster size will play a role on that among other things?
4. Can this value be configured when calico-node comes up?

**Comment by royanirban76** [comment]
Hi @nelljerram,
   Yes, I am talking about the pod block routes.
   My cluster has 10 nodes. I am booting 2 out of those 10 as described earlier.
   When Node1 comes up, the expectations is that the routes to the other 8 nodes are published as quickly as possible in Node1, don't wait for 4 mins. Node1 is waiting for 4 mins or "Node2 is up" which ever is first to publish any routes. There are times when Node2 is taking more time to come up. So we are facing a traffic drop scenario due to this 4 mins and want to minimize it.
   When Node2 comes up finally its routes also shows up fine and all routes on all nodes are good.

**Comment by nelljerram** [comment]
I'm still not clear why there are initially _any_ expected routes from Node2.  Were pods already scheduled to Node2 before the reboot?  Or is there some other process that schedules pods to Node2 as soon as it boots up?

**Comment by chandanD4** [comment]
@nelljerram  Pods were already scheduled to node2 before the reboot , node2 was already part of bgp mesh before it went for the reboot.

**Comment by royanirban76** [comment]
Some more clarification, if GR_WAIT timeout happens first in Node1, that is Node2 is still not up, I see Node1's routing table getting the rest of the pod blocks to the other nodes, Node3, 4, 5 ... excluding Node2 obviously.
As Node2 later come up, it also joins.

**Comment by coutinhop** [comment]
Granted, I haven't looked at bird source code, but from their docs it might seem like this is expected behavior:

https://bird.network.cz/?get_doc&v=16&f=prog-5.html#ss5.3

> BGP protocol implements graceful restart in both restarting (local restart) and receiving (neighbor restart) roles. The first is handled mostly by the graceful restart code in the nest, BGP protocol just handles capabilities, sets gr_wait and locks graceful restart until end-of-RIB mark is received.

@royanirban76 or @nelljerram please correct if my understanding is wrong, but wouldn't this mean that while Node1 is in its graceful restart (GR), it'll wait for either: an end-of-RIB (EOR) from all peers OR a GR timeout? In that case, as Node2 reboots during Node1's GR, Node1 will never get an EOR from Node2 (only would after Node2 finishes booting), and thus what happens is it waits for a GR timeout... (I'm not sure on what exactly the phrasing "locks graceful restart" on bird docs means)

Implications of a shorter GR timeout are that you might have tables churning more than they would with a longer timeout in the scenario of only one Node rebooting at a time, I think...

**Comment by nelljerram** [comment]
Thanks @coutinhop ; yes, I think that's exactly right.  I haven't checked, but I guess this behaviour is also specified in the relevant RFCs, because:

- the objective of GR is to avoid churning the local routing table unnecessarily when neighbours are restarting
- the same prefix could be advertised, perhaps with different weights, from multiple neighbours
- to ensure that it has the best possible information for deciding what ought to be in its local routing table, a BGP speaker really needs to get EOR from all of its peers (even if it has prefixes from some of them at an earlier time).

With that understanding, I think we can only advise that it would be better to avoid the pattern of node restart as originally described.

**Comment by royanirban76** [comment]
Hi @coutinhop, @nelljerram,
   @coutinhop, you were correct in understanding the scenario. Thanks for the information, we were looking for an explanation on the choice of that 4 min value and implications in changing it.
