### ISSUE TITLE
High CVE in Calico 3.24.5

### ISSUE THREAD

**Issue by ssoriche** [projectcalico/calico#7161]
Our vulnerability scanner has discovered that the golang.org/x/net version used in node, typha and kube-controller has this high CVE CVE-2022-27664.

The scanner also reports that github.com/emicklei/go-restful has the critical CVE-2022-1996, I found this issue already in the repository which may exempt that https://github.com/projectcalico/calico/issues/6733

Will these CVEs be addressed in a patch release soon?

Thank you

**Comment by Behnam-Shobiri** [comment]
@ssoriche Regarding CVE-2022-27664 the golang version used for the latest calico (3.24.5) is 1.18.7 (https://github.com/projectcalico/calico/blob/v3.24.5/metadata.mk#L6); therefore, the mentioned CVE is already fixed in the latest release. If the scanner you are using picks this CVE, it should be FP. 
We try to include the latest golang build in our releases (e.g., our next release will use 1.18.9) so it's always a good idea to use the latest version. 
Regarding CVE-2022-1996, as I mentioned in the other issue that you point out, this is an indirect dependency of K8s which they are not affected by.
