### ISSUE TITLE
Felix doesn't immediately apply config changes to etcd

### ISSUE THREAD

**Issue by spikecurtis** [projectcalico/calico#725]
Modifying configuration settings in the `/calico/vX/host/<host>/config/` directory doesn't trigger Felix to react to the change.  You have to manually bounce the Felix process.

Felix should immediately apply config changes made to etcd.

**Comment by fasaxc** [comment]
@spikecurtis It'd be nice to have but the steer I was getting a while back was that it wasn't MVP.  We could fairly easily do something blunt such as getting felix to restart if it detects a config change.  Risk is that all your felixes end up in a restart loop if something goes wrong.

Any particular use-case you had in mind?  Tuning logging on the fly is what I'd really like.

**Comment by spikecurtis** [comment]
My view is that this is a manageability issue.

Administrators are going to want to fiddle with all the little Felix options and it's going to drive people nuts that you have to restart to pick up config changes.  It's an extremely common complaint to support for other products I've worked on.

I think everyone has learned to live with the idea that processes don't pick up changes to config files without a kick, but the expectation is that if you change a config database, the change happens immediately.  It surprised me that Felix didn't pick up the change.

**Comment by fasaxc** [comment]
Some design thoughts on this:

* Logging and the like are easy to make dynamic.
* Some things are not straightforward:
  * the interface prefix is assumed to be static, we program it once and then never touch it again.
  * various timers that are configurable, such as the periodic resync timer, can't easily be changed because we abort the resync loop if resync is disabled.
  * etcd address awkward to change
  * felix hostname awkward to change, we discard a lot of data that we read if it doesn't match our hostname

Considering all that, I err towards restarting felix when any of the hard-to-change pieces change.  That could be as simple as committing suicide and being restarted or we could try to re-exec the process to avoid bothering the init daemon.

**Comment by spikecurtis** [comment]
From a requirements standpoint, I'd say

 - it MUST happen automatically with no extra kick from the user
 - it MUST be clear from the logs what is happening (e.g. if restarting because of a config change, rather than for some other reason) 
 - it SHOULD minimize disruption as much as possible

The actual implementations of different kinds of changes are going to have trade offs in terms of code complexity, amount of disruption, etc.

**Comment by spikecurtis** [comment]
@fasaxc there's a specific use case for this that we're now running up against: IP-in-IP support.

We'd like to allow users to turn this on with a `calicoctl` command.  But that doesn't work because it currently requires restarting every Felix in the cluster manually.

**Comment by fasaxc** [comment]
@spikecurtis Pull requests welcome :-P

Seriously though, what's your timescale?  I don't think we can fit it in this week but we can probably do it next sprint.

**Comment by spikecurtis** [comment]
Next sprint would be grand.

**Comment by eepyaich** [comment]
I believe we now have a solution for this under #749.  Presumably this issue can be closed @fasaxc @spikecurtis ?

**Comment by spikecurtis** [comment]
Works for me.
