### ISSUE TITLE
calico pod failed when OPA gatekeeper 3.7.1v installed on the cluster.  

### ISSUE THREAD

**Issue by mekalam** [projectcalico/calico#7286]
Installed gatekeepern3.7.1 on 1.20 v of Kubernetes cluster and calico pods are failing to restart

## Expected Behavior

calico pods should run even when OPA gatekeeper running in the cluster

## Current Behavior

but currently the pod fails with the logs like "[ERROR] [696] felix/daemon.go couldn't read server version from server error=unknown panic: runtime error: invalid memory address or nil pointer dereference

## Steps to Reproduce (for bugs)

1. install calico 3.20 version
2. install OPA gatekeeper 3.7.1
3. delete Calico pods 
4. delete OPA gatekeeper constraints and validating, mutating webhooks 

## Your Environment

* Calico version: version 3.20
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: ubuntu 20.04
* Link to your project (optional):

**Comment by mgleung** [comment]
@mekalam thanks for raising this. Is it possible to get the rest of the calico-node logs in order to get more context for the error? I also think that the error might have code line numbers associated with it for invalid memory addresses. Would you happen to have that? It might help us with debugging what exactly is going on.

**Comment by sridhartigera** [comment]
@mekalam Can you please get the logs?
