### ISSUE TITLE
CVEs found in Node v3.25.0

### ISSUE THREAD

**Issue by splashcd** [projectcalico/calico#7431]
A PrismaCloud scan has identified the following vulnerabilities in _calico/node:v3.25.0_

Please review and provide commentary if these reported vulnerabilities indeed affect users of _node:v3.25.0_, and if so, when the vulnerabilities expect to be resolved.

[CVE-2020-8558](https://nvd.nist.gov/vuln/detail/CVE-2020-8558): (High) The Kubelet and kube-proxy components in versions 1.1.0-1.16.10, 1.17.0-1.17.6, and 1.18.0-1.18.3 were found to contain a security issue which allows adjacent hosts to reach TCP and UDP services bound to 127.0.0.1 running on the node or in the node\'s network namespace. Such a service is generally thought to be reachable only by other processes on the same host, but due to this defeect, could be reachable by other hosts on the same LAN as the node, or by containers running on the same node as the service. (k8s.io/kubernetes fixed in: 1.16.11, 1.17.7, 1.18.4)

[CVE-2020-8565](https://nvd.nist.gov/vuln/detail/CVE-2020-8565): (Moderate) In Kubernetes, if the logging level is set to at least 9, authorization and bearer tokens will be written to log files. This can occur both in API server logs and client tool output like kubectl. This affects <= v1.19.3, <= v1.18.10, <= v1.17.13, < v1.20.0-alpha2. (k8s.io/kubernetes fixed in: 1.20.0-alpha.2)

[CVE-2020-8564](https://nvd.nist.gov/vuln/detail/CVE-2020-8564): (Moderate) In Kubernetes clusters using a logging level of at least 4, processing a malformed docker config file will result in the contents of the docker config file being leaked, which can include pull secrets or other registry credentials. This affects < v1.19.3, < v1.18.10, < v1.17.13. (k8s.io/kubernetes fixed in: 1.20.0-alpha.1)

[CVE-2015-5305](https://nvd.nist.gov/vuln/detail/CVE-2015-5305): (Moderate) Directory traversal vulnerability in Kubernetes, as used in Red Hat OpenShift Enterprise 3.0, allows attackers to write to arbitrary files via a crafted object type name, which is not properly handled before passing it to etcd. (k8s.io/kubernetes fixed in: 1.1.1)

**Comment by Behnam-Shobiri** [comment]
Thank you for sharing the result with us. 

I checked the CVEs and they are all False Positives (FPs). 
Calico 3.25.0 is based on K8s 1.24.0 libraries that include the fix for all the mentioned CVEs. I think the PrismaCloud scanner cannot detect the replace block in go.mod file (the k8s version in the required block is [here](https://github.com/projectcalico/calico/blob/v3.25.0/go.mod#L94) and it was replaced with 1.24.0 in [here](https://github.com/projectcalico/calico/blob/v3.25.0/go.mod#L326); therefore, 1.24.0 will be used). This might be something that you can bring up with PrismaCloud and they can work on fixing the bug. 

Since the version mentioned in the required block jas changed in the 3.25 branch, I think the FP CVE will no longer show in 3.25.1. But, as I mentioned, the CVEs are FPs and do not have any effect on the calico/node.

**Comment by mgleung** [comment]
Closing this issue since it seems resolved. If it is not, please shout out and we'll reopen this.
