### ISSUE TITLE
dnsmasq not restarted when upgrading on RHEL7

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#759]
I have a RHEL 7 system running openstack Kilo with calico.  I can create VMs and everything is happy.

I update everything with "yum update".  Following this, VMs are no longer able to DHCP.

@matthewdupre took a look and said: "It looks like something very strange has happened to dnsmasq's process.  In particular, /proc/<dnsmasq PID>/exe looks like this: lrwxrwxrwx. 1 root root 0 Jun 3 16:42 exe -> /usr/sbin/dnsmasq;557576d7 (deleted).  And the last bit is confusing rootwrap"

Looking at my terminal logs, dnsmasq was updated, but the dnsmasq process on my machine hasn't been restarted recently.  Manually restarting dnsmasq on my compute hosts fixes the problem.

**Comment by matthewdupre** [comment]
Workaround: `pkill dnsmasq` after any update to the dnsmasq packages.

A few notes:

- Probably not RHEL7 specific.
- Perhaps worth an upstream fix to rootwrap?
- Tricky to resolve without resorting to docs fixes (i.e. do the workaround), because dnsmasq doesn't run itself (DHCP agent runs it), so it can't really restart itself when it's yum updated (or probably apt-get upgraded).

**Comment by matthewdupre** [comment]
I've added a note to the upgrade procedure to warn people to kill dnsmasq if it gets upgraded.  For now I'm going to close this, but we should consider enhancing oslo-rootwrap to deal with this silently - @neiljerram can you take an action to consider this please?
