### ISSUE TITLE
calico does not release free blocks assigned to node

### ISSUE THREAD

**Issue by mchtech** [projectcalico/calico#7987]
according to https://github.com/projectcalico/calico/blob/v3.26.1/kube-controllers/pkg/controllers/node/ipam.go#L648-L653 , 
calico will not release free blocks when `numAddressesAvailableOnNode < 3`

## Expected Behavior

user/calico can release free blocks even if `numAddressesAvailableOnNode < 3`

## Current Behavior

calico will not release free blocks when `numAddressesAvailableOnNode < 3`

## Possible Solution

1. make `numAddressesAvailableOnNode < 3` configurable.
2. provide steps to release free blocks manually.

## Context

We run 1~2 apps on a node, so we set ip pool `blockSize = 31` to mininize bgp route count that exported to idc. If calico do not release unused block, some nodes will be assigned two /31 blocks "forever". It siginificantly reduced the utilization of ippool.

## Your Environment

* Calico version: 3.26.1 with etcd datastore
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.26.7
* Operating System and version: oracle linux 8.8
* Link to your project (optional):

**Comment by mazdakn** [comment]
@caseydavenport is it a good idea to make this number configurable?

**Comment by mchtech** [comment]
> > If calico do not release unused block, some nodes will be assigned two /31 blocks "forever". It siginificantly reduced the utilization of ippool.
> 
> Only if you have IPAM_STRICT_AFFINITY set. Otherwise the ip-borrowing behaviour will kick in when addresses are almost exhausted and borrow addresses from blocks allocated to other nodes.
> 
> Is this _actually_ causing you a problem? Can you describe that problem please? I think that even with blockSize = 31, Calico should be able to utilise ALL the IPs in the pool (because of "ip borrowing").

## problem: 
`calicoctl ipam show` output shows that there are lots of free addresses, but cni reports:
`
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "d41dc562be6437177983bf4dbb5c73bbbe4f86b1bc61c56dcff97a7b65bf8fc3": plugin type="calico" failed (add): failed to request IPv4 addresses: Assigned 0 out of 1 requested IPv4 addresses; No more free affine blocks and strict affinity enabled
`

I must add more ippools to solve this problem, but the utilization of ip is low. (max 50%, if calico does not reclaim /31 free blocks)

My K8s clusters use calico BGP (without encapsulation) to advertisement pod route. `IPAM_STRICT_AFFINITY` cannot be disabled in my cluster, otherwise, the pod cannot connect to the borrowed ip. 

```bash
when `ip bowrrowing` is enabled:

node A (
blackhole 10.0.0.128/31 proto bird
10.0.0.128 dev calixxxx scope link # <-- pod a
)

node B (
10.0.0.129 dev caliyyy  scope link # <-- pod b (ip borrowing)
)

pod a cannot connect to pod b (blackhole route)
```

**Comment by lwr20** [comment]
> IPAM_STRICT_AFFINITY cannot be disabled in my cluster, otherwise, the pod cannot connect to the borrowed ip.

The nodes should advertise a /32 route for borrowed IPs over BGP to the rest of the cluster, and routing should work due to the "most specific route wins" rule of routing, and the borrowed IP has a /32 route which is more specific than the black hole /31 route.

In your output above, node A seems to be missing the /32 route to pod b.  Are you sure your BGP peerings are up and happy between the nodes?

**Comment by mchtech** [comment]
> > IPAM_STRICT_AFFINITY cannot be disabled in my cluster, otherwise, the pod cannot connect to the borrowed ip.
> 
> The nodes should advertise a /32 route for borrowed IPs over BGP to the rest of the cluster, and routing should work due to the "most specific route wins" rule of routing, and the borrowed IP has a /32 route which is more specific than the black hole /31 route.
> 
> In your output above, node A seems to be missing the /32 route to pod b. Are you sure your BGP peerings are up and happy between the nodes?

## 

we use `The Downward Default model` to setup calico bgp: 
Every node advertises pod routes to TOR/BGP-control-plane.
TOR/BGP-control-plane does not publish any routes to node.
All traffic beyond this node will be sent to/received from node default gw.

As shown in the following figure:
`node-1` has route `10.142.159.0/24` and pod `10.142.159.0`.
`node-2` has pod `10.142.159.2` (disable `IPAM_STRICT_AFFINITY `: borrowed from `node-1`).

TOR/BGP-control-plane will not advertise `10.142.159.2/32 via 10.182.15.1` route to `node-1`, when network model is `The Downward Default`.

## 
<img width="1077" alt="image" src="https://github.com/projectcalico/calico/assets/8463208/78a55c28-078b-4d5c-88f8-53a28fd96644">

**Comment by mchtech** [comment]
> @mchtech how are pod's routes advertised in the cluster? Do you use an overlay?

I don't use an overlay. Pod's routes are directly advertised to IDC TOR (or SDN BGP control plane)

**Comment by mchtech** [comment]
@lwr20 refer to this issue: https://github.com/projectcalico/calico/issues/3246, I have validated that `borrowed-ip/32 via node-default-gw` route will be generated when `nodeToNodeMeshEnabled = true`.

Our IDC network env and calico deploy method and my problem like this  https://github.com/projectcalico/calico/issues/3246#issuecomment-687292396_

However, our largest cluster has about 3000 nodes. Open `nodeToNodeMeshEnabled` leads to:
1. All pod routes in this cluster will be spreaded to 3000 nodes.
2. 3000+ routes are applied to every node. Route process related cpu sys% softirq% increases.



Open `nodeToNodeMeshEnabled` or deploy `dedicated route reflector` or use `ip borrowing` make the problem more complex.

If calico can release free blocks of small node (with `strictaffinity` enabled), the `unused rate of ippool` and `route count of IDC router/switch` and `route count of every node` could be minimized.

**Comment by lwr20** [comment]
OK, thank you for explaining the problem in enough detail to explain why you want the change.  

So @caseydavenport, with the above context, do you agree this needs to be changed or made configurable?

**Comment by mazdakn** [comment]
@mchtech yes, enabling BGP mesh in a large cluster is problematic, but there are two things you can do instead:
- Set some nodes as RR, and peer all node with those. This is a common setup in large clusters: https://docs.tigera.io/calico-enterprise/latest/networking/configuring/bgp#route-reflectors
- Enable an overlay like `VXLAN` (not IPIP since it needs internal BGP to be ebabled). Felix program workload routes itself on all nodes.

**Comment by caseydavenport** [comment]
I can certainly believe our block release heuristic needs to be changed. I'd rather not make it configurable - it's a bit too low-level for _most_ (but obviously not all) users. I'd prefer if we just made our garbage collection smarter.

Here's a scenario that I think should approximate what you're seeing:

Assuming a block size of /31, and a node with 15 pods running:

- Should see 8 IPAM blocks assigned to the node to satisfy the request (with room for 1 more IP)
- Scale to 14 pods - there is now one unused IPAM block (but only two free addresses)
- Scale to 13 pods - there is now one unused IPAM block (and three free addresses)
- Scale to 12 pods - there are now two unused IPAM blocks (and 4 free addresses)
- Scale to 10 pods - there are now three unused IPAM blocks (and 6 free addresses)

It's only at this point that the GC will decide there are enough free addresses to release a block, and I would expect it to release one.

Does that sound like an accurate representation? I think it essentially means that the fewer pods you run on a node, the more likely it is you are not using IP space efficiently, since the threshold (3) becomes a larger and larger percentage of the pods that are actually running.

**Comment by mchtech** [comment]
> I think it essentially means that the fewer pods you run on a node, the more likely it is you are not using IP space efficiently, since the threshold (3) becomes a larger and larger percentage of the pods that are actually running.

Yes, what you described above   closely approximates my scenario.

**Comment by caseydavenport** [comment]
There's another general-case complication here, which is that not all blocks are used equally. It's very possible that there will be many addresses that seem to be available for use on a node, but not that are actually available to use because of Calico's IP pool selection capabilities. The GC controller doesn't take this into account today (and I don't really know how it could reasonably do so).

Perhaps it just makes sense to switch this to a time-based metric as well. If a block is empty and has been for X amount of time, we can be reasonably sure it's safe to release it. In that case, we'd be trading speed-of-block-release for an ultimately better IP space efficiency.

**Comment by mchtech** [comment]
Both releasing free blocks `according to idle time` or `by new/configurable threshold` are acceptable to my env.
Before new method/policy is available, how can I reclaim known free blocks (manually)?

**Comment by caseydavenport** [comment]
If the block is known to be empty, you can free it by deleting both the block itself as well as its block affinity (`kubectl get ipamblocks` and `kubectl get blockaffinities`)

Just make sure that you don't delete a block that has IP addresses in it. Ideally, you would freeze IP allocations whenever making these changes because it's possible that you can accidentally delete a block that was previously free, but has since had an IP address allocated within it.

You can do this either by disabling the IP pool containing that block, or by using `calicoctl datastore migrate lock|unlock` - note that the latter will prevent new pods from starting cluster-wide, because new IP allocation requests will be rejected.

**Comment by mchtech** [comment]
Are there any plans to fix/improve this? Releasing free blocks according to `idle time` or `configurable threshold`.

**Comment by caseydavenport** [comment]
I'd like to see this fixed, but haven't had time to do so myself yet and I am not sure when I will if I'm being honest. I think my preference would be an idle-time based mechanism. It's an easy knob to control (idle release time) and a pretty simple heuristic to implement. It also seems like the most generally applicable method of doing this, whereas a configurable threshold seems more complicated to configure properly.

**Comment by mchtech** [comment]
It seems that `blockReleaseTracker` (func [markEmpty](https://github.com/projectcalico/calico/blob/master/kube-controllers/pkg/controllers/node/ipam_allocation.go#L41-L56))  has implemented the idle-time based mechanism. 

deleting these codes can fix this issue: https://github.com/projectcalico/calico/blob/v3.26.1/kube-controllers/pkg/controllers/node/ipam.go#L633-L653

**Comment by mchtech** [comment]
It seems that `blockReleaseTracker` (func [markEmpty](https://github.com/projectcalico/calico/blob/master/kube-controllers/pkg/controllers/node/ipam_allocation.go#L41-L56))  has implemented the idle-time based mechanism. 

deleting these codes can fix this issue?
 https://github.com/projectcalico/calico/blob/v3.26.1/kube-controllers/pkg/controllers/node/ipam.go#L633-L653

**Comment by caseydavenport** [comment]
Yeah, that's true - there is already an idle-time in-use. The heuristic that is problematic is just that we only consider a block empty if it has fewer than three addresses. I will think about this a little bit more, it might be fine to just remove that section as you suggested.
