### ISSUE TITLE
tigera-operator eviction loop when the node which runs it has no free disk space available on the root filesystem

### ISSUE THREAD

**Issue by nkichukov** [projectcalico/calico#8110]
We are using the helm charts to deploy tigera-operator into its own namespace on onprem kubernetes clusters. When the node that is running the tigera-operator pod gets its filesystem full, the scheduler tries to evict the pod, but as it seems disk-pressure is something that is being tolerated by the default install, so it keeps being rescheduled and evicted to and from the same node, causing a loop.

The versions we have tried and behave in the same way are: v3.25.1 and v3.25.2.
It has been happening on kubernetes versions 1.24.8 through 1.28.1.

## Expected Behavior
By default, when the pod is scheduled on a node that has a taint causing the scheduler to evict it, it should not reschedule it on the same node, but try to put it on a different node.

## Current Behavior
The tigera-operator pod is evicted and rescheduled on the same node, which is having 100% full filesystem and is tainted with disk-pressure.

## Possible Solution
https://github.com/projectcalico/calico/blob/master/charts/tigera-operator/values.yaml#L35-L40
instead of using the defaults from the values.yaml above, overwrite the values to something which will not tolerate disk-pressure.

## Steps to Reproduce (for bugs)
1. Deploy calico's tigera-operator through the helm charts
2. Identify the node which is running the pod
3. Fill-up the root filesystem on this node, ie: `dd if=/dev/zero of=/full bs=8M`
4. Observe how the node is tainted and tigera-operator pod is evicted but rescheduled to the same node, in a loop

## Context
We were running various stress tests(in this case disk-pressure) to our kubernetes clusters when we observed the issue with tigera-operator eviction loop.

## Your Environment
* Calico version 1.25.1 and 1.25.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.24 through 1.28
* Operating System and version: Flatcar Container Linux by Kinvolk 3510.2.7 (Oklo)
* Link to your project (optional): n/a

**Comment by mgleung** [comment]
Hi @nkichukov , I believe that the behavior that we are hoping for the operator is that since the operator itself is not necessary for your cluster to keep working (once it has installed the relevant components), that in times of disk pressure, it should be one of the pods that does get evicted from the node in order to keep the system up and running. That being said, it is a bit problematic that it appears to be rescheduling to the same node.

Could you check if you have anything specific set for the node selector in your helm chart? https://github.com/projectcalico/calico/blob/master/charts/tigera-operator/values.yaml#L42-L44 I would have expected with our default values that different nodes should have been selected.

**Comment by nkichukov** [comment]
Hello @mgleung 

We have been using the default values from the chart for tolerations and nodeSelector.

**Comment by caseydavenport** [comment]
While it seems reasonable to exclude disk pressure from the default values, that would require us to list out all potential tolerations that might be needed.

This is configurable in the helm chart, so I'd suggest configuring this for your environment using values.yaml. That said, it's probably worth figuring out why your node is under disk pressure, as that will likely have other consequences.

I don't think this warrants a change in our default values, given it's configurable and disk pressure is a cluster error scenario.
