### ISSUE TITLE
Upgrade Calico Node and Controller Golang and net package to fix CVE-2023-44487

### ISSUE THREAD

**Issue by mitchellmaler** [projectcalico/calico#8169]
Calico v3.26.3 is using the net package that has CVE-2023-44487. This requires upgrading Golang and the net package to resolve the CVE. 
![Screenshot 2023-10-27 at 10 20 38 AM](https://github.com/projectcalico/calico/assets/4107699/56986c5d-7a64-4a45-af3f-ff665aeaa62e)
![Screenshot 2023-10-27 at 10 23 49 AM](https://github.com/projectcalico/calico/assets/4107699/8d17a0fc-c8f1-41c0-b44f-1835d5d56be7)

**Comment by mitchellmaler** [comment]
Same issue with Typha
![Screenshot 2023-10-27 at 10 33 39 AM](https://github.com/projectcalico/calico/assets/4107699/5ee93a90-374e-43f3-ae0f-759c95d8de87)

**Comment by mgleung** [comment]
pinging @Behnam-Shobiri

**Comment by Behnam-Shobiri** [comment]
Thanks for reporting the CVEs @mitchellmaler. 
The CVEs were fixed in the 3.26 branch ~2 weeks ago (when CVE was discovered; see https://github.com/projectcalico/calico/pull/8129). The next patch version of 3.26 will use the new golang/x/net library.
Unfortunately, the CVE was discovered after the release of 3.26.3 which made it not possible to include it (at the time of release 3.26.3 had only 1 high CVE which had no impact on our product).

**Comment by Behnam-Shobiri** [comment]
@mitchellmaler 3.26.4 was released and CVEs have been fixed. Please update to the latest version to get the fix. 
This release also updates the golang to the latest version (released this Nov) as well as a few other updates.
