### ISSUE TITLE
What is the refresh period for calico forwarding rules

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#8210]
## Current Behavior

I checked the routes of Calico and found that some of the routes' podips have already disappeared, but the route information has not been refreshed
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by mgleung** [comment]
Hi @smallemployees , I think the answer you are looking for is in your [Felix configuration](https://docs.tigera.io/calico/latest/reference/resources/felixconfig). The field that defines it should be `iptablesRefreshInterval`. There are also ways to force it to manually refresh which aren't very pretty. There is a discussion about forcing a manual refresh here: https://github.com/projectcalico/calico/issues/1292

**Comment by matthewdupre** [comment]
The IptablesRefreshInterval actually isn't relevant here - that field controls rewrites of iptables rules that were already programmed in case some other application removed them.

A possible source of confusion here is that routes to remote IPAM blocks that have been assigned to a node won't be removed.  If a /32 (or /128 for IPv6) route is persisting a long time after a pod is removed then that indicates a problem, but /26 (or /122 or other prefix length if the block size has been changed) routes are safe to stick around because the host can still use that block.

**Comment by matthewdupre** [comment]
If you wanted to look further I'd suggest going looking at the Felix logs for reference to the pod (assuming it's local), or using the BIRD command line tool if it's a remote pod.
