### ISSUE TITLE
Error logs hit when deleting VM (after stop/starting felix)

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#834]
Repro scenario.  On Openstack Icehouse with calico:
- create a VM on a host.
- stop felix on that host
- start felix on that host
- delete the VM.

At the time of deletion, we get 8 errors in felix.log like this:
2015-09-30 15:40:06,016 [ERROR][31781/8] calico.felix.fiptables 569: Failed to delete chain felix-p-_a15fd76a273ef0d-o, giving up. Maybe it  is still referenced?

Readily reproducible at present on Master.

**Comment by fasaxc** [comment]
I believe I have diagnosed his issue.  It occurs whenever the final endpoint using a profile is deleted during the graceful restart window.  This issue is that 

* the IptablesUpdater recognises that the endpoint chain is still in use so it decides to stub it out
* during the graceful restart window, it doesn't stub out chains that it knows already exist (this prevents us from stubbing out a "leaf" chain because we learned about the "branch" chain before the leaf).

The fix should be to stub out chains during the GR window iff they were explicitly deleted.
