### ISSUE TITLE
plugin type="calico" failed (add): error creating calico client: could not initialize etcdv3 client: open /etc/calico/ssl/calico.pem: no such file or directory

### ISSUE THREAD

**Issue by DRP1988** [projectcalico/calico#8409]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by DRP1988** [comment]
How to fix this problem
![微信截图_20240115163648](https://github.com/projectcalico/calico/assets/48700368/f8c939ba-592e-43f7-aece-e59463b7fedc)
![微信截图_20240115163717](https://github.com/projectcalico/calico/assets/48700368/07f38dc8-3fff-4f34-9175-08a6836359fd)

**Comment by caseydavenport** [comment]
@DRP1988 please fill out the issue template when opening issues. We cannot help you without the context it provides. 

>  /etc/calico/ssl/calico.pem

You need to provide Calico with certificate data in order to connect to etcd using TLS. 

I do recommend installing Calico in the default mode, where it does not need to access etcd directly though: https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart
