### ISSUE TITLE
Terminating pod still receiving service traffic

### ISSUE THREAD

**Issue by nascd** [projectcalico/calico#8423]
Hi Calico team,
We recently noticed an issue where a CoreDNS pod that was stuck in Terminating status seemed to still be getting traffic sent to it.  We use the eBPF kube-proxy replacement in Calico, and we enable the use of endpoint slices for Felix via https://github.com/projectcalico/calico/blob/master/api/pkg/apis/projectcalico/v3/felixconfig.go#L501 (though I can't actually find any code that references that param).

When a Pod is in terminating state, Endpoint slices will still list the endpoint, but will include some additional context via endpoint conditions that applications can use to evaluate whether an endpoint should be treated as healthy and accepting of traffic.  My understanding is that terminating pods will have the ready condition set to false, while having the serving and terminating conditions set to true (ref: https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/).

I tried looking at how Calico evaluates endpoint slices and I found the membersFromEndpointSlice function in Felix' service index (ref: https://github.com/projectcalico/calico/blob/master/felix/serviceindex/serviceindex.go#L195) -- it doesn't appear as though that particular function evaluates endpoint conditions, but I'm not familiar with the calico codebase and it's not clear to me that I'm looking at the relevant method.  Can you please help me understand how Felix behaves with respect to endpointslice conditions, and whether it will continue to route traffic to terminating endpoints, as my empirical experience seems to indicate?

If that is the case, please accept this as a feature request to optionally consider the status of endpoint conditions and to exclude endpoints that are in the process of terminating.

Thank you!

## Expected Behavior
I expect pods in Terminating status to receive no service traffic.

## Current Behavior
A pod that is stuck in Terminating status appears to still receive service traffic.

## Possible Solution
Ensure that endpointslice conditions are evaluated, and if an endpointslice is stated as terminating, discontinue sending traffic to it.

## Steps to Reproduce (for bugs)
Create a service with two healthy backing pods.
Force one pod into a terminating status, for example by causing a network interruption on the node hosting it.
Evaluate that some traffic does not make it to your remaining healthy pod.

## Context
In the case of CoreDNS, this issue presents with clients having intermittent DNS resolution failures, and has the potential to be quite damaging to a cluster's health.

## Your Environment
calico 3.26, kubernetes 1.24, eBPF kube-proxy replacement with endpointslices enabled.

**Comment by tomastigera** [comment]
> My understanding is that terminating pods will have the ready condition set to false, while having the serving and terminating conditions set to true (ref: https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/).

That is correct and we already remove the Terminating backend from the NAT tables. So once a service backend is terminating, service does not redirect any new traffic to it anymore. However, existing connections are not broken until the pod is removed since that would break graceful shutdown during the `terminationGracePeriodSeconds`.

This said, a client that picked the terminating DNS backed will keep sending traffic to that backend as long as it is terminating. Once it is gone, the connection to that backend is GCed and a new backend is selected.

I believe that is the same behaviour as with k8s kube-proxy. We use the same frontend and it does not provide the information when the grace period ends so we cannot force GCing the connection at that time and we rely on what k8s tells us.

To bad that a pod may get stuck in terminating state. However, tha may need a resolution outside of Calico.

**Comment by tomastigera** [comment]
@nascd On a second thought, it may make sense to have the option to reap the UDP connections regardless of whether the pod is terminating or not :thinking:
