### ISSUE TITLE
IPv6 routing loss bug

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#8431]
## Expected Behavior

Translate to keep the route unchanged
![image](https://github.com/projectcalico/calico/assets/150658327/c7e43150-0681-44df-b9bd-9db789b688c4)

## Current Behavior

calico_backend: "bird"
Adding a new IPv6 address to the network card and sorting it before the default IPv6 address will result in the loss of IPv6 routing
## Steps to Reproduce (for bugs)

1.calico_backend: "bird"
2.
3.
4.

## Your Environment

* Calico version v1.23.6
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by coutinhop** [comment]
@smallemployees we need a bit more information in order to try and understand your issue better. You mentioned calico v1.23.6, is that a typo? Do you mean that's the kubernetes version by any chance?
Could you give us more details on how to reproduce your issue (how to set up a cluster similar to yours, do you use a cloud provider, is it bare metal, how many nodes, what encapsulation you're using, etc)?
