### ISSUE TITLE
external/public ip of eks node is written to wireguard allowed ips

### ISSUE THREAD

**Issue by MageekChiu** [projectcalico/calico#8508]
In aws eks, where calico is used to manage wireguard and enable encryption in transit.
In an eks clusters, there are private nodes with private ip/internal ip, and public nodes with public ip/external ip(eip).
As far as I am concerned, these eips are not supposed to be included In allowed ips, however, they are indeed included.
Thus, when other private nodes access the eip of the public nodes, the traffic actually goes through the encryption tunnel and the target public node have no idea how to response and the connection is broken.

k8s version:1.25  calico version: 3.26.1

I think there are 2 ways to settle this
1. Offer an option wether to include external ip or not
2. Exclude eip by default, cause the implementation of eip determines that any traffic with dst of this eip should not be directly delivered to the node but through a nat gateway instead(and the dst of the packet is transformed to the private ip of this node), the node itself has no idea how to handle a packet(directly delivered through the encryption tunnel) with dst of this eip

**Comment by aaaaaaaalex** [comment]
Hi, have you installed with operator or manifest? 
For clarity, are the private IPs also added for nodes with an EIP, or is only the EIP added?

Thanks

**Comment by aaaaaaaalex** [comment]
Thanks @MageekChiu. One more question that came to mind is - when you say a private node sends traffic to a public node, do you mean pods on each node communicating, or host-network processes? Trying to nail down if this is an issue of routing and network topology, or a misconfiguration of wireguard itself.

In isolation, I don't believe it's a bug that we are adding the public IP to the trusted IP's list, though there may be another issue cropping up as a result. Im curious why nodes in the same cluster would use a public IP rather than the private IP to communicate? Is there a service-IP / load balancer at play?

**Comment by tomastigera** [comment]
@MageekChiu any update?

**Comment by sridhartigera** [comment]
closing this issue. Feel free to reopen.
