### ISSUE TITLE
On AKS and GKE managed Calico, add a way to add specify tolerations

### ISSUE THREAD

**Issue by agateaux** [projectcalico/calico#8584]
## Expected Behavior
I our GKE and AKS clusters, we have 2 nodepools: one system without any specific taint or label, with only one node, and a application nodepool with taints and labels to avoid any system pod to run on the related nodes.

I'd like to add the possibility to add a toleration to these managed Calico, for them to run on my apps nodes.

## Current Behavior
On GKE, calico requires 2 replicas of calico-typha. There is an error because it seems they want to use the same port.
On AKS, it seems there is a pod anti affinity avoiding two replicas to run on the same node.

## Possible Solution
Remove these ports/or pod anti affinity, or add the possiblity to modify the specific AKS and GKE configuration.

## Steps to Reproduce (for bugs)
Provision a GKE cluster, with 2 node pools, on one region. First system node pool with only one node, and second nodepool with labels and taints
Provision the same AKS cluster, and try to launch at least 5 nodes on the apps to pool, in order to get more replicas of calico-typha.

## Context
We have unschedulable pods

## Your Environment
Please see above. Versions of AKS and GKE: 1.28

**Comment by caseydavenport** [comment]
The anti-affinity is correct, as Typha needs to run on separate nodes and needs to run with hostNetwork for bootstrapping purposes.

Where are you getting the Calico manfiest to install from for these clusters? Are you using BYO manifests or the install mechanisms supplied by GKE / AKS?

**Comment by agateaux** [comment]
> Where are you getting the Calico manfiest to install from for these clusters? Are you using BYO manifests or the install mechanisms supplied by GKE / AKS?

I'm using the install mechanisms supplied by GKE/AKS. 
I tried to override them but they always come back to their initial state.

**Comment by caseydavenport** [comment]
I think you should probably raise an issue with the GKE and AKS teams - Calico itself supports configuration of both affinity and tolerations, but it seems those platforms have integrated Calico in such a way that it is not available and are reconciling away changes to their manifests.

When using "manifest" install, the resources can be modified directly. 

Operator and helm based installs support this as described here: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.TyphaDeploymentPodSpec

An alternative would be to use something like BYO CNI so that you have full control: https://learn.microsoft.com/en-us/azure/aks/use-byo-cni?tabs=azure-cli

**Comment by agateaux** [comment]
Ok thank you, I'll reach Google and Microsoft customers' support in that cas.
