### ISSUE TITLE
calico/node is not ready: BIRD is not ready: BGP not established with 172.21.0.1

### ISSUE THREAD

**Issue by hubcomsix** [projectcalico/calico#8607]
# PossibleSolution
Add the parameter 
nodeAddressAutodetectionV4:
      interface: ens.*

**Comment by petercorrea** [comment]
Im experiencing the exact issue, any work around?

**Comment by coutinhop** [comment]
@hubcomsix or @petercorrea, there is very little information to go with right here (you might even have different issues, we can't be sure, I'd be cautious not to jump into conclusions here).

@hubcomsix could you fill in the whole issue template, so that we can have more info on your setup/versions/topology/etc? From the info you gave, it seems like you might have multiple network interfaces? In that case, yes, setting `nodeAddressAutodetectionV4` would be the right solution, but I can't know for sure as I said...
