### ISSUE TITLE
Bug  calico/key-cert-provisioner not tagged for 3.28.0

### ISSUE THREAD

**Issue by CodeGlitcher** [projectcalico/calico#8850]
## Expected Behavior
We used a Calico image set to pin the calico images to a digest.
The operator logs that the image: calico/key-cert-provisioner must be present in this image set.
When we used: `docker run quay.io/tigera/operator:v1.34.0 --print-images=list`
To find out what images calico uses it says:
docker.io/calico/key-cert-provisioner:v3.28.0

But this image does not exist:
docker pull docker.io/calico/key-cert-provisioner:v3.28.0
Error response from daemon: manifest for calico/key-cert-provisioner:v3.28.0 not found: manifest unknown: manifest unknown

## Current Behavior
Calico in its default configuration does not uses the key-cert-provisioner, but it is required in the image set.

## Possible Solution
1. ensure calico/key-cert-provisioner is published with the right tag.
2. Dont make key-cert-provisioner required in the image set, if calico installation does not uses this image.

## Steps to Reproduce (for bugs)
I dont have a setup that uses key-cert-provisioner.

## Context

I was preparing a upgrade from calico 3.27 to 3.28.
and the operator:  tigera/operator v1.33.0 to v1.34.0.

In our environment we have a private registry and we pull all images by digest.
So after installing the oprator 1.34 I got a error message that said:
calico/key-cert-provisioner was missing. 
Taking a closer look add the release notes I saw:
Move key-cert-provisioner to the monorepo [calico #8475](https://github.com/projectcalico/calico/pull/8475) 
After this i decided to rerun  --print-images=list command to find the new image I needed to add in the ImageSet.
But I was unable to pull this image.

## Your Environment

* Calico version 3.28
*  tigera/operator v1.34.0 
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.28.9
* Operating System and version: Almalinux 8
* Link to your project (optional):

**Comment by danudey** [comment]
Hey @CodeGlitcher, thanks for opening the issue! I've published [key-cert-provisioner on Docker Hub](https://hub.docker.com/r/calico/key-cert-provisioner/tags?name=v3.28.0), and you should be able to continue with your upgrade.

```
❯ docker pull docker.io/calico/key-cert-provisioner:v3.28.0
v3.28.0: Pulling from calico/key-cert-provisioner
Digest: sha256:155e81217a2af7fc211800a582af43466201d0bdcb2d1cb6d6939223a240c473
Status: Downloaded newer image for calico/key-cert-provisioner:v3.28.0
docker.io/calico/key-cert-provisioner:v3.28.0
```

The issue came about due to the migration of key-cert-provisioner to the monorepo and the change in version numbers interacting with the expectations of the release system. We'll have this resolved in time for the next release and update our postrelease tests to validate the deployment.

I'm going to close this issue now, but if anything else comes up please let us know.
