### ISSUE TITLE
Custom BGP configuration via extensions on BGPConfiguration and BGPPeer

### ISSUE THREAD

**Issue by RefluxMeds** [projectcalico/calico#8931]
Hi,

Is it possible to make a request for having custom BGP config in the Calico open source version?
https://docs.tigera.io/calico-enterprise/latest/networking/configuring/custom-bgp-config

Please allow this as we have cases not covered in the standard open source version, and my team would benefit greatly from having extensions enabled for BGPConfiguration and BGPPeer. 

Thanks!

**Comment by caseydavenport** [comment]
This feature is deprecated in Calico Enterprise because it's very difficult to support without breaking when new BGP template features are added. I think it's very very unlikely that we will add a native way to configure BIRD templates directly through the Calico API - the Calico team would be on the hook for any misconfiguration that occurs as a result of a user modifying our templates. That time would much better be spent reviewing PRs to implement the missing features.

**Comment by caseydavenport** [comment]
@RefluxMeds I know the BFD support is one you guys need, is there another feature missing that we should be aware of?

I'd like to get BFD support in natively, but at the moment we're still hoping someone can carry that one to a PR. I'd love to review it, but haven't had the time available to implement it myself.
