### ISSUE TITLE
Calico for Mesos Unified Containerizer (CNI) Demo is Broken

### ISSUE THREAD

**Issue by eepyaich** [projectcalico/calico#94]
In trying to fix the broken link in - /_site/v1.5/getting-started/mesos/demos/cni/index.html I couldn't actually work out where the link should point, nor what the actual instructions in that doc should be referring to (e.g. the instructions under stage 1 are wrong, as there is no calico-containers/mesos/cni-compose-demo directory).

**Comment by djosborne** [comment]
Ah yeah. This demo has some serious issues that need to be resolved.

Turns out, `docker-compose` isn't a good method to showcase Unified Containerizer networking since Mesos' Virtualization can't create an isolated container namespace in a docker container. Half of this demo is supposed to showcase Unified Containerizer functionality, so we need to kill this and come up with something better. Vagrant maybe?
