### ISSUE TITLE
Can I use calico to set networking of physical servers?

### ISSUE THREAD

**Issue by wx1982** [projectcalico/calico#958]
I wish，the whole networking can be in the same one workspace.

**Comment by fasaxc** [comment]
@wx1982 Is your goes to configure IP addresses and security policy for `eth0`, for example?  We don't support that yet but it's something we'd like to add.

**Comment by wx1982** [comment]
yes
so what time do you plan to support it

tkx

**Comment by fasaxc** [comment]
@wx1982 Unless someone sponsors the work, I'd guess 6-12 months before we add features in that area.

**Comment by elfchief** [comment]
If one were to remove "configure IP addresses" from the scope, and only wanted to generate security policy on physical interfaces, does that reduce the scope of this question/ask any? It seems like as long as the user was able to load host information into etcd, it shouldn't be too much of a stretch to then use that information to generate host iptables rules.

Is there any chance you could outline (in broad strokes) what it would take to add that level of management into Calico? My employer is currently working on a project where the ability to distribute security policy in this way is needed; Depending on the time and effort involved, we might be able to contribute towards making it happen.

**Comment by fasaxc** [comment]
@elfchief I think policy is the more straightforward piece to add.  I'm currently working on adding new "label-based" policy to Calico, allowing for powerful tiered policy.  My current thinking is that the new label-based policy would be the right way to add "bare metal" support.

In my current thinking, there are a few pieces that need to be done to support bare-metal:

- Agree a datamodel for the new changes.
- Add labels to hosts so that the new policy can reference them.
- Add a rule match criteria for interface name so we can apply different policy to different interfaces.
- Add code to manage and update the new iptables chains required.
- Add some way to configure it all (updates to the calicoctl command-line tool, for example).

**Comment by elfchief** [comment]
@fasaxc Awesome, thanks for the detailed rundown!

If we wanted to sponsor development of this, what would that entail, time- and money-wise? (I don't know that we do; I'm just information-gathering at the moment.)

**Comment by fasaxc** [comment]
@elfchief probably best to discuss in more detail on our slack channel.  You can get an invite here: https://calicousers-slackin.herokuapp.com/ if you're not already a member.

**Comment by fasaxc** [comment]
@wx1982 We've now added policy support for bare-metal interfaces.  It's available in the current pre-release of 1.4.0 and documented here: http://docs.projectcalico.org/en/latest/bare-metal.html.  

Please open a new issue if that doesn't cover your use-case.
