### ISSUE TITLE
Better handling of CIDR mismatches

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#962]
Would be nice to have a better way to tell when CIDRs don't match up - for example when workload endpoints have IP addresses that don't fall within a configured IP Pool.

Inspiration comes from trying to KDD on kubeadm, default pool being `192.168.0.0/16` whereas the default range for kubeadm is `10.244.0.0/16`, which causes problems.  Took a little while to spot this.

## Possible Solution

Perhaps some sort of warning or validation command that could be run to indicate potential problems with the deployment?

**Comment by ReSearchITEng** [comment]
Even after cleaning cluster of all ip allocations, and loading calico.yaml with:
```
 - name: CALICO_IPV4POOL_CIDR
              value: "10.244.0.0/16"
```
calico is loaded fine, but keep allocating from the 192.168.0.0/16 pool...

**Comment by caseydavenport** [comment]
@ReSearchITEng have you made sure you don't have the 192.168.0.0/16 pool around still?

e.g. calicoctl get ippools

**Comment by tmjd** [comment]
@ReSearchITEng `CALICO_IPV4POOL_CIDR` is only honored for initial pool creation that happens if there are no IP Pools defined.  So even if you've deleted all pods using the IP you would also have to delete the IP Pool that exists to have the honored. If you want to change the IP Pool after cluster creation I'd suggest editing the pool with the `calicoctl` command.

As Casey suggested you can check if the default pool that was originally created still exists.

**Comment by caseydavenport** [comment]
Somewhat related: https://github.com/projectcalico/calico/pull/1101
